// Do not edit this file
// Auto-generated from generate_translation_ts_file.tsx code
export const locales = ['en']
export const localeNames = {
  en: 'en-US',
}
export type Locales = 'en'
export const defaultLocale = 'en'
