export interface Action {
  icon?: any
  href: string
  title: string
  name?: string
  author: string
  description: string
  iconForeground?: string
  iconBackground?: string
}
export interface Plugin extends Action {
  npmDownloads?: number
  githubStars?: number
  readme?: string
  datePublished?: string
  dateModified?: string
  tutorial?: string
}
export const actions = [
  {
    name: 'capacitor-native-http',
    href: 'git+https://github.com/viniciusgandrade/capacitor-native-http.git',
    title: 'capacitor-native-http',
    description: 'Plugin capacitor para requisições nativas',
    author: 'viniciusgandrade1',
  },
  {
    name: '@bistroo/vite-plugin-capacitor',
    href: 'git+https://github.com/bistroo/vite-plugin-capacitor.git',
    title: 'vite-plugin-capacitor',
    description: 'Vite plugin for capacitor',
    author: 'bistroo-dev',
  },
  {
    name: 'capacitor-secure-storage-plugin',
    href: 'git+https://github.com/martinkasa/capacitor-secure-storage-plugin.git',
    title: 'capacitor-secure-storage-plugin',
    description: 'Securely store secrets such as usernames, passwords, tokens, certificates or other sensitive information (strings) on iOS & Android',
    author: 'martinkasa',
  },
  {
    name: 'capacitor-plugin-safe-area',
    href: 'git+https://github.com/AlwaysLoveme/capacitor-plugin-safe-area.git.git',
    title: 'capacitor-plugin-safe-area',
    description: 'a capacitor plugin to get SafeArea info on Android and IOS',
    author: 'zhuxian',
  },
  {
    name: '@capacitor-community/file-opener',
    href: 'git+https://github.com/capacitor-community/file-opener.git',
    title: 'file-opener',
    description: 'Capacitor File Opener. The plugin is able to open a file given the mimeType and the file uri.',
    author: 'jcesarmobile',
  },
  {
    name: 'appsflyer-capacitor-plugin',
    href: 'git+https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin.git',
    title: 'appsflyer-capacitor-plugin',
    description: 'AppsFlyer SDK plugin for Capacitor',
    author: 'amit-kremer93',
  },
  {
    name: 'pinia-plugin-capacitor-persist',
    href: 'git+https://github.com/craigrileyuk/pinia-plugin-capacitor-persist.git',
    title: 'pinia-plugin-capacitor-persist',
    description: 'A Vue 3 Pinia plugin which persists store content using the CapacitorJS Preferences store.',
    author: 'craigrileyuk',
  },
  {
    name: 'capacitor-plugin-app-tracking-transparency',
    href: 'git+https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency.git',
    title: 'capacitor-plugin-app-tracking-transparency',
    description: 'Capacitor plugin to request user authorization to access app-related data for tracking the user or the device.',
    author: 'mahnuh',
  },
  {
    name: '@capawesome/capacitor-app-update',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-app-update',
    description: 'Capacitor plugin that assists with app updates.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-native-settings',
    href: 'git+https://github.com/RaphaelWoude/capacitor-native-settings.git',
    title: 'capacitor-native-settings',
    description: 'Capacitor plugin to open native settings screens for android and iOS',
    author: 'dennisameling',
  },
  {
    name: '@capacitor-community/firebase-analytics',
    href: 'git+https://github.com/capacitor-community/firebase-analytics.git',
    title: 'firebase-analytics',
    description: 'A native plugin for firebase analytics.',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/preferences',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'preferences',
    description: 'The Preferences API provides a simple key/value persistent store for lightweight data.',
    author: 'itschaced',
  },
  {
    name: '@newrelic/newrelic-capacitor-plugin',
    href: 'git+https://github.com/newrelic/newrelic-capacitor-plugin.git',
    title: 'newrelic-capacitor-plugin',
    description: 'NewRelic Plugin for ionic Capacitor',
    author: 'newrelic',
  },
  {
    name: '@capacitor-firebase/crashlytics',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'crashlytics',
    description: 'Capacitor plugin for Firebase Crashlytics.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/in-app-review',
    href: 'git+https://github.com/capacitor-community/in-app-review.git',
    title: 'in-app-review',
    description: 'Lets you prompt users to submit app store ratings and reviews without leaving your app - using platform native dialogs.',
    author: 'jcesarmobile',
  },
  {
    name: '@codetrix-studio/capacitor-google-auth',
    href: 'git+https://github.com/CodetrixStudio/CapacitorGoogleAuth.git',
    title: 'capacitor-google-auth',
    description: 'Google Auth plugin for capacitor.',
    author: 'parveenkhtkr',
  },
  {
    name: '@capacitor-community/media',
    href: 'git+https://github.com/capacitor-community/media.git',
    title: 'media',
    description: 'Capacitor plugin for saving and retrieving photos and videos, and managing photo albums.',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/sqlite',
    href: 'git+https://github.com/capacitor-community/sqlite.git',
    title: 'sqlite',
    description: 'Community plugin for native & electron SQLite databases',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/device',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'device',
    description: 'The Device API exposes internal information about the device, such as the model and operating system version, along with user information such as unique ids.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-mlkit/barcode-scanning',
    href: 'git+https://github.com/capawesome-team/capacitor-mlkit.git',
    title: 'barcode-scanning',
    description: 'Capacitor plugin for ML Kit Barcode Scanning.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/intercom',
    href: 'git+https://github.com/capacitor-community/intercom.git',
    title: 'intercom',
    description: 'Enable Intercom features for Capacitor apps',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-firebase/analytics',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'analytics',
    description: 'Capacitor plugin for Firebase Analytics.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/camera-preview',
    href: 'git+https://github.com/capacitor-community/camera-preview.git',
    title: 'camera-preview',
    description: 'Camera preview',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/privacy-screen',
    href: 'git+https://github.com/capacitor-community/privacy-screen.git',
    title: 'privacy-screen',
    description: 'Capacitor plugin that protects your app from displaying a screenshot in Recents screen/App Switcher.',
    author: 'jcesarmobile',
  },
  {
    name: '@capawesome/capacitor-file-picker',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-file-picker',
    description: 'Capacitor plugin that allows the user to select a file.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/contacts',
    href: 'git+https://github.com/capacitor-community/contacts.git',
    title: 'contacts',
    description: 'Contacts Plugin for Capacitor',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/fcm',
    href: 'git+https://github.com/capacitor-community/fcm.git',
    title: 'fcm',
    description: 'Enable Firebase Cloud Messaging features for Capacitor apps',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/speech-recognition',
    href: 'git+https://github.com/capacitor-community/speech-recognition.git',
    title: 'speech-recognition',
    description: 'A native plugin for speech recognition',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-firebase/authentication',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'authentication',
    description: 'Capacitor plugin for Firebase Authentication.',
    author: 'robingenz',
  },
  {
    name: '@capacitor/app',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'app',
    description:
      'The App API handles high level App state and events.For example, this API emits events when the app enters and leaves the foreground, handles deeplinks, opens other apps, and manages persisted plugin state.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-firebase/remote-config',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'remote-config',
    description: 'Capacitor plugin for Firebase Remote Config.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/http',
    href: 'git+https://github.com/capacitor-community/http.git',
    title: 'http',
    description: 'A native HTTP plugin for CORS-free requests and file transfers',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/keep-awake',
    href: 'git+https://github.com/capacitor-community/keep-awake.git',
    title: 'keep-awake',
    description: 'Prevent your screen from getting some sleep!',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/screen-brightness',
    href: 'git+https://github.com/capacitor-community/screen-brightness.git',
    title: 'screen-brightness',
    description: 'control screen brightness on ios and android',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/filesystem',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'filesystem',
    description: 'The Filesystem API provides a NodeJS-like API for working with files on the device.',
    author: 'itschaced',
  },
  {
    name: '@appcues/capacitor',
    href: 'git+https://github.com/appcues/appcues-capacitor-plugin.git',
    title: 'capacitor',
    description: 'Capcitor plugin to bridge the native Android and iOS Appcues mobile SDKs in an Ionic application.',
    author: 'willianjusten',
  },
  {
    name: '@capacitor-firebase/app',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'app',
    description: 'Capacitor plugin for Firebase App.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/bluetooth-le',
    href: 'git+https://github.com/capacitor-community/bluetooth-le.git',
    title: 'bluetooth-le',
    description: 'Capacitor plugin for Bluetooth Low Energy ',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-firebase/messaging',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'messaging',
    description: 'Capacitor plugin for Firebase Cloud Messaging (FCM).',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/apple-sign-in',
    href: 'git+https://github.com/capacitor-community/apple-sign-in.git',
    title: 'apple-sign-in',
    description: 'Capacitor Sign in with Apple',
    author: 'jcesarmobile',
  },
  {
    name: '@transistorsoft/capacitor-background-fetch',
    href: 'git+https://github.com/transistorsoft/capacitor-background-fetch.git',
    title: 'capacitor-background-fetch',
    description: 'Periodic callbacks in the background for both IOS and Android',
    author: 'transistorsoft-admin',
  },
  {
    name: '@capacitor-community/native-audio',
    href: 'git+https://github.com/capacitor-community/native-audio.git',
    title: 'native-audio',
    description: 'A native plugin for native audio engine',
    author: 'jcesarmobile',
  },
  {
    name: '@capgo/capacitor-native-biometric',
    href: 'git+https://github.com/Cap-go/capacitor-native-biometric.git',
    title: 'capacitor-native-biometric',
    description: 'This plugin gives access to the native biometric apis for android and iOS',
    author: 'riderx',
  },
  {
    name: '@capgo/inappbrowser',
    href: 'git+https://github.com/Cap-go/capacitor-inappbrowser.git',
    title: 'inappbrowser',
    description: 'Capacitor plugin in app browser',
    author: 'riderx',
  },
  {
    name: '@aparajita/capacitor-biometric-auth',
    href: 'git+https://github.com/aparajita/capacitor-biometric-auth.git',
    title: 'capacitor-biometric-auth',
    description: 'Provides access to the native biometric auth & device security APIs for Capacitor apps',
    author: 'ckgaparajita',
  },
  {
    name: '@capgo/capacitor-social-login',
    href: 'git+https://github.com/Cap-go/capacitor-social-login.git',
    title: 'capacitor-social-login',
    description: 'All social logins in one plugin',
    author: 'riderx',
  },
  {
    name: '@capacitor-community/safe-area',
    href: 'git+https://github.com/capacitor-community/safe-area.git',
    title: 'safe-area',
    description: 'Capacitor Plugin that exposes the safe area insets from the native iOS/Android device to your web project.',
    author: 'jcesarmobile',
  },
  {
    name: '@aparajita/capacitor-secure-storage',
    href: 'git+https://github.com/aparajita/capacitor-secure-storage.git',
    title: 'capacitor-secure-storage',
    description: 'Capacitor 5+ plugin that provides secure storage for the iOS and Android',
    author: 'ckgaparajita',
  },
  {
    name: '@capacitor/status-bar',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'status-bar',
    description: 'The StatusBar API Provides methods for configuring the style of the Status Bar, along with showing or hiding it.',
    author: 'itschaced',
  },
  {
    name: '@capacitor/browser',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'browser',
    description: 'The Browser API provides the ability to open an in-app browser and subscribe to browser events.',
    author: 'itschaced',
  },
  {
    name: '@transistorsoft/capacitor-background-geolocation',
    href: 'git+https://github.com/transistorsoft/capacitor-background-geolocation.git',
    title: 'capacitor-background-geolocation',
    description: 'The most sophisticated cross platform Capacitor background location tracking & geofencing module with battery-conscious motion-detection intelligence',
    author: 'transistorsoft-admin',
  },
  {
    name: '@capawesome/capacitor-android-edge-to-edge-support',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-android-edge-to-edge-support',
    description: 'Capacitor plugin to support edge-to-edge display on Android.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/facebook-login',
    href: 'git+ssh://git@github.com/capacitor-community/facebook-login.git',
    title: 'facebook-login',
    description: 'A native plugin for Facebook Login',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-voice-recorder',
    href: 'git+https://github.com/tchvu3/capacitor-voice-recorder.git',
    title: 'capacitor-voice-recorder',
    description: 'Capacitor plugin for voice recording',
    author: 'tchvu3',
  },
  {
    name: '@bcyesil/capacitor-plugin-printer',
    href: 'git+https://github.com/BarisCanYesil/capacitor-plugin-printer.git',
    title: 'capacitor-plugin-printer',
    description: 'Capacitor plugin for printing HTML format value iOS/Android apps.',
    author: 'bariscanyesil',
  },
  {
    name: '@sentry/capacitor',
    href: 'git+https://github.com/getsentry/sentry-capacitor.git',
    title: 'capacitor',
    description: 'Official Sentry SDK for Capacitor',
    author: 'billyvg',
  },
  {
    name: '@capgo/capacitor-updater',
    href: 'git+https://github.com/Cap-go/capacitor-updater.git',
    title: 'capacitor-updater',
    description: 'Live update for capacitor apps',
    author: 'riderx',
  },
  {
    name: '@capawesome/capacitor-screen-orientation',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-screen-orientation',
    description: 'Capacitor plugin to lock/unlock the screen orientation.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-file-chunk',
    href: 'git+https://github.com/qrclip/capacitor-file-chunk.git',
    title: 'capacitor-file-chunk',
    description: 'Capacitor plugin to read and write files in chunks using a local server and without using capacitor bridge.',
    author: 'qrclip',
  },
  {
    name: '@capacitor/geolocation',
    href: 'git+https://github.com/ionic-team/capacitor-geolocation.git',
    title: 'geolocation',
    description:
      'The Geolocation API provides simple methods for getting and tracking the current position of the device using GPS, along with altitude, heading, and speed information if available.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-community/native-market',
    href: 'git+https://github.com/capacitor-community/native-market.git',
    title: 'native-market',
    description: 'A native market plugin for linking to google play or app store.',
    author: 'jcesarmobile',
  },
  {
    name: '@ua/capacitor-airship',
    href: 'git+https://github.com/urbanairship/capacitor-airship.git',
    title: 'capacitor-airship',
    description: 'Airship capacitor plugin',
    author: 'urbanairship',
  },
  {
    name: '@capawesome/capacitor-badge',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-badge',
    description: 'Capacitor plugin to access and update the badge number of the app icon.',
    author: 'robingenz',
  },
  {
    name: '@capacitor/barcode-scanner',
    href: 'git+github.com/ionic-team/capacitor-barcode-scanner.git',
    title: 'barcode-scanner',
    description: 'Capacitor plugin using Outsystems Barcode libs',
    author: 'itschaced',
  },
  {
    name: '@capacitor-community/app-icon',
    href: 'git+https://github.com/capacitor-community/app-icon.git',
    title: 'app-icon',
    description: 'Capacitor community plugin for changing an iOS app icon.',
    author: 'jcesarmobile',
  },
  {
    name: '@capawesome-team/capacitor-file-opener',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-file-opener',
    description: 'Capacitor plugin to open a file with the default application.',
    author: 'robingenz',
  },
  {
    name: '@jcesarmobile/ssl-skip',
    href: 'git+https://github.com/jcesarmobile/ssl-skip.git',
    title: 'ssl-skip',
    description: 'Capacitor plugin for skipping ssl checks',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-firebase/performance',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'performance',
    description: 'Capacitor plugin for Firebase Performance Monitoring.',
    author: 'robingenz',
  },
  {
    name: '@capawesome/capacitor-background-task',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-background-task',
    description: 'Capacitor plugin for running background tasks.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-jitsi-meet',
    href: 'git+https://github.com/calvinckho/capacitor-jitsi-meet.git',
    title: 'capacitor-jitsi-meet',
    description: 'This Ionic Capacitor plugin is created to make video calls through the free, open-sourced Jitsi video platform (https://meet.jit.si) on iOS and Android.',
    author: 'calvinckho',
  },
  {
    name: '@capacitor-community/text-to-speech',
    href: 'git+https://github.com/capacitor-community/text-to-speech.git',
    title: 'text-to-speech',
    description: 'Capacitor plugin for synthesizing speech from text.',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/camera',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'camera',
    description: 'The Camera API provides the ability to take a photo with the camera or choose an existing one from the photo album.',
    author: 'itschaced',
  },
  {
    name: '@ebarooni/capacitor-calendar',
    href: 'git+https://github.com/ebarooni/capacitor-calendar.git',
    title: 'capacitor-calendar',
    description: 'A capacitor plugin for managing calendar events on iOS and Android, with reminders support on iOS.',
    author: 'ebarooni',
  },
  {
    name: '@capacitor/splash-screen',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'splash-screen',
    description: 'The Splash Screen API provides methods for showing or hiding a Splash image.',
    author: 'itschaced',
  },
  {
    name: 'capacitor-rate-app',
    href: 'git+https://github.com/Nodonisko/capacitor-rate-app.git',
    title: 'capacitor-rate-app',
    description: 'Let users rate your app using native rate app dialog for both Android and iOS.',
    author: 'nodon',
  },
  {
    name: '@capacitor/inappbrowser',
    href: 'git+https://github.com/ionic-team/capacitor-os-inappbrowser.git',
    title: 'inappbrowser',
    description:
      "The InAppBrowser Plugin provides a web browser view that allows you to load any web page externally. It behaves as a standard web browser and is useful to load untrusted content without risking your application's security. It offers three different ways t",
    author: 'itschaced',
  },
  {
    name: '@capgo/native-audio',
    href: 'git+https://github.com/Cap-go/capacitor-native-audio.git',
    title: 'native-audio',
    description: 'A native plugin for native audio engine',
    author: 'riderx',
  },
  {
    name: '@capacitor/screen-orientation',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'screen-orientation',
    description: 'The Screen Orientation API provides methods to lock and unlock the screen orientation.',
    author: 'itschaced',
  },
  {
    name: '@recognizebv/capacitor-plugin-msauth',
    href: 'git+https://github.com/recognizegroup/capacitor-plugin-msauth.git',
    title: 'capacitor-plugin-msauth',
    description: 'This plugin enables MSAL support for Capacitor.',
    author: 'johankamp',
  },
  {
    name: 'capacitor-email-composer',
    href: 'git+https://github.com/EinfachHans/capacitor-email-composer.git',
    title: 'capacitor-email-composer',
    description: 'E-Mail Composer Plugin for Capacitor',
    author: 'hanskrywaa',
  },
  {
    name: '@capacitor/text-zoom',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'text-zoom',
    description: 'The Text Zoom API provides the ability to change Web View text size for visual accessibility.',
    author: 'itschaced',
  },
  {
    name: '@capacitor/keyboard',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'keyboard',
    description: 'The Keyboard API provides keyboard display and visibility control, along with event tracking when the keyboard shows and hides.',
    author: 'itschaced',
  },
  {
    name: '@capgo/nativegeocoder',
    href: 'git+https://github.com/Cap-go/capacitor-nativegeocoder.git',
    title: 'nativegeocoder',
    description: 'Capacitor plugin for native forward and reverse geocoding',
    author: 'riderx',
  },
  {
    name: '@capacitor/share',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'share',
    description: 'The Share API provides methods for sharing content in any sharing-enabled apps the user may have installed.',
    author: 'itschaced',
  },
  {
    name: 'capacitor-radar',
    href: 'git+https://github.com/radarlabs/capacitor-radar.git',
    title: 'capacitor-radar',
    description: 'Capacitor plugin for Radar, the leading geofencing and location tracking platform',
    author: 'nickpatrick-radar',
  },
  {
    name: '@capacitor/haptics',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'haptics',
    description: 'The Haptics API provides physical feedback to the user through touch or vibration.',
    author: 'itschaced',
  },
  {
    name: '@hugotomazi/capacitor-navigation-bar',
    href: 'git+https://github.com/hugotomazi/navigation-bar.git',
    title: 'capacitor-navigation-bar',
    description: 'Capacitor Plugin for Navigation Bar',
    author: 'hugotomazi',
  },
  {
    name: '@capacitor/action-sheet',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'action-sheet',
    description: 'The Action Sheet API provides access to native Action Sheets, which come up from the bottom of the screen and display actions a user can take.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-community/barcode-scanner',
    href: 'git+https://github.com/capacitor-community/barcode-scanner.git',
    title: 'barcode-scanner',
    description: 'A fast and efficient (QR) barcode scanner for Capacitor',
    author: 'jcesarmobile',
  },
  {
    name: '@capgo/capacitor-mute',
    href: 'git+https://github.com/Cap-go/capacitor-mute.git',
    title: 'capacitor-mute',
    description: 'Detect if the mute switch is enabled/disabled on a device',
    author: 'riderx',
  },
  {
    name: 'capacitor-video-player',
    href: 'git+https://github.com/harmonwood/capacitor-video-player.git',
    title: 'capacitor-video-player',
    description: 'custom Native Capacitor plugin to play a video',
    author: 'jeepq',
  },
  {
    name: '@capacitor-community/firebase-crashlytics',
    href: 'git+https://github.com/capacitor-community/firebase-crashlytics.git',
    title: 'firebase-crashlytics',
    description: 'Capacitor plugin for Firebase Crashlytics.',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/live-updates',
    href: 'git+https://github.com/ionic-team/capacitor-live-updates-plugin.git',
    title: 'live-updates',
    description: 'Official Live Updates plugin for Capacitor',
    author: 'itschaced',
  },
  {
    name: '@capacitor/network',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'network',
    description: 'The Network API provides network and connectivity information.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-firebase/firestore',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'firestore',
    description: 'Capacitor plugin for Firebase Cloud Firestore.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-ios-autofill-save-password',
    href: 'git+https://github.com/cuongpl/capacitor-ios-autofill-save-password.git',
    title: 'capacitor-ios-autofill-save-password',
    description: 'Prompt to display dialog for saving password to keychain for iOS webview app.',
    author: 'cuongpl',
  },
  {
    name: 'capacitor-apprate-gfc',
    href: 'git+https://github.com/SASGeniusFlashConception/capacitor-apprate-gfc.git',
    title: 'capacitor-apprate-gfc',
    description: "Le plugin capacitor-apprate-gfc est une implementation native qui permet aux utilisateurs d'évaluer facilement votre application",
    author: 'geniusflashconception',
  },
  {
    name: 'capacitor-blob-writer',
    href: 'git+https://github.com/diachedelic/capacitor-blob-writer.git',
    title: 'capacitor-blob-writer',
    description: 'Write javascript Blobs to the filesystem efficiently',
    author: 'diachedelic',
  },
  {
    name: '@cwoebker/capacitor-start-navigation',
    href: 'git+https://github.com/cwoebker/capacitor-start-navigation.git',
    title: 'capacitor-start-navigation',
    description: 'Starts navigation in the native maps application',
    author: 'cwoebker',
  },
  {
    name: '@capacitor-community/advertising-id',
    href: 'git+https://github.com/capacitor-community/advertising-id.git',
    title: 'advertising-id',
    description: 'Allows access to the IDFA (iOS) and GAID (Android)',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-firebase/app-check',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'app-check',
    description: 'Capacitor plugin for Firebase App Check.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-swipe-back-plugin',
    href: 'git+https://github.com/alesmraz/capacitor-plugin-swipe-back.git',
    title: 'capacitor-swipe-back-plugin',
    description:
      'Capacitor swipe back plugin. For Capacitor v3, v4 (0.0.3) and v5 (1.0.0+). For v2 use original plugin: https://github.com/diiiary/capacitor-plugin-ios-swipe-back',
    author: 'alesmraz',
  },
  {
    name: '@capacitor/toast',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'toast',
    description: 'The Toast API provides a notification pop up for displaying important information to a user. Just like real toast!',
    author: 'itschaced',
  },
  {
    name: '@aparajita/capacitor-dark-mode',
    href: 'git+https://github.com/aparajita/capacitor-dark-mode.git',
    title: 'capacitor-dark-mode',
    description: 'Universal dark mode support for Ionic web and native apps',
    author: 'ckgaparajita',
  },
  {
    name: 'hypertrack-sdk-ionic-capacitor',
    href: 'git+https://github.com/hypertrack/sdk-ionic-capacitor.git',
    title: 'hypertrack-sdk-ionic-capacitor',
    description: 'Capacitor plugin for HyperTrack generation SDKs',
    author: 'hypertrack',
  },
  { name: 'send-intent', href: 'git+https://github.com/carsten-klaffke/send-intent.git', title: 'send-intent', description: 'SendIntent', author: 'cklaffke' },
  {
    name: '@capacitor-community/admob',
    href: 'git+ssh://git@github.com/capacitor-community/admob.git',
    title: 'admob',
    description: 'A native plugin for AdMob',
    author: 'jcesarmobile',
  },
  {
    name: '@capgo/native-market',
    href: 'git+https://github.com/Cap-go/capacitor-native-market.git',
    title: 'native-market',
    description: 'A native market plugin for linking to google play or app store.',
    author: 'riderx',
  },
  {
    name: '@whiteguru/capacitor-plugin-file-opener',
    href: 'git+https://github.com/dragermrb/capacitor-plugin-file-opener.git',
    title: 'capacitor-plugin-file-opener',
    description: 'Capacitor plugin to open files',
    author: 'dragermrb',
  },
  {
    name: '@capawesome/capacitor-live-update',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-live-update',
    description: 'Capacitor plugin to update your app remotely in real-time.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-hce-plugin-int',
    href: 'git+https://github.com/Sanders3026/capacitor-hce-plugin.git',
    title: 'capacitor-hce-plugin-int',
    description: 'Plugin to make your capacitor app to support NFC HCE',
    author: 'sandijs',
  },
  {
    name: 'capacitor-screenshot',
    href: 'git+https://github.com/ludufre/capacitor-screenshot.git',
    title: 'capacitor-screenshot',
    description: 'This plugin take screenshot of the app or webpage',
    author: 'ludufre',
  },
  {
    name: '@whiteguru/capacitor-plugin-video-editor',
    href: 'git+https://github.com/dragermrb/capacitor-plugin-video-editor.git',
    title: 'capacitor-plugin-video-editor',
    description: 'Capacitor plugin to edit videos',
    author: 'dragermrb',
  },
  {
    name: '@capacitor/google-maps',
    href: 'git+https://github.com/ionic-team/capacitor-google-maps.git',
    title: 'google-maps',
    description: 'Google maps on Capacitor',
    author: 'itschaced',
  },
  {
    name: 'capacitor-native-biometric',
    href: 'git+https://github.com/epicshaggy/capacitor-native-biometric.git',
    title: 'capacitor-native-biometric',
    description: 'This plugin gives access to the native biometric apis for android and iOS',
    author: 'epicshaggy',
  },
  {
    name: '@capacitor/clipboard',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'clipboard',
    description: 'The Clipboard API enables copy and pasting to/from the system clipboard.',
    author: 'itschaced',
  },
  {
    name: '@capacitor/push-notifications',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'push-notifications',
    description: 'The Push Notifications API provides access to native push notifications.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-community/photoviewer',
    href: 'git+https://github.com/capacitor-community/photoviewer.git',
    title: 'photoviewer',
    description: 'PhotoViewer table images with fullscreen and sharing capabilities',
    author: 'jcesarmobile',
  },
  {
    name: '@capawesome-team/capacitor-android-battery-optimization',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-android-battery-optimization',
    description: 'Capacitor plugin to access battery optimization settings on Android.',
    author: 'robingenz',
  },
  {
    name: '@evva/capacitor-secure-storage-plugin',
    href: 'git+https://github.com/evva-sfw/capacitor-secure-storage-plugin.git',
    title: 'capacitor-secure-storage-plugin',
    description: 'Securely store secrets such as usernames, passwords, tokens, certificates or other sensitive information (strings) on iOS & Android',
    author: 'sfw-evva',
  },
  {
    name: 'capacitor-call-number',
    href: 'git+https://github.com/mantosh59/call-number.git',
    title: 'capacitor-call-number',
    description: 'Plugin to pick files/images/videos from android or ios.',
    author: 'devmantosh2019',
  },
  {
    name: 'capacitor-plugin-ios-webview-configurator',
    href: 'git+https://github.com/cellular/capacitor-plugin-ios-webview-configurator.git',
    title: 'capacitor-plugin-ios-webview-configurator',
    description: '""',
    author: 'dlehmhus',
  },
  {
    name: '@mozartec/capacitor-microphone',
    href: 'git+https://github.com/mozartec/capacitor-microphone.git',
    title: 'capacitor-microphone',
    description: 'This Microphone API provides the ability to interact with the microphone and record Audio',
    author: 'mozart-alkhateeb',
  },
  {
    name: '@revenuecat/purchases-capacitor',
    href: 'git+https://github.com/RevenueCat/purchases-capacitor.git',
    title: 'purchases-capacitor',
    description: 'Capacitor in-app purchases and subscriptions made easy. Support for iOS and Android.',
    author: 'vegaro',
  },
  {
    name: 'capacitor-plugin-developer-options',
    href: 'git+https://github.com/asephermann/capacitor-plugin-developer-options.git',
    title: 'capacitor-plugin-developer-options',
    description: 'Capacitor Plugin to check and open developer options',
    author: 'asephermann',
  },
  {
    name: '@capacitor-community/date-picker',
    href: 'git+https://github.com/capacitor-community/date-picker.git',
    title: 'date-picker',
    description: 'Native DateTime Picker Plugin for Capacitor Apps',
    author: 'jcesarmobile',
  },
  {
    name: '@capawesome/capacitor-torch',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-torch',
    description: 'Capacitor plugin for switching the flashlight on and off.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/device-security-detect',
    href: 'git+https://github.com/capacitor-community/device-security-detect.git',
    title: 'device-security-detect',
    description:
      'The Device Security Detect plugin is designed to provide comprehensive device security detection capabilities for Capacitor-based applications. It aims to detect the device has been rooted (Android) or jailbroken (iOS). By using this plugin, developers ca',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-firebase-auth',
    href: 'git+https://github.com/baumblatt/capacitor-firebase-auth.git',
    title: 'capacitor-firebase-auth',
    description: 'Capacitor plugin for Firebase Authentication',
    author: 'baumblatt',
  },
  { name: '@capgo/camera-preview', href: 'git+https://github.com/Cap-go/camera-preview.git', title: 'camera-preview', description: 'Camera preview', author: 'riderx' },
  {
    name: '@capacitor/app-launcher',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'app-launcher',
    description: 'The AppLauncher API allows to open other apps',
    author: 'itschaced',
  },
  {
    name: '@capacitor/dialog',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'dialog',
    description: 'The Dialog API provides methods for triggering native dialog windows for alerts, confirmations, and input prompts',
    author: 'itschaced',
  },
  {
    name: 'capacitor-branch-deep-links',
    href: 'git+https://github.com/BranchMetrics/capacitor-branch-deep-links.git',
    title: 'capacitor-branch-deep-links',
    description: 'Capacitor plugin for Branch.io deep links',
    author: 'echo_branch',
  },
  {
    name: '@bondulich/native-audio',
    href: 'git+https://github.com/bondulich/native-audio.git',
    title: 'native-audio',
    description: 'A native plugin for native audio engine',
    author: 'bondulich',
  },
  {
    name: '@capacitor-community/image-to-text',
    href: 'git+ssh://git@github.com/capacitor-community/image-to-text.git',
    title: 'image-to-text',
    description: 'Image to Text (OCR) Plugin for Capacitor',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-music-controls-plugin-v3',
    href: 'git+https://github.com/ingageco/capacitor-music-controls-plugin-v3.git',
    title: 'capacitor-music-controls-plugin-v3',
    description: 'Implementation of MusicControls for Capacitor 3+ projects',
    author: 'ingage',
  },
  {
    name: 'capacitor-document-scanner',
    href: 'git+https://github.com/WebsiteBeaver/capacitor-document-scanner.git',
    title: 'capacitor-document-scanner',
    description: 'A Capacitor plugin that lets you scan documents using Android and iOS',
    author: 'dmarcus',
  },
  {
    name: '@capawesome/capacitor-posthog',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-posthog',
    description: 'Unofficial Capacitor plugin for PostHog SDK.',
    author: 'robingenz',
  },
  {
    name: 'tailwind-capacitor',
    href: 'git+https://github.com/Cap-go/tailwind-capacitor.git',
    title: 'tailwind-capacitor',
    description: 'Tailwind plugin for Capacitor apps',
    author: 'riderx',
  },
  {
    name: '@capacitor/motion',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'motion',
    description: 'The Motion API tracks accelerometer and device orientation (compass heading, etc.)',
    author: 'itschaced',
  },
  {
    name: '@perfood/capacitor-healthkit',
    href: 'git+https://github.com/perfood/capacitor-healthkit.git',
    title: 'capacitor-healthkit',
    description: 'Capacitor plugin to read data from and write data to Apple Health',
    author: 'mahnuh',
  },
  {
    name: '@basecom-gmbh/capacitor-jailbreak-root-detection',
    href: 'git+https://github.com/Phil0xFF/capacitor-jailbreak-root-detection.git',
    title: 'capacitor-jailbreak-root-detection',
    description: 'Jailbreak Root detection Plugin for Capacitor',
    author: 'jordankniest',
  },
  {
    name: 'capacitor-pass-to-wallet',
    href: 'git+https://github.com/valentinAbundo/capacitor-pass-to-wallet.git.git',
    title: 'capacitor-pass-to-wallet',
    description: 'Allow to add .pkpass files to Apple Wallet',
    author: 'nitnelav97',
  },
  {
    name: '@capacitor-community/stripe',
    href: 'git+https://github.com/capacitor-community/stripe.git',
    title: 'stripe',
    description: 'Stripe SDK bindings for Capacitor Applications',
    author: 'jcesarmobile',
  },
  {
    name: 'cap-overlay-webview',
    href: 'git+https://github.com/vmagination/cap-overlay-webview.git',
    title: 'cap-overlay-webview',
    description: 'Capacitor webview plugin',
    author: 'vladya',
  },
  {
    name: '@capgo/capacitor-screen-recorder',
    href: 'git+https://github.com/Cap-go/capacitor-screen-recorder.git',
    title: 'capacitor-screen-recorder',
    description: "Record device's screen",
    author: 'riderx',
  },
  {
    name: '@capgo/capacitor-crisp',
    href: 'git+https://github.com/Cap-go/capacitor-crisp.git',
    title: 'capacitor-crisp',
    description: 'Crisp native SDK for capacitor',
    author: 'riderx',
  },
  {
    name: 'capacitor-plugin-scanbot-sdk',
    href: '',
    title: 'capacitor-plugin-scanbot-sdk',
    description: 'Scanbot Document and Barcode Scanner SDK for Capacitor',
    author: 'scanbot',
  },
  {
    name: '@capacitor/local-notifications',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'local-notifications',
    description: 'The Local Notifications API provides a way to schedule device notifications locally (i.e. without a server sending push notifications).',
    author: 'itschaced',
  },
  {
    name: '@microblink/blinkid-capacitor',
    href: 'git+https://github.com/BlinkID/blinkid-capacitor.git',
    title: 'blinkid-capacitor',
    description: 'A small and powerful ID card Capacitor plugin for BlinkID SDK',
    author: 'microblinkadmin',
  },
  {
    name: '@pantrist/capacitor-firebase-dynamic-links',
    href: 'git+https://github.com/Pantrist-dev/capacitor-firebase-dynamic-links.git',
    title: 'capacitor-firebase-dynamic-links',
    description: 'Capacitor Plugin for Firebase Dynamic Links',
    author: 'nico.lueg',
  },
  {
    name: 'capacitor-plugin-playlist',
    href: 'git+https://github.com/phiamo/capacitor-plugin-playlist.git',
    title: 'capacitor-plugin-playlist',
    description: 'Playlist ',
    author: 'phiamo',
  },
  {
    name: '@capawesome/capacitor-managed-configurations',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-managed-configurations',
    description: 'Capacitor plugin to access managed configuration settings.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-adjust-resize',
    href: 'git+https://github.com/NePheus/capacitor-adjust-resize.git',
    title: 'capacitor-adjust-resize',
    description: 'Auto adjust the native android layout when the keyboard opens. Needed when using translucent status and navigation bars.',
    author: 'nepheus',
  },
  {
    name: '@capgo/capacitor-data-storage-sqlite',
    href: 'git+https://github.com/Cap-go/capacitor-data-storage-sqlite.git',
    title: 'capacitor-data-storage-sqlite',
    description: 'SQLite Storage of key/value strings pair',
    author: 'riderx',
  },
  {
    name: 'capacitor-datawedge',
    href: 'git+https://github.com/jkbz64/capacitor-datawedge.git',
    title: 'capacitor-datawedge',
    description: 'DataWedge plugin for capacitor',
    author: 'jkbz',
  },
  {
    name: '@capawesome/capacitor-photo-editor',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-photo-editor',
    description: 'Capacitor plugin that allows the user to edit a photo.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/volume-buttons',
    href: 'git+https://github.com/capacitor-community/volume-buttons.git',
    title: 'volume-buttons',
    description: 'Capacitor Volume Buttons. The plugin enables to listen to hardware volume button presses',
    author: 'jcesarmobile',
  },
  {
    name: '@capgo/capacitor-flash',
    href: 'git+https://github.com/Cap-go/capacitor-flash.git',
    title: 'capacitor-flash',
    description: 'Switch the Flashlight / Torch of your device.',
    author: 'riderx',
  },
  {
    name: '@foodello/intercom',
    href: 'git+https://github.com/fiksuruoka-fi/intercom.git',
    title: 'intercom',
    description: 'Enable Intercom features for Capacitor apps',
    author: 'eljass',
  },
  {
    name: '@capgo/tailwind-capacitor',
    href: 'git+https://github.com/Cap-go/tailwind-capacitor.git',
    title: 'tailwind-capacitor',
    description: 'Tailwind plugin for Capacitor apps',
    author: 'riderx',
  },
  {
    name: '@remnote/capacitor-updater',
    href: 'git+https://github.com/Cap-go/capacitor-updater.git',
    title: 'capacitor-updater',
    description: 'OTA update for capacitor apps',
    author: 'mfranzs',
  },
  {
    name: '@capacitor-community/stripe-terminal',
    href: 'git+https://github.com/capacitor-community/stripe.git',
    title: 'stripe-terminal',
    description: 'Stripe SDK bindings for Capacitor Applications',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-appmetrica-plugin',
    href: 'git+https://github.com/virusv/capacitor-appmetrica-plugin.git',
    title: 'capacitor-appmetrica-plugin',
    description: 'Yandex App metrica plugin for Capacitor',
    author: 'virusv',
  },
  {
    name: '@capawesome-team/capacitor-datetime-picker',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-datetime-picker',
    description: 'Capacitor plugin that let the user easily enter both a date and a time.',
    author: 'robingenz',
  },
  {
    name: '@jofr/capacitor-media-session',
    href: 'git+https://github.com/jofr/capacitor-media-session.git',
    title: 'capacitor-media-session',
    description: 'Capacitor plugin for media notifications and platform media keys as well as background audio playback',
    author: 'jofr',
  },
  {
    name: '@michaelwolz/camera-preview-lite',
    href: 'git+https://github.com/michaelwolz/camera-preview-lite.git',
    title: 'camera-preview-lite',
    description: 'Fork of the capacitor-community/camera-preview plugin focusing on high resolution photos without bloating up the code.',
    author: 'michaelwolz',
  },
  {
    name: 'capacitor-plugin-useragent',
    href: 'git+https://github.com/asephermann/capacitor-plugin-useragent.git',
    title: 'capacitor-plugin-useragent',
    description: 'Allows you to change your User-Agent for HTTP requests.',
    author: 'asephermann',
  },
  {
    name: 'capacitor-plugin-security-check',
    href: 'git+https://github.com/indodevniaga/capacitor-plugin-security-check.git',
    title: 'capacitor-plugin-security-check',
    description: 'capacitor-plugin-security-check',
    author: 'greatdayhr',
  },
  {
    name: '@whiteguru/capacitor-plugin-facebook-login',
    href: 'git+https://github.com/dragermrb/capacitor-plugin-facebook-login.git',
    title: 'capacitor-plugin-facebook-login',
    description: 'Capacitor plugin to login with Facebook',
    author: 'dragermrb',
  },
  {
    name: 'capacitor-speaker-phone-toggle',
    href: 'git+https://github.com/javedshahzad/capacitor-speaker-phone-toggle.git',
    title: 'capacitor-speaker-phone-toggle',
    description: 'Capacitor plugin to audio toggle',
    author: 'javed-shahzad',
  },
  {
    name: '@pantrist/capacitor-plugin-ml-kit-text-recognition',
    href: 'git+https://github.com/Pantrist-dev/capacitor-plugin-ml-kit-text-recognition.git',
    title: 'capacitor-plugin-ml-kit-text-recognition',
    description: 'Capacitor Wrapper for TextRecognition of Gogoles ML-Kit',
    author: 'nico.lueg',
  },
  {
    name: '@aashu-dubey/capacitor-statusbar-safe-area',
    href: 'git+https://github.com/Aashu-Dubey/capacitor-statusbar-safe-area.git',
    title: 'capacitor-statusbar-safe-area',
    description: 'Get Status bar height and Safe area insets on Android & iOS.',
    author: 'aashu-dubey',
  },
  {
    name: '@jonz94/capacitor-sim',
    href: 'git+https://github.com/jonz94/capacitor-sim.git',
    title: 'capacitor-sim',
    description: "Capacitor plugin to get information from device's sim cards",
    author: 'jonz94',
  },
  {
    name: '@e-is/capacitor-bluetooth-serial',
    href: 'git+https://github.com/e-is/capacitor-bluetooth-serial.git',
    title: 'capacitor-bluetooth-serial',
    description: 'Capacitor Bluetooth Serial Plugin',
    author: 'blavenie',
  },
  {
    name: 'capacitor-antitampering',
    href: 'git+https://github.com/asephermann/capacitor-antitampering.git',
    title: 'capacitor-antitampering',
    description: 'Capacitor plugin to verifies the integrity of the static assets of your application, cheking if the files have changed since the original build.',
    author: 'asephermann',
  },
  {
    name: 'netshow-screen2-plugin',
    href: 'https://git.zhonghe.newline.com/fernando/netshow-screen2-plugin.git',
    title: 'netshow-screen2-plugin',
    description: 'Screen Sharing Capacitor Plugin',
    author: 'datenshi24',
  },
  {
    name: 'capacitor-hce-plugin',
    href: 'git+https://github.com/thangman22/capacitor-hce-plugin.git',
    title: 'capacitor-hce-plugin',
    description: 'Plugin to make your capacitor app to support NFC HCE',
    author: 'thangman22',
  },
  {
    name: '@capacitor/screen-reader',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'screen-reader',
    description: 'The Screen Reader API provides access to TalkBack/VoiceOver/etc. and provides simple text-to-speech capabilities for visual accessibility.',
    author: 'itschaced',
  },
  {
    name: '@capgo/capacitor-navigation-bar',
    href: 'git+https://github.com/Cap-go/capacitor-navigation-bar.git',
    title: 'capacitor-navigation-bar',
    description: 'Set navigation bar color for android lolipop and higher',
    author: 'riderx',
  },
  {
    name: '@capawesome/capacitor-app-review',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-app-review',
    description: 'Capacitor plugin that allows users to submit app store reviews and ratings.',
    author: 'robingenz',
  },
  {
    name: '@capgo/capacitor-shake',
    href: 'git+https://github.com/Cap-go/capacitor-shake.git',
    title: 'capacitor-shake',
    description: 'Detect shake gesture in device',
    author: 'riderx',
  },
  {
    name: '@dghathway/firebase-remote-config',
    href: 'git+https://github.com/capacitor-community/firebase-remote-config.git',
    title: 'firebase-remote-config',
    description: 'A native plugin for firebase remote config',
    author: 'dghathway',
  },
  {
    name: 'capacitor-read-native-setting',
    href: 'git+https://github.com/ingageco/capacitor-read-native-setting.git',
    title: 'capacitor-read-native-setting',
    description: 'A simple plugin to read from Info.plist on iOS and strings.xml on Android',
    author: 'ingage',
  },
  {
    name: '@capacitor-firebase/storage',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'storage',
    description: 'Capacitor plugin for Firebase Cloud Storage.',
    author: 'robingenz',
  },
  {
    name: 'metamap-capacitor-plugin',
    href: 'git+https://github.com/GetMetaMap/mati-capacitor-plugin.git',
    title: 'metamap-capacitor-plugin',
    description: 'Capacitor plugin for MetaMapSDK',
    author: 'getmetamap',
  },
  {
    name: '@falconeta/capacitor-wifi-connect',
    href: 'git+https://github.com/falconeta/capacitor-wifi-connect.git',
    title: 'capacitor-wifi-connect',
    description: 'plugin used for connect the device through Wifi also with prefix',
    author: 'falconeta-dev',
  },
  {
    name: '@anuradev/capacitor-background-mode',
    href: 'git+https://github.com/angeloraso/capacitor-background-mode.git.git',
    title: 'capacitor-background-mode',
    description: 'Capacitor plugin to enable background mode',
    author: 'araso',
  },
  {
    name: 'capacitor-suppress-longpress-gesture',
    href: 'git+https://github.com/Nikita-schetko/capacitor-suppress-longpress-gesture.git',
    title: 'capacitor-suppress-longpress-gesture',
    description: 'This plugin allows to suppress longpress gesture in iOS system. Designed for capacitor v6, and support previous versions also. Check readme.md',
    author: 'nikita_shchetko',
  },
  {
    name: 'capacitor-plugin-webview-cache',
    href: 'git+https://github.com/FrameworkSystemsGmbH/capacitor-plugin-webview-cache.git',
    title: 'capacitor-plugin-webview-cache',
    description: 'Clears Android WebView cache',
    author: 'fsdko',
  },
  {
    name: 'capacitor-plugin-purchase',
    href: 'git+https://github.com/scgscorp/capacitorpluginpurchase.git.git',
    title: 'capacitor-plugin-purchase',
    description: 'consumable products purchase',
    author: 'scgscorp',
  },
  {
    name: 'capacitor-gleap-plugin',
    href: 'git+https://github.com/GleapSDK/Capacitor-SDK.git',
    title: 'capacitor-gleap-plugin',
    description:
      'Gleap SDK for Capacitor is the easiest way to integrate Gleap into your Ionic apps! Achieve better app quality with comprehensive in-app bug reporting & customer feedback for your web-apps and websites. Many thanks to Stephan Nagel (congrapp) for his work',
    author: 'boehlerlukas',
  },
  {
    name: '@capacitor-community/video-recorder',
    href: 'git+https://github.com/capacitor-community/video-recorder.git',
    title: 'video-recorder',
    description: 'capacitor plugin to record video',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-android-shortcuts',
    href: 'git+https://github.com/NePheus/capacitor-android-shortcuts.git',
    title: 'capacitor-android-shortcuts',
    description: 'Add shortcuts in Android',
    author: 'nepheus',
  },
  {
    name: 'capacitor-plugin-camera',
    href: 'git+https://github.com/xulihang/capacitor-plugin-camera.git',
    title: 'capacitor-plugin-camera',
    description: 'A capacitor camera plugin',
    author: 'xulihang',
  },
  {
    name: 'capacitor-google-play-services-checker',
    href: 'git+https://github.com/asephermann/capacitor-google-play-services-checker.git',
    title: 'capacitor-google-play-services-checker',
    description: 'Capacitor Plugin Google Play Services Checker',
    author: 'asephermann',
  },
  {
    name: '@capacitor/background-runner',
    href: 'git+https://github.com/ionic-team/capacitor-background-runner.git',
    title: 'background-runner',
    description: 'Capacitor Background Runner',
    author: 'itschaced',
  },
  {
    name: '@adeprez/capacitor-user-agent',
    href: 'git+https://github.com/adeprez/capacitor-user-agent.git',
    title: 'capacitor-user-agent',
    description: 'User Agent get/set/reset plugin for Capacitor',
    author: 'adeprez',
  },
  {
    name: 'capacitor-stripe-terminal',
    href: 'git+https://github.com/eventOneHQ/capacitor-stripe-terminal.git',
    title: 'capacitor-stripe-terminal',
    description: 'Capacitor plugin for Stripe Terminal (credit card readers).',
    author: 'nprail',
  },
  {
    name: '@adplorg/capacitor-in-app-purchase',
    href: 'git+https://github.com/adpl-repos/capacitor-in-app-purchase.git.git',
    title: 'capacitor-in-app-purchase',
    description: 'Capacitor plugin for In App Purchase',
    author: 'kbala-adpl',
  },
  {
    name: '@okode/capacitor-marketingcloud',
    href: 'git+https://github.com/okode/capacitor-marketingcloud.git',
    title: 'capacitor-marketingcloud',
    description: 'MarketingCloud Capacitor Plugin',
    author: 'okode',
  },
  {
    name: '@freeedcom/capacitor-facebook-login',
    href: 'git+ssh://git@github.com/freeedcom/capacitor-facebook-login.git',
    title: 'capacitor-facebook-login',
    description: 'A native plugin for Facebook Login',
    author: 'aidar-freeed',
  },
  {
    name: '@houseninja/capacitor-mixpanel',
    href: 'git+https://github.com/houseninjadojo/capacitor-mixpanel.git',
    title: 'capacitor-mixpanel',
    description: 'Capacitor plugin for Mixpanel',
    author: 'mileszim',
  },
  {
    name: 'capacitor-native-google-one-tap-signin',
    href: 'git+https://github.com/inouiw/capacitor-native-google-one-tap-signin.git',
    title: 'capacitor-native-google-one-tap-signin',
    description: 'Google One Tap sign-in plugin for capacitor.',
    author: 'inouiw',
  },
  {
    name: '@independo/capacitor-voice-recorder',
    href: 'git+https://github.com/independo-gmbh/capacitor-voice-recorder.git',
    title: 'capacitor-voice-recorder',
    description: 'Capacitor plugin for voice recording',
    author: 'kstruempf',
  },
  {
    name: 'capacitor-biometric-auth',
    href: 'git+https://github.com/arielhernandezmusa/capacitor-biometric-auth.git',
    title: 'capacitor-biometric-auth',
    description: 'Complete',
    author: 'arielhernandezmusa',
  },
  {
    name: '@whiteguru/capacitor-plugin-file-picker',
    href: 'git+https://github.com/dragermrb/capacitor-plugin-file-picker.git',
    title: 'capacitor-plugin-file-picker',
    description: 'Capacitor plugin to pick files',
    author: 'dragermrb',
  },
  {
    name: '@unsou/capacitor-intercom',
    href: 'git+https://github.com/unsou/capacitor-intercom.git',
    title: 'capacitor-intercom',
    description: 'Enable Intercom features for Capacitor apps',
    author: 'maxnowack',
  },
  {
    name: '@rollershop/capacitor-emarsys-sdk',
    href: 'git+https://github.com/roller-ecom/capacitor-emarsys-sdk.git',
    title: 'capacitor-emarsys-sdk',
    description: 'Capacitor Plugin that wraps the Emarsys SDK',
    author: 'roller-shop',
  },
  { name: 'capacitor-zeroconf', href: 'git+https://github.com/trik/capacitor-zeroconf.git', title: 'capacitor-zeroconf', description: 'Capacitor ZeroConf plugin', author: 'trik' },
  {
    name: '@capacitor-community/tap-jacking',
    href: 'git+https://github.com/capacitor-community/tap-jacking.git',
    title: 'tap-jacking',
    description: 'Capacitor Plugin to prevent tap jacking in Android',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/google-maps',
    href: 'git+https://github.com/capacitor-community/google-maps.git',
    title: 'google-maps',
    description: 'Plugin using native Maps API for Android and iOS.',
    author: 'jcesarmobile',
  },
  {
    name: '@capgo/home-indicator',
    href: 'git+https://github.com/Cap-go/home-indicator.git',
    title: 'home-indicator',
    description: 'hide and show home button indicator in Capacitor app',
    author: 'riderx',
  },
  {
    name: '@capawesome/capacitor-cloudinary',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-cloudinary',
    description: 'Unofficial Capacitor plugin for integrating with Cloudinary.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-freerasp',
    href: 'git+https://github.com/talsec/Free-RASP-Capacitor.git',
    title: 'capacitor-freerasp',
    description: 'Capacitor plugin for improving app security and threat monitoring on Android and iOS mobile devices',
    author: 'talsec-app',
  },
  {
    name: '@fresha/capacitor-plugin-applepay',
    href: 'git+https://github.com/fresha/capacitor-plugin-applepay.git',
    title: 'capacitor-plugin-applepay',
    description: 'Apple Pay plugin for Capacitor',
    author: 'dziala',
  },
  {
    name: 'capacitor-subscriptions',
    href: 'git+https://github.com/CraigRonald555/capacitor-subscriptions.git.git',
    title: 'capacitor-subscriptions',
    description: 'A capacitor plugin which simplifies subscription handling - implementing StoreKit 2 and Google Billing',
    author: 'craigronald',
  },
  {
    name: 'capacitor-ios-app-tracking',
    href: 'git+https://github.com/migtam628/capacitor-ios-app-tracking.git',
    title: 'capacitor-ios-app-tracking',
    description: 'App AD Tracking for iOS 14 and above',
    author: 'migtamrod1',
  },
  {
    name: '@capacitor-community/stripe-identity',
    href: 'git+https://github.com/capacitor-community/stripe.git',
    title: 'stripe-identity',
    description: 'Stripe Identity SDK bindings for Capacitor Applications',
    author: 'jcesarmobile',
  },
  {
    name: '@leadscout/http',
    href: 'git+https://github.com/Homscout/http.git',
    title: 'http',
    description: 'A native HTTP plugin for CORS-free requests and file transfers',
    author: 'mrozema',
  },
  {
    name: '@capawesome-team/capacitor-android-foreground-service',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-android-foreground-service',
    description: 'Capacitor plugin to run a foreground service on Android.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-request-location',
    href: 'git+https://github.com/asephermann/capacitor-request-location.git',
    title: 'capacitor-request-location',
    description: 'A Capacitor plugin to check and request permission for using location service (Android)',
    author: 'asephermann',
  },
  {
    name: 'capacitor-swipe-gestures-plugin',
    href: 'git+https://github.com/krzysztofkostecki/capacitor-plugin-swipe-gestures.git',
    title: 'capacitor-swipe-gestures-plugin',
    description: 'Capacitor swipe gestures plugin.',
    author: 'krzysztofkostecki',
  },
  {
    name: 'capacitor-plugin-siri-shorts',
    href: 'git+https://github.com/TimoZacherl/capacitor-plugin-siri-shortcuts.git',
    title: 'capacitor-plugin-siri-shorts',
    description: 'Capacitor Plugin for Siri Shortcuts',
    author: 'timozacherl',
  },
  {
    name: '@langx/capacitor-voice-recorder',
    href: 'git+https://github.com/langx/capacitor-voice-recorder.git',
    title: 'capacitor-voice-recorder',
    description: 'Capacitor plugin for voice recording',
    author: 'xuelink',
  },
  {
    name: 'enode-capacitor',
    href: 'git+https://github.com/eneco-online/enode-capacitor.git',
    title: 'enode-capacitor',
    description: 'Enode SDK for Capacitor',
    author: 'eneco-valentijn',
  },
  {
    name: 'capacitor-plugin-purchase-ios',
    href: 'git+https://github.com/MrZenW/capacitor-plugin-purchase-ios.git',
    title: 'capacitor-plugin-purchase-ios',
    description: 'cool',
    author: 'mrzenw',
  },
  {
    name: '@easy-connect/inappbrowser',
    href: 'git+https://github.com/Ticket-Gretchen/capacitor-inappbrowser.git',
    title: 'inappbrowser',
    description: 'Capacitor plugin in app browser',
    author: 'easyconnect',
  },
  {
    name: '@capacitor-firebase/functions',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'functions',
    description: 'Capacitor plugin for Firebase Cloud Functions.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/mdm-appconfig',
    href: 'git+https://github.com/capacitor-community/mdm-appconfig.git',
    title: 'mdm-appconfig',
    description: 'Capacitor community plugin for reading app configurations written by a MDM (see appconfig.org) such as VMWare Workspace One.',
    author: 'jcesarmobile',
  },
  {
    name: '@idpass/smartscanner-capacitor',
    href: 'git+https://github.com/idpass/smartscanner-capacitor.git',
    title: 'smartscanner-capacitor',
    description: 'Capacitor plugin for the SmartScanner Core library to scan MRZ, NFC and barcodes',
    author: 'uocnb',
  },
  {
    name: 'capacitor-greatday-camera',
    href: 'git+https://github.com/asephermann/capacitor-greatday-camera.git',
    title: 'capacitor-greatday-camera',
    description: 'The capacitor plugin for camera function',
    author: 'asephermann',
  },
  {
    name: '@avo121/mati-capacitor-plugin',
    href: 'git+https://github.com/GetMetaMap/mati-capacitor-plugin.git',
    title: 'mati-capacitor-plugin',
    description: 'Capacitor plugin for MetaMapSDK',
    author: 'vadim.korelin',
  },
  {
    name: '@olo/pay-capacitor',
    href: 'git+https://github.com/ololabs/olo-pay-capacitor-plugin-releases.git',
    title: 'pay-capacitor',
    description: 'Olo Pay SDK Capacitor Plugin',
    author: 'carol.cuatt',
  },
  {
    name: '@joinflux/capacitor-segment',
    href: 'git+https://github.com/joinflux/capacitor-segment.git',
    title: 'capacitor-segment',
    description: 'A Capacitor plugin for Segment analytics',
    author: 'gugahoi',
  },
  {
    name: '@selaliadobor/apple-sign-in',
    href: 'git+https://github.com/capacitor-community/apple-sign-in.git',
    title: 'apple-sign-in',
    description: 'Capacitor Sign in with Apple',
    author: 'selaliadobor',
  },
  { name: '@zeply-ou/google-pay-capacitor', href: '', title: 'google-pay-capacitor', description: 'Google Pay plugin for Capacitor', author: 'nikos.mastragelis' },
  {
    name: '@ttdev/capacitor-secure-storage-plugin',
    href: 'git+https://github.com/martinkasa/capacitor-secure-storage-plugin.git',
    title: 'capacitor-secure-storage-plugin',
    description: 'Securely store secrets such as usernames, passwords, tokens, certificates or other sensitive information (strings) on iOS & Android',
    author: 'ttdev',
  },
  {
    name: '@nitra/capacitor-plugin-smartmerch-camera',
    href: 'git+https://github.com/abinbevefes/capacitor-plugin-smartmerch-camera.git',
    title: 'capacitor-plugin-smartmerch-camera',
    description: '-',
    author: 'vitaliytv',
  },
  {
    name: '@evva/abrevva-capacitor',
    href: 'git+https://github.com/evva-sfw/abrevva-capacitor.git',
    title: 'abrevva-capacitor',
    description: 'Collection of tools to work with electronic EVVA access components.',
    author: 'sfw-evva',
  },
  {
    name: 'capacitor-mock-location-checker',
    href: 'git+https://github.com/asephermann/capacitor-mock-location-checker.git',
    title: 'capacitor-mock-location-checker',
    description: 'Capacitor plugin to avoid location mocking',
    author: 'asephermann',
  },
  {
    name: '@microblink/blinkcard-capacitor',
    href: 'git+https://github.com/blinkcard/blinkcard-capacitor.git',
    title: 'blinkcard-capacitor',
    description: 'AI-driven credit card scanning for cross-platform apps built with Capacitor.',
    author: 'mb-mpisacic',
  },
  {
    name: 'capacitor-custom-google-maps',
    href: 'git+https://github.com/nasasutisna/capacitor-custom-google-maps.git',
    title: 'capacitor-custom-google-maps',
    description: 'capacitor custom plugin google maps',
    author: 'nasa.sutisna',
  },
  {
    name: 'capacitor-areas',
    href: 'git+https://github.com/NePheus/capacitor-areas.git',
    title: 'capacitor-areas',
    description: 'This plugin provides functions to detect the devices safe area and the status bar and navigation bar height.',
    author: 'nepheus',
  },
  {
    name: '@bperel/object-detection',
    href: 'git+https://github.com/capawesome-team/capacitor-mlkit.git',
    title: 'object-detection',
    description: 'Capacitor plugin for ML Kit Object Detection.',
    author: 'bperel',
  },
  {
    name: 'capacitor-aad',
    href: 'https://github.com/leopq/capacitor-azure-active-directory.git',
    title: 'capacitor-aad',
    description: 'Capacitor plugin used to authenticate with Azure Active Directory on apps and PWAs!',
    author: 'leopq',
  },
  {
    name: '@aposnovmati/mati-capacitor-plugin',
    href: 'git+https://github.com/GetMati/mati-capacitor-plugin.git',
    title: 'mati-capacitor-plugin',
    description: 'Capacitor plugin for MatiSDK',
    author: 'aposnovmati',
  },
  {
    name: '@skektec/capacitor-contacts',
    href: 'git+https://github.com/Skektec/Capacitor-V7-Contacts-Port.git',
    title: 'capacitor-contacts',
    description: 'Contacts Plugin for Capacitor, ported for Capacitor V7',
    author: 'skektec',
  },
  {
    name: 'sq-capacitor-plugin-ios-swipe-back',
    href: '',
    title: 'sq-capacitor-plugin-ios-swipe-back',
    description: 'Enable the back/forward swipe guestures support for iOS',
    author: 'a.poplavsky',
  },
  {
    name: '@teamhive/capacitor-single-signon',
    href: 'git+https://github.com/TeamHive/capacitor-single-sign-on.git',
    title: 'capacitor-single-signon',
    description: 'This plugin is designed to streamline the single signon process between android and ios',
    author: 'emrado',
  },
  {
    name: '@atroo/capacitor-secure-storage-plugin',
    href: 'git+https://github.com/atroo/capacitor-secure-storage-plugin.git.git',
    title: 'capacitor-secure-storage-plugin',
    description: 'Securely store secrets such as usernames, passwords, tokens, certificates or other sensitive information (strings) on iOS & Android',
    author: 'atroo',
  },
  {
    name: '@capacitor-community/exif',
    href: 'git+https://github.com/capacitor-community/exif.git',
    title: 'exif',
    description: 'This plugin offers utility functions for interacting with image exif metadata',
    author: 'jcesarmobile',
  },
  {
    name: '@teamhive/capacitor-video-recorder',
    href: 'git+https://github.com/TeamHive/capacitor-video-recorder.git',
    title: 'capacitor-video-recorder',
    description: 'Records video',
    author: 'emrado',
  },
  {
    name: 'capacitor-kakao-login-plugin',
    href: 'git+https://github.com/nerdFrenzs/capacitor-kakao-login-plugin.git',
    title: 'capacitor-kakao-login-plugin',
    description: 'This plugin is only used in Native capacitor(not web implemented)',
    author: 'nerdfrenzs',
  },
  {
    name: '@aparajita/capacitor-ios-silent-notifications',
    href: 'git+https://github.com/aparajita/capacitor-ios-silent-notifications.git',
    title: 'capacitor-ios-silent-notifications',
    description: 'Capacitor 5+ plugin that provides silent notification support for iOS',
    author: 'ckgaparajita',
  },
  {
    name: '@danyalwe/capacitor-sensors',
    href: 'git+https://github.com/zAlweNy26/capacitor-sensors.git',
    title: 'capacitor-sensors',
    description: 'Get access to every sensor present in the device!',
    author: 'danyalwe',
  },
  {
    name: '@capawesome/capacitor-screenshot',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-screenshot',
    description: 'Capacitor plugin for taking screenshots.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-biometric-lock',
    href: 'git+https://github.com/aeharding/capacitor-biometric-lock.git',
    title: 'capacitor-biometric-lock',
    description: 'Lock and unlock an app with biometrics',
    author: 'aeharding',
  },
  {
    name: '@nativescript/capacitor',
    href: 'git+https://github.com/NativeScript/capacitor.git',
    title: 'capacitor',
    description: 'NativeScript for Capacitor',
    author: 'mukaschultze',
  },
  {
    name: 'capacitor-share-extension',
    href: 'git+https://github.com/calvinckho/capacitor-share-extension.git',
    title: 'capacitor-share-extension',
    description: 'A Capacitor Plugin that provides native capabilities to retrieve media files sent via iOS Share Extension and Android Send Intent events',
    author: 'calvinckho',
  },
  {
    name: '@proteansoftware/capacitor-start-navigation',
    href: 'git+https://github.com/ProteanSoftware/capacitor-start-navigation.git',
    title: 'capacitor-start-navigation',
    description: 'Starts navigation in the native maps application',
    author: 'dave_proteansoftware',
  },
  {
    name: '@okode/capacitor-dynatrace',
    href: 'git+https://github.com/okode/capacitor-dynatrace.git',
    title: 'capacitor-dynatrace',
    description: 'Dynatrace plugin for Capacitor',
    author: 'okode',
  },
  {
    name: 'capacitor-nfc-launch',
    href: 'git+https://github.com/NePheus/capacitor-nfc-launch.git',
    title: 'capacitor-nfc-launch',
    description: 'Launch the app by a NFC tag and read the data',
    author: 'nepheus',
  },
  {
    name: 'capacitor-razorpay',
    href: 'git+https://github.com/razorpay/razorpay-cordova.git',
    title: 'capacitor-razorpay',
    description: 'This plugin is used for integration related to ionic Capacitor and its latest versions.',
    author: 'vivek_shindhe9604',
  },
  { name: '@admob-plus/capacitor', href: 'git+https://github.com/admob-plus/admob-plus.git', title: 'capacitor', description: 'AdMob Plus Capacitor Plugin', author: 'ratson' },
  {
    name: '@contentsquare/capacitor-plugin',
    href: '',
    title: 'capacitor-plugin',
    description: 'A Capacitor plugin that wraps the Contentsquare SDK with an easy to use API',
    author: 'cyberdandy',
  },
  {
    name: 'capacitor-music-controls-plugin',
    href: 'git+https://github.com/ingageco/capacitor-music-controls-plugin.git',
    title: 'capacitor-music-controls-plugin',
    description: 'Implementation of MusicControls for Capacitor 3+ projects',
    author: 'ingage',
  },
  {
    name: 'capacitor-luna-id-sdk',
    href: 'git+https://github.com/qliqdev/capacitor-luna-id-sdk.git',
    title: 'capacitor-luna-id-sdk',
    description: 'LUNA SDK is a face recognition and analysis system that provides efficient and accurate processing of faces in images and video streams',
    author: 'abbas.fatullaev',
  },
  {
    name: '@agorapulse/capacitor-mediastore',
    href: 'git+https://github.com/agorapulse/capacitor-mediastore.git',
    title: 'capacitor-mediastore',
    description: 'Manage Android media files',
    author: 'benorama',
  },
  {
    name: '@capacitor-community/security-provider',
    href: 'git+https://github.com/capacitor-community/security-provider.git',
    title: 'security-provider',
    description: 'Capacitor plugin with methods to check and update the Android Security Provider',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-plugin-audiosession-bluetooth',
    href: 'git+https://github.com/Jun-Murakami/capacitor-plugin-audiosession-bluetooth.git',
    title: 'capacitor-plugin-audiosession-bluetooth',
    description:
      'This capacitor plugin allows iOS applications to get notified audio about interrupts & route changes (for example when a headset is connected), and also query and override the audio device in use.',
    author: 'jun-murakami',
  },
  {
    name: 'app-tracking-transparency-capacitor-ionic',
    href: 'git+https://github.com/vipinsaini0/app-tracking-transparency-capacitor-ionic.git',
    title: 'app-tracking-transparency-capacitor-ionic',
    description: 'Capacitor plugin to request user authorization to access app-related data for tracking the user or the device.',
    author: 'vipinsaini0',
  },
  {
    name: 'cleverpush-capacitor-sdk',
    href: 'git+https://github.com/cleverpush/cleverpush-capacitor-sdk.git',
    title: 'cleverpush-capacitor-sdk',
    description: 'CleverPush Capacitor SDK',
    author: 'gbhrdt',
  },
  {
    name: '@squareetlabs/capacitor-openwith',
    href: 'git+https://github.com/squareetlabs/capacitor-openwith.git',
    title: 'capacitor-openwith',
    description: 'Capacitor plugin to handle files shared from other apps',
    author: 'squareetlabs',
  },
  {
    name: 'capacitor-webview-print',
    href: 'git+https://github.com/5uper/capacitor-webview-print.git',
    title: 'capacitor-webview-print',
    description: 'This is a Capacitor plugin for printing the webview. It supports the Web, iOS and Android Platform.',
    author: '5uper',
  },
  {
    name: '@capacitor-community/appcenter',
    href: 'git+https://github.com/capacitor-community/appcenter-sdk-capacitor.git',
    title: 'appcenter',
    description: "Capacitor Plugin for Microsoft's App Center SDK.",
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-face-id',
    href: 'git+https://github.com/danielsogl/capacitor-face-id.git',
    title: 'capacitor-face-id',
    description: 'Allow users to authenticate with Face ID or Touch ID on iOS devices',
    author: 'danielsogl',
  },
  {
    name: 'capacitor-plugin-filedownload',
    href: 'git+https://github.com/AlwaysLoveme/capacitor-plugin-filedownload.git.git',
    title: 'capacitor-plugin-filedownload',
    description: 'a file download plugin for capacitor3.0+',
    author: 'zhuxian',
  },
  {
    name: '@okode/capacitor-plugin-secure-share',
    href: 'git+https://github.com/okode/capacitor-plugin-secure-share.git',
    title: 'capacitor-plugin-secure-share',
    description: 'Capacitor Secure Share Plugin',
    author: 'okode',
  },
  {
    name: '@capawesome/capacitor-app-shortcuts',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-app-shortcuts',
    description: 'Capacitor plugin to manage app shortcuts and quick actions.',
    author: 'robingenz',
  },
  {
    name: '@belongnet/capacitor-google-auth',
    href: 'git+https://github.com/belongnet/CapacitorGoogleAuth.git',
    title: 'capacitor-google-auth',
    description: 'Google Auth plugin for capacitor.',
    author: 'reslear',
  },
  {
    name: 'capacitor-imessage',
    href: 'git+https://github.com/palauaandsons/capacitor-imessage.git',
    title: 'capacitor-imessage',
    description: 'Capacitor plugin for iMessage',
    author: 'javier.martinez',
  },
  {
    name: '@aalzehla/capacitor-jailbreak-root-detection',
    href: 'git+https://github.com/aalzehla/capacitor-jailbreak-root-detection.git.git',
    title: 'capacitor-jailbreak-root-detection',
    description: 'Jailbreak Root detection plugin for capacitor.',
    author: 'aalzehla',
  },
  {
    name: 'capacitor-widgetsbridge-plugin',
    href: 'git+https://github.com/0xn33t/capacitor-widgetsbridge-plugin.git.git',
    title: 'capacitor-widgetsbridge-plugin',
    description: 'Capacitor plugin to interact with ios widgetkit',
    author: '0xn33t',
  },
  {
    name: '@bugfender/capacitor',
    href: 'git+https://github.com/bugfender/bugfender-capacitor.git',
    title: 'capacitor',
    description: 'Remote logging with Bugfender',
    author: 'ventayol',
  },
  {
    name: 'capacitor-exit-app-ios',
    href: 'git+https://github.com/tienmanh94hbk/capacitor-exit-app-ios.git',
    title: 'capacitor-exit-app-ios',
    description: 'exit app on ios',
    author: 'dotienmanh',
  },
  { name: '@capgo/ivs-player', href: 'git+https://github.com/Cap-go/ivs-player.git', title: 'ivs-player', description: 'Ivs player for capacitor app', author: 'riderx' },
  {
    name: '@gws20/capacitor-developer-options',
    href: 'git+https://github.com/gws20/capacitor-developer-options.git',
    title: 'capacitor-developer-options',
    description: 'A Capacitor plugin to check if Developer Options are enabled on Android devices.',
    author: 'gwsginanjar',
  },
  { name: 'capacitor-print', href: 'git+https://github.com/leoruhland/capacitor-print.git', title: 'capacitor-print', description: 'Print the webview', author: 'leoruhland' },
  {
    name: 'capacitor-plugin-backgroundservice',
    href: 'git+https://github.com/manpreet-mobicloud/capacitor-plugin-registerBackgroundService.git.git',
    title: 'capacitor-plugin-backgroundservice',
    description: 'Plugin to start application as foreground service to run in background continously even if the app is killed or device is rebooted',
    author: 'pakshal-mobicloud',
  },
  {
    name: '@idpass/hotspot-file-transfer-capacitor',
    href: 'git+https://github.com/jlduragos/hotspot-file-transfer.git',
    title: 'hotspot-file-transfer-capacitor',
    description: 'Capacitor plugin for the SmartScanner Core library to scan MRZ, NFC and barcodes',
    author: 'lemuelduragos',
  },
  {
    name: '@aparajita/capacitor-logger',
    href: 'git+https://github.com/aparajita/capacitor-logger.git',
    title: 'capacitor-logger',
    description: 'Enhanced, universal logging for Capacitor apps and plugins',
    author: 'ckgaparajita',
  },
  {
    name: 'capacitor-open-app-settings',
    href: 'git+https://github.com/swernimo/capacitor-open-app-settings.git',
    title: 'capacitor-open-app-settings',
    description: "A simple plugin that opens the app's settings page (if it exists)",
    author: 'swernimont',
  },
  {
    name: '@sencrop/capacitor-intercom',
    href: 'git+https://github.com/sencrop/capacitor-intercom.git',
    title: 'capacitor-intercom',
    description: 'Intercom Plugin for Capacitor',
    author: 'jeromesencrop',
  },
  {
    name: 'capacitor-moengage-core',
    href: 'git+https://github.com/moengage/Capacitor-SDK.git.git',
    title: 'capacitor-moengage-core',
    description: 'MoEngage is a mobile marketing automation company. This capacitor SDK helps you track events, trigger smart notifications.',
    author: 'moengagecordava',
  },
  {
    name: 'capacitor-plugin-octopulse',
    href: 'git+https://github.com/Octolytics-SDK/octopulse-ionic-plugin.git',
    title: 'capacitor-plugin-octopulse',
    description: 'Plugin for use Smart Agent SDK',
    author: 'yornelalcancia',
  },
  {
    name: '@hotend/capacitor-file-picker',
    href: 'git+https://github.com/rbreckner/capawesome-capacitor-plugins.git',
    title: 'capacitor-file-picker',
    description: 'Capacitor plugin that allows the user to select a file.',
    author: 'pommes',
  },
  {
    name: '@juannpz/inappbrowser',
    href: 'git+https://github.com/Cap-go/capacitor-inappbrowser.git',
    title: 'inappbrowser',
    description: 'Capacitor plugin in app browser',
    author: 'juannpz',
  },
  {
    name: 'indigitall-capacitor-plugin',
    href: 'git+https://gclarfer@bitbucket.org/indigitallfuente/capacitor-sdk.git.git',
    title: 'indigitall-capacitor-plugin',
    description: 'Capacitor Indigitall Plugin',
    author: 'sdkindigitall',
  },
  {
    name: 'capacitor-ionic-plugin-amap',
    href: 'git+https://github.com/PelnHigh/capacitor-ionic-plugin-amap.git',
    title: 'capacitor-ionic-plugin-amap',
    description: 'Amap Capacitor',
    author: 'tompeng',
  },
  {
    name: 'capacitor-facebook-events',
    href: 'git+https://github.com/Linknpay/capacitor-facebook-events.git',
    title: 'capacitor-facebook-events',
    description: 'Facebook events tracking in Capacitor applications',
    author: 'gketata',
  },
  {
    name: '@codoffer/capacitor-healthkit',
    href: 'git+https://github.com/codoffer-infotech/capacitor-healthkit.git',
    title: 'capacitor-healthkit',
    description: 'Capacitor plugin to read data from and write data to Apple Health',
    author: 'codoffer',
  },
  {
    name: '@capacitor-mlkit/translation',
    href: 'git+https://github.com/capawesome-team/capacitor-mlkit.git',
    title: 'translation',
    description: 'Capacitor plugin for ML Kit Translation.',
    author: 'robingenz',
  },
  {
    name: '@felix-health/capacitor-segment',
    href: 'git+https://github.com/FelixHealth/capacitor-segment.git',
    title: 'capacitor-segment',
    description: 'Capacitor plugin for Segment analytics',
    author: 'felix-eddiemachete',
  },
  {
    name: '@micahlt/capacitor-dark-mode',
    href: 'git+https://github.com/hinddeep/ionicCapacitorDarkMode.git',
    title: 'capacitor-dark-mode',
    description: 'Handle dark mode changes on android and iOS',
    author: 'micahlt',
  },
  {
    name: 'capacitor-plugin-dynamsoft-barcode-reader',
    href: 'git+https://github.com/tony-xlh/capacitor-plugin-dynamsoft-barcode-reader.git',
    title: 'capacitor-plugin-dynamsoft-barcode-reader',
    description: 'A capacitor plugin for Dynamsoft Barcode Reader',
    author: 'xulihang',
  },
  {
    name: '@albgen/capacitor-zpl-plugin',
    href: 'git+https://github.com/albgen/capacitor-zpl-plugin.git.git',
    title: 'capacitor-zpl-plugin',
    description: 'A plugin which facilitate the communication with ZPL Printers.',
    author: 'albgen',
  },
  {
    name: '@droponio/capacitor-barcode-scanner-fragment',
    href: 'git+https://github.com/dropon/capacitor-barcode-scanner-fragment.git',
    title: 'capacitor-barcode-scanner-fragment',
    description: 'BarcodeScanner in Fragment',
    author: 'dropon',
  },
  {
    name: '@palauaandsons/capacitor-sharing',
    href: 'git+https://github.com/palauaandsons/capacitor-sharing.git',
    title: 'capacitor-sharing',
    description: 'Sharing plugin for Capacitor',
    author: 'javiermartinz',
  },
  {
    name: 'capacitor-cidprint',
    href: 'git+https://github.com/P4IT/capacitor-plugin-cidprint.git',
    title: 'capacitor-cidprint',
    description: 'CaptureID Printer Plugin',
    author: 'u-hoppe',
  },
  {
    name: '@pantrist/capacitor-date-picker',
    href: 'git+https://github.com/Pantrist-dev/capacitor-date-picker.git',
    title: 'capacitor-date-picker',
    description: 'Native DateTime Picker Plugin for Capacitor Apps',
    author: 'nico.lueg',
  },
  {
    name: 'capacitor-community-contacts',
    href: 'git+https://github.com/capacitor-community/contacts.git',
    title: 'capacitor-community-contacts',
    description: 'Contacts Plugin for Capacitor',
    author: 'denis_galkin',
  },
  {
    name: '@givenergy/barcode-scanning',
    href: 'git+https://github.com/capawesome-team/capacitor-mlkit.git',
    title: 'barcode-scanning',
    description: 'Capacitor plugin for ML Kit Barcode Scanning.',
    author: 'givenergy-jamiem',
  },
  {
    name: 'capacitor-dark-mode',
    href: 'git+https://github.com/hinddeep/ionicCapacitorDarkMode.git',
    title: 'capacitor-dark-mode',
    description: 'Handle dark mode changes on android and iOS',
    author: 'hinddeep',
  },
  {
    name: 'fiuuxdk-capacitor-plugin',
    href: 'git+https://github.com/nikfaris88/fiuu_capacitor_plugin.git',
    title: 'fiuuxdk-capacitor-plugin',
    description: 'Capacitor plugin to use Fiuu XDK',
    author: 'molpay',
  },
  {
    name: 'adjust-capacitor-plugin',
    href: 'git+https://github.com/fieprmxxwx83/adjust-capacitor-plugin.git',
    title: 'adjust-capacitor-plugin',
    description: 'Adjust SDK plugin for Capacitor',
    author: 'fieprmxxwx83',
  },
  {
    name: '@spryrocks/capacitor-socket-connection-plugin',
    href: 'git+https://github.com/SpryRocks/capacitor-socket-connection-plugin.git',
    title: 'capacitor-socket-connection-plugin',
    description: 'Capacitor Socket Connection Plugin',
    author: 'maxim.zhemerenko',
  },
  {
    name: '@capacitor-mlkit/selfie-segmentation',
    href: 'git+https://github.com/capawesome-team/capacitor-mlkit.git',
    title: 'selfie-segmentation',
    description: 'Capacitor plugin for ML Kit Selfie Segmentation.',
    author: 'robingenz',
  },
  {
    name: '@capacitor/watch',
    href: 'git+https://github.com/ionic-team/CapacitorWatch.git',
    title: 'watch',
    description: 'Provide Watch interfaces and communication',
    author: 'itschaced',
  },
  {
    name: '@cotecna/camera-preview',
    href: 'git+https://github.com/Cotecna-Inspection/camera-preview.git',
    title: 'camera-preview',
    description: 'Camera preview',
    author: 'cotecna-itpi-admin',
  },
  {
    name: 'capacitor-plugin-scgssigninwithgoogle',
    href: 'git+https://github.com/scgscorp/capacitor-plugin-scgssigninwithgoogle.git',
    title: 'capacitor-plugin-scgssigninwithgoogle',
    description: 'capacitor signinwithgoogle using supabase',
    author: 'scgscorp',
  },
  {
    name: 'capacitor-ssl-pinning',
    href: 'git+https://github.com/mchl18/Capacitor-SSL-Pinning.git',
    title: 'capacitor-ssl-pinning',
    description: 'Check/pin SSL certificates',
    author: 'morefox',
  },
  {
    name: 'capacitor-plugin-filesharer',
    href: 'git+https://github.com/mpat8121/capacitor-plugin-filesharer.git.git',
    title: 'capacitor-plugin-filesharer',
    description: 'Capacitor plugin to allow file sharing on Android and iOS',
    author: 'mpat8121',
  },
  {
    name: '@evehr/capacitor-jailbreak-root-detection',
    href: 'git+https://github.com/evehr-vn/capacitor-jailbreak-root-detection.git.git',
    title: 'capacitor-jailbreak-root-detection',
    description: 'Jailbreak Root detection plugin for capacitor.',
    author: 'hmphu',
  },
  {
    name: 'capacitor-brightcove-player',
    href: 'git+https://github.com/jnesislabs/capacitor-brightcove-player.git',
    title: 'capacitor-brightcove-player',
    description: 'Play video and audio files from Brightcove Video Cloud with offline features',
    author: 'jnesis',
  },
  {
    name: 'capacitor-plugin-speaker-toggle-ios-android',
    href: 'git+https://github.com/javedshahzad/capacitor-speaker-toggle-ios-android.git',
    title: 'capacitor-plugin-speaker-toggle-ios-android',
    description: 'Capacitor plugin  for switching between speaker and earpiece when playing audio.',
    author: 'javed-shahzad',
  },
  {
    name: 'capacitor-clear-cache',
    href: 'git+https://github.com/aeharding/capacitor-clear-cache.git',
    title: 'capacitor-clear-cache',
    description: 'Clear various app caches',
    author: 'aeharding',
  },
  {
    name: 'capacitor-plugin-silent-notifications',
    href: 'git+https://github.com/greenygh0st/capacitor-plugin-silent-notifications.git',
    title: 'capacitor-plugin-silent-notifications',
    description: 'Allows an a Capacitor application to handle iOS remote/silent push notifications',
    author: 'greenygh0st',
  },
  {
    name: '@carviz/capacitor-camera-preview',
    href: 'git+https://github.com/GetCarviz/capacitor-camera-preview.git',
    title: 'capacitor-camera-preview',
    description: 'Fork of the capacitor-community/camera-preview plugin focusing on high resolution photos without bloating up the code.',
    author: 'evanlegamer',
  },
  {
    name: '@slothfi/capacitor-social-login',
    href: 'git+https://github.com/Slothfi/capacitor-social-login.git',
    title: 'capacitor-social-login',
    description: 'All social logins in one plugin',
    author: '0xghosty',
  },
  {
    name: '@mindly/capacitor-android-edge-to-edge-support',
    href: 'git+https://github.com/mindly-space/capacitor-android-edge-to-edge-support.git',
    title: 'capacitor-android-edge-to-edge-support',
    description: 'Capacitor plugin to support edge-to-edge display on Android.',
    author: 'dimitri320',
  },
  {
    name: 'capacitor-geofence-box-tracker',
    href: 'git+https://github.com/jaimbox/capacitor-geofence-box-tracker.git',
    title: 'capacitor-geofence-box-tracker',
    description: 'Capacitor Geofence Tracker',
    author: 'jaimbox',
  },
  {
    name: '@felix-health/inappbrowser',
    href: 'git+https://github.com/Felix-Health/capacitor-inappbrowser.git',
    title: 'inappbrowser',
    description: 'Capacitor plugin in app browser | Felix Health fork',
    author: 'felix-eddiemachete',
  },
  {
    name: '@squareetlabs/capacitor-navigation-bar',
    href: 'git+https://jacobo-squareet@bitbucket.org/squareetlabs/capacitor-navigation-bar.git',
    title: 'capacitor-navigation-bar',
    description: 'This Capacitor Plugin allows control of the navigation bar on Android devices.',
    author: 'squareetlabs',
  },
  {
    name: 'capacitor2-zoom-plugin',
    href: 'git+https://github.com/prakashvadrevu/capacitor2-zoom-plugin.git',
    title: 'capacitor2-zoom-plugin',
    description: 'Zoom plugin for Capacitor2',
    author: 'bharatak',
  },
  {
    name: '@jonz94/capacitor-azure-notification-hubs',
    href: 'git+https://github.com/jonz94/capacitor-azure-notification-hubs.git',
    title: 'capacitor-azure-notification-hubs',
    description: 'Capacitor plugin to register push notifications via Azure Notification Hub.',
    author: 'jonz94',
  },
  {
    name: 'callkit-voip-capacitor-plugin',
    href: 'git+https://github.com/Abhiranjanchaurasia/callkit-voip-capacitor-plugin.git',
    title: 'callkit-voip-capacitor-plugin',
    description: 'Provide CallKit and PushKit functionality to capacitor on iOS & android',
    author: 'abhiranjanchaurasia',
  },
  {
    name: 'capacitor-share-safari',
    href: 'git+https://github.com/aeharding/capacitor-share-safari.git',
    title: 'capacitor-share-safari',
    description: 'Capacitor share, iOS only, with open in safari option',
    author: 'aeharding',
  },
  {
    name: '@hiloenergie/capacitor-plugin-safe-area',
    href: 'https://dev.azure.com/HQCdevops/HQC/_git/capacitor-community-safe-area',
    title: 'capacitor-plugin-safe-area',
    description: 'A plugin to expose the safe area insets from the native iOS/Android device to your web project.',
    author: 'jbouchard_hiloenergie',
  },
  {
    name: '@blue-performance/capacitor-contact-sync',
    href: 'git+https://github.com/BluePerformance/capacitor-contact-sync.git',
    title: 'capacitor-contact-sync',
    description: 'Contacts Plugin for Capacitor',
    author: 'marco-hochmuth',
  },
  {
    name: '@capacitor-mlkit/face-detection',
    href: 'git+https://github.com/capawesome-team/capacitor-mlkit.git',
    title: 'face-detection',
    description: 'Capacitor plugin for ML Kit Face Detection.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-autostartmanager',
    href: 'git+https://github.com/asephermann/capacitor-autostartmanager.git',
    title: 'capacitor-autostartmanager',
    description: 'Auto Start Manager, Check Automatic Date Time Zone, Check Camera',
    author: 'asephermann',
  },
  {
    name: '@whiteguru/capacitor-plugin-media-capture',
    href: 'git+https://github.com/dragermrb/capacitor-plugin-media-capture.git',
    title: 'capacitor-plugin-media-capture',
    description: 'Capacitor plugin to capture video',
    author: 'dragermrb',
  },
  {
    name: 'capacitor-healthkit',
    href: 'git+https://github.com/Ad-Scientiam/capacitor-healthkit.git',
    title: 'capacitor-healthkit',
    description: 'Capacitor plugin to retrieve data from Healthkit',
    author: 'mahnuh',
  },
  {
    name: '@swernimont/capacitor-jailbreak-root-detection',
    href: 'git+https://github.com/swernimo/capacitor-jailbreak-root-detection.git',
    title: 'capacitor-jailbreak-root-detection',
    description: 'Jailbreak Root detection plugin for capacitor.',
    author: 'swernimont',
  },
  {
    name: '@aalzehla/capacitor-secure-storage-plugin',
    href: 'git+https://github.com/aalzehla/capacitor-secure-storage-plugin.git',
    title: 'capacitor-secure-storage-plugin',
    description: 'Securely store secrets such as usernames, passwords, tokens, certificates or other sensitive information (strings) on iOS & Android',
    author: 'aalzehla',
  },
  {
    name: '@captureid/capacitor-cidprint',
    href: 'git+https://github.com/P4IT/capacitor-plugin-cidprint.git',
    title: 'capacitor-cidprint',
    description: 'CaptureID Printer Plugin',
    author: 'u-hoppe',
  },
  {
    name: '@capgo/native-purchases',
    href: 'git+https://github.com/Cap-go/native-purchases.git',
    title: 'native-purchases',
    description: 'In-app Subscriptions Made Easy',
    author: 'riderx',
  },
  {
    name: 'capacitor-reader',
    href: 'git+https://github.com/aeharding/capacitor-reader.git',
    title: 'capacitor-reader',
    description: 'Opens a simplified in app browser, prioritizing readability',
    author: 'aeharding',
  },
  {
    name: 'capacitor-health-connect',
    href: 'git+https://github.com/ubie-oss/capacitor-health-connect.git',
    title: 'capacitor-health-connect',
    description: 'Android Health Connect integration for Capacitor',
    author: 'monchi',
  },
]
