export interface Action {
  icon?: any
  href: string
  title: string
  name?: string
  author: string
  description: string
  iconForeground?: string
  iconBackground?: string
}
export interface Plugin extends Action {
  npmDownloads?: number
  githubStars?: number
  readme?: string
  datePublished?: string
  dateModified?: string
  tutorial?: string
}
export const actions = [
  {
    name: 'capacitor-native-http',
    href: 'git+https://github.com/viniciusgandrade/capacitor-native-http.git',
    title: 'capacitor-native-http',
    description: 'Plugin capacitor para requisições nativas',
    author: 'viniciusgandrade1',
  },
  {
    name: 'capacitor-secure-storage-plugin',
    href: 'git+https://github.com/martinkasa/capacitor-secure-storage-plugin.git',
    title: 'capacitor-secure-storage-plugin',
    description: 'Securely store secrets such as usernames, passwords, tokens, certificates or other sensitive information (strings) on iOS & Android',
    author: 'martinkasa',
  },
  {
    name: '@capacitor-community/file-opener',
    href: 'git+https://github.com/capacitor-community/file-opener.git',
    title: 'file-opener',
    description: 'Capacitor File Opener. The plugin is able to open a file given the mimeType and the file uri.',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-plugin-safe-area',
    href: 'git+https://github.com/AlwaysLoveme/capacitor-plugin-safe-area.git.git',
    title: 'capacitor-plugin-safe-area',
    description: 'a capacitor plugin to get SafeArea info on Android and IOS',
    author: 'zhuxian',
  },
  {
    name: 'appsflyer-capacitor-plugin',
    href: 'git+https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin.git',
    title: 'appsflyer-capacitor-plugin',
    description: 'AppsFlyer SDK plugin for Capacitor',
    author: 'amit-kremer93',
  },
  {
    name: '@capacitor-community/firebase-analytics',
    href: 'git+https://github.com/capacitor-community/firebase-analytics.git',
    title: 'firebase-analytics',
    description: 'A native plugin for firebase analytics.',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-native-settings',
    href: 'git+https://github.com/RaphaelWoude/capacitor-native-settings.git',
    title: 'capacitor-native-settings',
    description: 'Capacitor plugin to open native settings screens for android and iOS',
    author: 'dennisameling',
  },
  {
    name: 'capacitor-plugin-app-tracking-transparency',
    href: 'git+https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency.git',
    title: 'capacitor-plugin-app-tracking-transparency',
    description: 'Capacitor plugin to request user authorization to access app-related data for tracking the user or the device.',
    author: 'mahnuh',
  },
  {
    name: '@bistroo/vite-plugin-capacitor',
    href: 'git+https://github.com/bistroo/vite-plugin-capacitor.git',
    title: 'vite-plugin-capacitor',
    description: 'Vite plugin for capacitor',
    author: 'bistroo-dev',
  },
  {
    name: '@capawesome/capacitor-app-update',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-app-update',
    description: 'Capacitor plugin that assists with app updates.',
    author: 'robingenz',
  },
  {
    name: '@capacitor/preferences',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'preferences',
    description: 'The Preferences API provides a simple key/value persistent store for lightweight data.',
    author: 'itschaced',
  },
  {
    name: '@newrelic/newrelic-capacitor-plugin',
    href: 'git+https://github.com/newrelic/newrelic-capacitor-plugin.git',
    title: 'newrelic-capacitor-plugin',
    description: 'NewRelic Plugin for ionic Capacitor',
    author: 'newrelic',
  },
  {
    name: '@codetrix-studio/capacitor-google-auth',
    href: 'git+https://github.com/CodetrixStudio/CapacitorGoogleAuth.git',
    title: 'capacitor-google-auth',
    description: 'Google Auth plugin for capacitor.',
    author: 'parveenkhtkr',
  },
  {
    name: '@capacitor-community/media',
    href: 'git+https://github.com/capacitor-community/media.git',
    title: 'media',
    description: 'Capacitor plugin for saving and retrieving photos and videos, and managing photo albums.',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/in-app-review',
    href: 'git+https://github.com/capacitor-community/in-app-review.git',
    title: 'in-app-review',
    description: 'Lets you prompt users to submit app store ratings and reviews without leaving your app - using platform native dialogs.',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-firebase/crashlytics',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'crashlytics',
    description: 'Capacitor plugin for Firebase Crashlytics.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/sqlite',
    href: 'git+https://github.com/capacitor-community/sqlite.git',
    title: 'sqlite',
    description: 'Community plugin for native & electron SQLite databases',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/device',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'device',
    description: 'The Device API exposes internal information about the device, such as the model and operating system version, along with user information such as unique ids.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-mlkit/barcode-scanning',
    href: 'git+https://github.com/capawesome-team/capacitor-mlkit.git',
    title: 'barcode-scanning',
    description: 'Capacitor plugin for ML Kit Barcode Scanning.',
    author: 'robingenz',
  },
  {
    name: '@capgo/capacitor-social-login',
    href: 'git+https://github.com/Cap-go/capacitor-social-login.git',
    title: 'capacitor-social-login',
    description: 'All social logins in one plugin',
    author: 'riderx',
  },
  {
    name: '@capacitor-firebase/analytics',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'analytics',
    description: 'Capacitor plugin for Firebase Analytics.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/intercom',
    href: 'git+https://github.com/capacitor-community/intercom.git',
    title: 'intercom',
    description: 'Enable Intercom features for Capacitor apps',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/privacy-screen',
    href: 'git+https://github.com/capacitor-community/privacy-screen.git',
    title: 'privacy-screen',
    description: 'Capacitor plugin that protects your app from displaying a screenshot in Recents screen/App Switcher.',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/camera-preview',
    href: 'git+https://github.com/capacitor-community/camera-preview.git',
    title: 'camera-preview',
    description: 'Camera preview',
    author: 'jcesarmobile',
  },
  {
    name: '@capawesome/capacitor-file-picker',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-file-picker',
    description: 'Capacitor plugin that allows the user to select a file.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-firebase/remote-config',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'remote-config',
    description: 'Capacitor plugin for Firebase Remote Config.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-firebase/authentication',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'authentication',
    description: 'Capacitor plugin for Firebase Authentication.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/http',
    href: 'git+https://github.com/capacitor-community/http.git',
    title: 'http',
    description: 'A native HTTP plugin for CORS-free requests and file transfers',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/contacts',
    href: 'git+https://github.com/capacitor-community/contacts.git',
    title: 'contacts',
    description: 'Contacts Plugin for Capacitor',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/app',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'app',
    description:
      'The App API handles high level App state and events.For example, this API emits events when the app enters and leaves the foreground, handles deeplinks, opens other apps, and manages persisted plugin state.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-community/fcm',
    href: 'git+https://github.com/capacitor-community/fcm.git',
    title: 'fcm',
    description: 'Enable Firebase Cloud Messaging features for Capacitor apps',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/screen-brightness',
    href: 'git+https://github.com/capacitor-community/screen-brightness.git',
    title: 'screen-brightness',
    description: 'control screen brightness on ios and android',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/filesystem',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'filesystem',
    description: 'The Filesystem API provides a NodeJS-like API for working with files on the device.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-firebase/app',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'app',
    description: 'Capacitor plugin for Firebase App.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/keep-awake',
    href: 'git+https://github.com/capacitor-community/keep-awake.git',
    title: 'keep-awake',
    description: 'Prevent your screen from getting some sleep!',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/speech-recognition',
    href: 'git+https://github.com/capacitor-community/speech-recognition.git',
    title: 'speech-recognition',
    description: 'A native plugin for speech recognition',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/bluetooth-le',
    href: 'git+https://github.com/capacitor-community/bluetooth-le.git',
    title: 'bluetooth-le',
    description: 'Capacitor plugin for Bluetooth Low Energy ',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-firebase/messaging',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'messaging',
    description: 'Capacitor plugin for Firebase Cloud Messaging (FCM).',
    author: 'robingenz',
  },
  {
    name: '@transistorsoft/capacitor-background-fetch',
    href: 'git+https://github.com/transistorsoft/capacitor-background-fetch.git',
    title: 'capacitor-background-fetch',
    description: 'Periodic callbacks in the background for both IOS and Android',
    author: 'transistorsoft-admin',
  },
  {
    name: '@capacitor-community/native-audio',
    href: 'git+https://github.com/capacitor-community/native-audio.git',
    title: 'native-audio',
    description: 'A native plugin for native audio engine',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/apple-sign-in',
    href: 'git+https://github.com/capacitor-community/apple-sign-in.git',
    title: 'apple-sign-in',
    description: 'Capacitor Sign in with Apple',
    author: 'jcesarmobile',
  },
  {
    name: '@capgo/capacitor-native-biometric',
    href: 'git+https://github.com/Cap-go/capacitor-native-biometric.git',
    title: 'capacitor-native-biometric',
    description: 'This plugin gives access to the native biometric apis for android and iOS',
    author: 'riderx',
  },
  {
    name: '@capgo/inappbrowser',
    href: 'git+https://github.com/Cap-go/capacitor-inappbrowser.git',
    title: 'inappbrowser',
    description: 'Capacitor plugin in app browser',
    author: 'riderx',
  },
  {
    name: '@aparajita/capacitor-biometric-auth',
    href: 'git+https://github.com/aparajita/capacitor-biometric-auth.git',
    title: 'capacitor-biometric-auth',
    description: 'Provides access to the native biometric auth & device security APIs for Capacitor apps',
    author: 'ckgaparajita',
  },
  {
    name: '@aparajita/capacitor-secure-storage',
    href: 'git+https://github.com/aparajita/capacitor-secure-storage.git',
    title: 'capacitor-secure-storage',
    description: 'Capacitor 5+ plugin that provides secure storage for the iOS and Android',
    author: 'ckgaparajita',
  },
  {
    name: '@capacitor/browser',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'browser',
    description: 'The Browser API provides the ability to open an in-app browser and subscribe to browser events.',
    author: 'itschaced',
  },
  {
    name: '@transistorsoft/capacitor-background-geolocation',
    href: 'git+https://github.com/transistorsoft/capacitor-background-geolocation.git',
    title: 'capacitor-background-geolocation',
    description: 'The most sophisticated cross platform Capacitor background location tracking & geofencing module with battery-conscious motion-detection intelligence',
    author: 'transistorsoft-admin',
  },
  {
    name: '@capacitor/status-bar',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'status-bar',
    description: 'The StatusBar API Provides methods for configuring the style of the Status Bar, along with showing or hiding it.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-community/facebook-login',
    href: 'git+ssh://git@github.com/capacitor-community/facebook-login.git',
    title: 'facebook-login',
    description: 'A native plugin for Facebook Login',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-voice-recorder',
    href: 'git+https://github.com/tchvu3/capacitor-voice-recorder.git',
    title: 'capacitor-voice-recorder',
    description: 'Capacitor plugin for voice recording',
    author: 'tchvu3',
  },
  {
    name: '@capawesome/capacitor-badge',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-badge',
    description: 'Capacitor plugin to access and update the badge number of the app icon.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/native-market',
    href: 'git+https://github.com/capacitor-community/native-market.git',
    title: 'native-market',
    description: 'A native market plugin for linking to google play or app store.',
    author: 'jcesarmobile',
  },
  {
    name: '@sentry/capacitor',
    href: 'git+https://github.com/getsentry/sentry-capacitor.git',
    title: 'capacitor',
    description: 'Official Sentry SDK for Capacitor',
    author: 'billyvg',
  },
  {
    name: '@capawesome/capacitor-screen-orientation',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-screen-orientation',
    description: 'Capacitor plugin to lock/unlock the screen orientation.',
    author: 'robingenz',
  },
  {
    name: '@capgo/capacitor-updater',
    href: 'git+https://github.com/Cap-go/capacitor-updater.git',
    title: 'capacitor-updater',
    description: 'Live update for capacitor apps',
    author: 'riderx',
  },
  {
    name: '@capacitor-community/safe-area',
    href: 'git+https://github.com/capacitor-community/safe-area.git',
    title: 'safe-area',
    description: 'Capacitor Plugin that exposes the safe area insets from the native iOS/Android device to your web project.',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/geolocation',
    href: 'git+https://github.com/ionic-team/capacitor-geolocation.git',
    title: 'geolocation',
    description:
      'The Geolocation API provides simple methods for getting and tracking the current position of the device using GPS, along with altitude, heading, and speed information if available.',
    author: 'itschaced',
  },
  {
    name: '@capawesome/capacitor-background-task',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-background-task',
    description: 'Capacitor plugin for running background tasks.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-file-chunk',
    href: 'git+https://github.com/qrclip/capacitor-file-chunk.git',
    title: 'capacitor-file-chunk',
    description: 'Capacitor plugin to read and write files in chunks using a local server and without using capacitor bridge.',
    author: 'qrclip',
  },
  {
    name: '@capacitor-firebase/performance',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'performance',
    description: 'Capacitor plugin for Firebase Performance Monitoring.',
    author: 'robingenz',
  },
  {
    name: '@jcesarmobile/ssl-skip',
    href: 'git+https://github.com/jcesarmobile/ssl-skip.git',
    title: 'ssl-skip',
    description: 'Capacitor plugin for skipping ssl checks',
    author: 'jcesarmobile',
  },
  {
    name: '@bcyesil/capacitor-plugin-printer',
    href: 'git+https://github.com/BarisCanYesil/capacitor-plugin-printer.git',
    title: 'capacitor-plugin-printer',
    description: 'Capacitor plugin for printing HTML format value iOS/Android apps.',
    author: 'bariscanyesil',
  },
  {
    name: 'pinia-plugin-capacitor-persist',
    href: 'git+https://github.com/craigrileyuk/pinia-plugin-capacitor-persist.git',
    title: 'pinia-plugin-capacitor-persist',
    description: 'A Vue 3 Pinia plugin which persists store content using the CapacitorJS Preferences store.',
    author: 'craigrileyuk',
  },
  {
    name: '@capawesome-team/capacitor-file-opener',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-file-opener',
    description: 'Capacitor plugin to open a file with the default application.',
    author: 'robingenz',
  },
  {
    name: '@ebarooni/capacitor-calendar',
    href: 'git+https://github.com/ebarooni/capacitor-calendar.git',
    title: 'capacitor-calendar',
    description: 'A capacitor plugin for managing calendar events on iOS and Android, with reminders support on iOS.',
    author: 'ebarooni',
  },
  {
    name: '@capacitor/barcode-scanner',
    href: 'git+github.com/ionic-team/capacitor-barcode-scanner.git',
    title: 'barcode-scanner',
    description: 'Capacitor plugin using Outsystems Barcode libs',
    author: 'itschaced',
  },
  {
    name: '@capacitor/splash-screen',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'splash-screen',
    description: 'The Splash Screen API provides methods for showing or hiding a Splash image.',
    author: 'itschaced',
  },
  {
    name: '@ua/capacitor-airship',
    href: 'git+https://github.com/urbanairship/capacitor-airship.git',
    title: 'capacitor-airship',
    description: 'Airship capacitor plugin',
    author: 'urbanairship',
  },
  {
    name: '@capacitor/camera',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'camera',
    description: 'The Camera API provides the ability to take a photo with the camera or choose an existing one from the photo album.',
    author: 'itschaced',
  },
  {
    name: 'capacitor-rate-app',
    href: 'git+https://github.com/Nodonisko/capacitor-rate-app.git',
    title: 'capacitor-rate-app',
    description: 'Let users rate your app using native rate app dialog for both Android and iOS.',
    author: 'nodon',
  },
  {
    name: '@capacitor-community/app-icon',
    href: 'git+https://github.com/capacitor-community/app-icon.git',
    title: 'app-icon',
    description: 'Capacitor community plugin for changing an iOS app icon.',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-jitsi-meet',
    href: 'git+https://github.com/calvinckho/capacitor-jitsi-meet.git',
    title: 'capacitor-jitsi-meet',
    description: 'This Ionic Capacitor plugin is created to make video calls through the free, open-sourced Jitsi video platform (https://meet.jit.si) on iOS and Android.',
    author: 'calvinckho',
  },
  {
    name: '@capacitor-community/text-to-speech',
    href: 'git+https://github.com/capacitor-community/text-to-speech.git',
    title: 'text-to-speech',
    description: 'Capacitor plugin for synthesizing speech from text.',
    author: 'jcesarmobile',
  },
  {
    name: '@capgo/native-audio',
    href: 'git+https://github.com/Cap-go/capacitor-native-audio.git',
    title: 'native-audio',
    description: 'A native plugin for native audio engine',
    author: 'riderx',
  },
  {
    name: '@capawesome-team/capacitor-android-battery-optimization',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-android-battery-optimization',
    description: 'Capacitor plugin to access battery optimization settings on Android.',
    author: 'robingenz',
  },
  {
    name: '@capacitor/screen-orientation',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'screen-orientation',
    description: 'The Screen Orientation API provides methods to lock and unlock the screen orientation.',
    author: 'itschaced',
  },
  {
    name: '@capacitor/keyboard',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'keyboard',
    description: 'The Keyboard API provides keyboard display and visibility control, along with event tracking when the keyboard shows and hides.',
    author: 'itschaced',
  },
  {
    name: 'capacitor-swipe-back-plugin',
    href: 'git+https://github.com/alesmraz/capacitor-plugin-swipe-back.git',
    title: 'capacitor-swipe-back-plugin',
    description:
      'Capacitor swipe back plugin. For Capacitor v3, v4 (0.0.3) and v5 (1.0.0+). For v2 use original plugin: https://github.com/diiiary/capacitor-plugin-ios-swipe-back',
    author: 'alesmraz',
  },
  {
    name: 'capacitor-email-composer',
    href: 'git+https://github.com/EinfachHans/capacitor-email-composer.git',
    title: 'capacitor-email-composer',
    description: 'E-Mail Composer Plugin for Capacitor',
    author: 'hanskrywaa',
  },
  {
    name: '@capacitor/text-zoom',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'text-zoom',
    description: 'The Text Zoom API provides the ability to change Web View text size for visual accessibility.',
    author: 'itschaced',
  },
  {
    name: '@hugotomazi/capacitor-navigation-bar',
    href: 'git+https://github.com/hugotomazi/navigation-bar.git',
    title: 'capacitor-navigation-bar',
    description: 'Capacitor Plugin for Navigation Bar',
    author: 'hugotomazi',
  },
  {
    name: 'capacitor-radar',
    href: 'git+https://github.com/radarlabs/capacitor-radar.git',
    title: 'capacitor-radar',
    description: 'Capacitor plugin for Radar, the leading geofencing and location tracking platform',
    author: 'nickpatrick-radar',
  },
  {
    name: '@recognizebv/capacitor-plugin-msauth',
    href: 'git+https://github.com/recognizegroup/capacitor-plugin-msauth.git',
    title: 'capacitor-plugin-msauth',
    description: 'This plugin enables MSAL support for Capacitor.',
    author: 'johankamp',
  },
  {
    name: '@capacitor/share',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'share',
    description: 'The Share API provides methods for sharing content in any sharing-enabled apps the user may have installed.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-community/firebase-crashlytics',
    href: 'git+https://github.com/capacitor-community/firebase-crashlytics.git',
    title: 'firebase-crashlytics',
    description: 'Capacitor plugin for Firebase Crashlytics.',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/inappbrowser',
    href: 'git+https://github.com/ionic-team/capacitor-os-inappbrowser.git',
    title: 'inappbrowser',
    description:
      "The InAppBrowser Plugin provides a web browser view that allows you to load any web page externally. It behaves as a standard web browser and is useful to load untrusted content without risking your application's security. It offers three different ways t",
    author: 'itschaced',
  },
  {
    name: 'capacitor-video-player',
    href: 'git+https://github.com/harmonwood/capacitor-video-player.git',
    title: 'capacitor-video-player',
    description: 'custom Native Capacitor plugin to play a video',
    author: 'jeepq',
  },
  {
    name: '@capacitor/haptics',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'haptics',
    description: 'The Haptics API provides physical feedback to the user through touch or vibration.',
    author: 'itschaced',
  },
  {
    name: '@capacitor/action-sheet',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'action-sheet',
    description: 'The Action Sheet API provides access to native Action Sheets, which come up from the bottom of the screen and display actions a user can take.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-community/barcode-scanner',
    href: 'git+https://github.com/capacitor-community/barcode-scanner.git',
    title: 'barcode-scanner',
    description: 'A fast and efficient (QR) barcode scanner for Capacitor',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/live-updates',
    href: 'git+https://github.com/ionic-team/capacitor-live-updates-plugin.git',
    title: 'live-updates',
    description: 'Official Live Updates plugin for Capacitor',
    author: 'itschaced',
  },
  {
    name: '@capawesome/capacitor-android-edge-to-edge-support',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-android-edge-to-edge-support',
    description: 'Capacitor plugin to support edge-to-edge display on Android.',
    author: 'robingenz',
  },
  {
    name: '@capgo/capacitor-mute',
    href: 'git+https://github.com/Cap-go/capacitor-mute.git',
    title: 'capacitor-mute',
    description: 'Detect if the mute switch is enabled/disabled on a device',
    author: 'riderx',
  },
  {
    name: 'capacitor-ios-autofill-save-password',
    href: 'git+https://github.com/cuongpl/capacitor-ios-autofill-save-password.git',
    title: 'capacitor-ios-autofill-save-password',
    description: 'Prompt to display dialog for saving password to keychain for iOS webview app.',
    author: 'cuongpl',
  },
  {
    name: '@capacitor/network',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'network',
    description: 'The Network API provides network and connectivity information.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-firebase/firestore',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'firestore',
    description: 'Capacitor plugin for Firebase Cloud Firestore.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-appmetrica-plugin',
    href: 'git+https://github.com/virusv/capacitor-appmetrica-plugin.git',
    title: 'capacitor-appmetrica-plugin',
    description: 'Yandex App metrica plugin for Capacitor',
    author: 'virusv',
  },
  {
    name: '@appcues/capacitor',
    href: 'git+https://github.com/appcues/appcues-capacitor-plugin.git',
    title: 'capacitor',
    description: 'Capcitor plugin to bridge the native Android and iOS Appcues mobile SDKs in an Ionic application.',
    author: 'stephano_appcues',
  },
  {
    name: '@cwoebker/capacitor-start-navigation',
    href: 'git+https://github.com/cwoebker/capacitor-start-navigation.git',
    title: 'capacitor-start-navigation',
    description: 'Starts navigation in the native maps application',
    author: 'cwoebker',
  },
  {
    name: '@aparajita/capacitor-dark-mode',
    href: 'git+https://github.com/aparajita/capacitor-dark-mode.git',
    title: 'capacitor-dark-mode',
    description: 'Universal dark mode support for Ionic web and native apps',
    author: 'ckgaparajita',
  },
  {
    name: 'capacitor-plugin-audiosession-bluetooth',
    href: 'git+https://github.com/Jun-Murakami/capacitor-plugin-audiosession-bluetooth.git',
    title: 'capacitor-plugin-audiosession-bluetooth',
    description:
      'This capacitor plugin allows iOS applications to get notified audio about interrupts & route changes (for example when a headset is connected), and also query and override the audio device in use.',
    author: 'jun-murakami',
  },
  {
    name: 'capacitor-blob-writer',
    href: 'git+https://github.com/diachedelic/capacitor-blob-writer.git',
    title: 'capacitor-blob-writer',
    description: 'Write javascript Blobs to the filesystem efficiently',
    author: 'diachedelic',
  },
  {
    name: '@capacitor-community/admob',
    href: 'git+ssh://git@github.com/capacitor-community/admob.git',
    title: 'admob',
    description: 'A native plugin for AdMob',
    author: 'jcesarmobile',
  },
  {
    name: '@capgo/nativegeocoder',
    href: 'git+https://github.com/Cap-go/capacitor-nativegeocoder.git',
    title: 'nativegeocoder',
    description: 'Capacitor plugin for native forward and reverse geocoding',
    author: 'riderx',
  },
  {
    name: '@capawesome/capacitor-live-update',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-live-update',
    description: 'Capacitor plugin to update your app remotely in real-time.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/advertising-id',
    href: 'git+https://github.com/capacitor-community/advertising-id.git',
    title: 'advertising-id',
    description: 'Allows access to the IDFA (iOS) and GAID (Android)',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/toast',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'toast',
    description: 'The Toast API provides a notification pop up for displaying important information to a user. Just like real toast!',
    author: 'itschaced',
  },
  {
    name: 'hypertrack-sdk-ionic-capacitor',
    href: 'git+https://github.com/hypertrack/sdk-ionic-capacitor.git',
    title: 'hypertrack-sdk-ionic-capacitor',
    description: 'Capacitor plugin for HyperTrack generation SDKs',
    author: 'hypertrack',
  },
  { name: '@capgo/camera-preview', href: 'git+https://github.com/Cap-go/camera-preview.git', title: 'camera-preview', description: 'Camera preview', author: 'riderx' },
  {
    name: 'capacitor-native-biometric',
    href: 'git+https://github.com/epicshaggy/capacitor-native-biometric.git',
    title: 'capacitor-native-biometric',
    description: 'This plugin gives access to the native biometric apis for android and iOS',
    author: 'epicshaggy',
  },
  {
    name: '@capacitor-firebase/app-check',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'app-check',
    description: 'Capacitor plugin for Firebase App Check.',
    author: 'robingenz',
  },
  {
    name: '@capacitor/google-maps',
    href: 'git+https://github.com/ionic-team/capacitor-google-maps.git',
    title: 'google-maps',
    description: 'Google maps on Capacitor',
    author: 'itschaced',
  },
  {
    name: '@capawesome/capacitor-managed-configurations',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-managed-configurations',
    description: 'Capacitor plugin to access managed configuration settings.',
    author: 'robingenz',
  },
  { name: 'send-intent', href: 'git+https://github.com/carsten-klaffke/send-intent.git', title: 'send-intent', description: 'SendIntent', author: 'cklaffke' },
  {
    name: '@capacitor/clipboard',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'clipboard',
    description: 'The Clipboard API enables copy and pasting to/from the system clipboard.',
    author: 'itschaced',
  },
  {
    name: '@capacitor/push-notifications',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'push-notifications',
    description: 'The Push Notifications API provides access to native push notifications.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-community/date-picker',
    href: 'git+https://github.com/capacitor-community/date-picker.git',
    title: 'date-picker',
    description: 'Native DateTime Picker Plugin for Capacitor Apps',
    author: 'jcesarmobile',
  },
  {
    name: '@whiteguru/capacitor-plugin-video-editor',
    href: 'git+https://github.com/dragermrb/capacitor-plugin-video-editor.git',
    title: 'capacitor-plugin-video-editor',
    description: 'Capacitor plugin to edit videos',
    author: 'dragermrb',
  },
  {
    name: 'capacitor-screenshot',
    href: 'git+https://github.com/ludufre/capacitor-screenshot.git',
    title: 'capacitor-screenshot',
    description: 'This plugin take screenshot of the app or webpage',
    author: 'ludufre',
  },
  {
    name: '@capacitor-community/photoviewer',
    href: 'git+https://github.com/capacitor-community/photoviewer.git',
    title: 'photoviewer',
    description: 'PhotoViewer table images with fullscreen and sharing capabilities',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-plugin-developer-options',
    href: 'git+https://github.com/asephermann/capacitor-plugin-developer-options.git',
    title: 'capacitor-plugin-developer-options',
    description: 'Capacitor Plugin to check and open developer options',
    author: 'asephermann',
  },
  {
    name: '@whiteguru/capacitor-plugin-file-opener',
    href: 'git+https://github.com/dragermrb/capacitor-plugin-file-opener.git',
    title: 'capacitor-plugin-file-opener',
    description: 'Capacitor plugin to open files',
    author: 'dragermrb',
  },
  {
    name: '@capacitor/dialog',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'dialog',
    description: 'The Dialog API provides methods for triggering native dialog windows for alerts, confirmations, and input prompts',
    author: 'itschaced',
  },
  {
    name: 'capacitor-branch-deep-links',
    href: 'git+https://github.com/BranchMetrics/capacitor-branch-deep-links.git',
    title: 'capacitor-branch-deep-links',
    description: 'Capacitor plugin for Branch.io deep links',
    author: 'echo_branch',
  },
  {
    name: '@evva/capacitor-secure-storage-plugin',
    href: 'git+https://github.com/evva-sfw/capacitor-secure-storage-plugin.git',
    title: 'capacitor-secure-storage-plugin',
    description: 'Securely store secrets such as usernames, passwords, tokens, certificates or other sensitive information (strings) on iOS & Android',
    author: 'sfw-evva',
  },
  {
    name: 'capacitor-document-scanner',
    href: 'git+https://github.com/WebsiteBeaver/capacitor-document-scanner.git',
    title: 'capacitor-document-scanner',
    description: 'A Capacitor plugin that lets you scan documents using Android and iOS',
    author: 'dmarcus',
  },
  {
    name: '@capawesome/capacitor-torch',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-torch',
    description: 'Capacitor plugin for switching the flashlight on and off.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/device-security-detect',
    href: 'git+https://github.com/capacitor-community/device-security-detect.git',
    title: 'device-security-detect',
    description:
      'The Device Security Detect plugin is designed to provide comprehensive device security detection capabilities for Capacitor-based applications. It aims to detect the device has been rooted (Android) or jailbroken (iOS). By using this plugin, developers ca',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-plugin-ios-webview-configurator',
    href: 'git+https://github.com/cellular/capacitor-plugin-ios-webview-configurator.git',
    title: 'capacitor-plugin-ios-webview-configurator',
    description: '""',
    author: 'dlehmhus',
  },
  {
    name: '@capacitor/app-launcher',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'app-launcher',
    description: 'The AppLauncher API allows to open other apps',
    author: 'itschaced',
  },
  {
    name: '@capgo/native-market',
    href: 'git+https://github.com/riderx/native-market.git',
    title: 'native-market',
    description: 'A native market plugin for linking to google play or app store.',
    author: 'riderx',
  },
  {
    name: '@whiteguru/capacitor-plugin-facebook-login',
    href: 'git+https://github.com/dragermrb/capacitor-plugin-facebook-login.git',
    title: 'capacitor-plugin-facebook-login',
    description: 'Capacitor plugin to login with Facebook',
    author: 'dragermrb',
  },
  {
    name: '@revenuecat/purchases-capacitor',
    href: 'git+https://github.com/RevenueCat/purchases-capacitor.git',
    title: 'purchases-capacitor',
    description: 'Capacitor in-app purchases and subscriptions made easy. Support for iOS and Android.',
    author: 'vegaro',
  },
  {
    name: '@mozartec/capacitor-microphone',
    href: 'git+https://github.com/mozartec/capacitor-microphone.git',
    title: 'capacitor-microphone',
    description: 'This Microphone API provides the ability to interact with the microphone and record Audio',
    author: 'mozart-alkhateeb',
  },
]
