export const actions = [
  {
    name: 'capacitor-native-http',
    href: 'git+https://github.com/viniciusgandrade/capacitor-native-http.git',
    title: 'capacitor-native-http',
    description: 'Plugin capacitor para requisições nativas',
    author: 'viniciusgandrade1',
  },
  {
    name: 'capacitor-secure-storage-plugin',
    href: 'git+https://github.com/martinkasa/capacitor-secure-storage-plugin.git',
    title: 'capacitor-secure-storage-plugin',
    description: 'Securely store secrets such as usernames, passwords, tokens, certificates or other sensitive information (strings) on iOS & Android',
    author: 'martinkasa',
  },
  {
    name: '@capacitor-community/file-opener',
    href: 'git+https://github.com/capacitor-community/file-opener.git',
    title: 'file-opener',
    description: 'Capacitor File Opener. The plugin is able to open a file given the mimeType and the file uri.',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-plugin-safe-area',
    href: 'git+https://github.com/AlwaysLoveme/capacitor-plugin-safe-area.git.git',
    title: 'capacitor-plugin-safe-area',
    description: 'a capacitor plugin to get SafeArea info on Android and IOS',
    author: 'zhuxian',
  },
  {
    name: 'appsflyer-capacitor-plugin',
    href: 'git+https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin.git',
    title: 'appsflyer-capacitor-plugin',
    description: 'AppsFlyer SDK plugin for Capacitor',
    author: 'amit-kremer93',
  },
  {
    name: 'capacitor-native-settings',
    href: 'git+https://github.com/RaphaelWoude/capacitor-native-settings.git',
    title: 'capacitor-native-settings',
    description: 'Capacitor plugin to open native settings screens for android and iOS',
    author: 'dennisameling',
  },
  {
    name: '@capacitor-community/firebase-analytics',
    href: 'git+https://github.com/capacitor-community/firebase-analytics.git',
    title: 'firebase-analytics',
    description: 'A native plugin for firebase analytics.',
    author: 'jcesarmobile',
  },
  {
    name: '@bistroo/vite-plugin-capacitor',
    href: 'git+https://github.com/bistroo/vite-plugin-capacitor.git',
    title: 'vite-plugin-capacitor',
    description: 'Vite plugin for capacitor',
    author: 'bistroo-dev',
  },
  {
    name: 'capacitor-plugin-app-tracking-transparency',
    href: 'git+https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency.git',
    title: 'capacitor-plugin-app-tracking-transparency',
    description: 'Capacitor plugin to request user authorization to access app-related data for tracking the user or the device.',
    author: 'mahnuh',
  },
  {
    name: '@capawesome/capacitor-app-update',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-app-update',
    description: 'Capacitor plugin that assists with app updates.',
    author: 'robingenz',
  },
  {
    name: '@capacitor/preferences',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'preferences',
    description: 'The Preferences API provides a simple key/value persistent store for lightweight data.',
    author: 'itschaced',
  },
  {
    name: '@newrelic/newrelic-capacitor-plugin',
    href: 'git+https://github.com/newrelic/newrelic-capacitor-plugin.git',
    title: 'newrelic-capacitor-plugin',
    description: 'NewRelic Plugin for ionic Capacitor',
    author: 'newrelic',
  },
  {
    name: '@codetrix-studio/capacitor-google-auth',
    href: 'git+https://github.com/CodetrixStudio/CapacitorGoogleAuth.git',
    title: 'capacitor-google-auth',
    description: 'Google Auth plugin for capacitor.',
    author: 'parveenkhtkr',
  },
  {
    name: '@capacitor-community/media',
    href: 'git+https://github.com/capacitor-community/media.git',
    title: 'media',
    description: 'Capacitor plugin for saving and retrieving photos and videos, and managing photo albums.',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/in-app-review',
    href: 'git+https://github.com/capacitor-community/in-app-review.git',
    title: 'in-app-review',
    description: 'Lets you prompt users to submit app store ratings and reviews without leaving your app - using platform native dialogs.',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-firebase/crashlytics',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'crashlytics',
    description: 'Capacitor plugin for Firebase Crashlytics.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/sqlite',
    href: 'git+https://github.com/capacitor-community/sqlite.git',
    title: 'sqlite',
    description: 'Community plugin for native & electron SQLite databases',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/device',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'device',
    description: 'The Device API exposes internal information about the device, such as the model and operating system version, along with user information such as unique ids.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-mlkit/barcode-scanning',
    href: 'git+https://github.com/capawesome-team/capacitor-mlkit.git',
    title: 'barcode-scanning',
    description: 'Capacitor plugin for ML Kit Barcode Scanning.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-firebase/analytics',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'analytics',
    description: 'Capacitor plugin for Firebase Analytics.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/intercom',
    href: 'git+https://github.com/capacitor-community/intercom.git',
    title: 'intercom',
    description: 'Enable Intercom features for Capacitor apps',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/privacy-screen',
    href: 'git+https://github.com/capacitor-community/privacy-screen.git',
    title: 'privacy-screen',
    description: 'Capacitor plugin that protects your app from displaying a screenshot in Recents screen/App Switcher.',
    author: 'jcesarmobile',
  },
  {
    name: '@capgo/capacitor-social-login',
    href: 'git+https://github.com/Cap-go/capacitor-social-login.git',
    title: 'capacitor-social-login',
    description: 'All social logins in one plugin',
    author: 'riderx',
  },
  {
    name: '@capacitor-community/camera-preview',
    href: 'git+https://github.com/capacitor-community/camera-preview.git',
    title: 'camera-preview',
    description: 'Camera preview',
    author: 'jcesarmobile',
  },
  {
    name: '@capawesome/capacitor-file-picker',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-file-picker',
    description: 'Capacitor plugin that allows the user to select a file.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-firebase/remote-config',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'remote-config',
    description: 'Capacitor plugin for Firebase Remote Config.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-firebase/authentication',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'authentication',
    description: 'Capacitor plugin for Firebase Authentication.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/http',
    href: 'git+https://github.com/capacitor-community/http.git',
    title: 'http',
    description: 'A native HTTP plugin for CORS-free requests and file transfers',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/fcm',
    href: 'git+https://github.com/capacitor-community/fcm.git',
    title: 'fcm',
    description: 'Enable Firebase Cloud Messaging features for Capacitor apps',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/app',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'app',
    description:
      'The App API handles high level App state and events.For example, this API emits events when the app enters and leaves the foreground, handles deeplinks, opens other apps, and manages persisted plugin state.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-community/contacts',
    href: 'git+https://github.com/capacitor-community/contacts.git',
    title: 'contacts',
    description: 'Contacts Plugin for Capacitor',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/filesystem',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'filesystem',
    description: 'The Filesystem API provides a NodeJS-like API for working with files on the device.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-firebase/app',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'app',
    description: 'Capacitor plugin for Firebase App.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/speech-recognition',
    href: 'git+https://github.com/capacitor-community/speech-recognition.git',
    title: 'speech-recognition',
    description: 'A native plugin for speech recognition',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/keep-awake',
    href: 'git+https://github.com/capacitor-community/keep-awake.git',
    title: 'keep-awake',
    description: 'Prevent your screen from getting some sleep!',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/screen-brightness',
    href: 'git+https://github.com/capacitor-community/screen-brightness.git',
    title: 'screen-brightness',
    description: 'control screen brightness on ios and android',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-firebase/messaging',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'messaging',
    description: 'Capacitor plugin for Firebase Cloud Messaging (FCM).',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/bluetooth-le',
    href: 'git+https://github.com/capacitor-community/bluetooth-le.git',
    title: 'bluetooth-le',
    description: 'Capacitor plugin for Bluetooth Low Energy ',
    author: 'jcesarmobile',
  },
  {
    name: '@transistorsoft/capacitor-background-fetch',
    href: 'git+https://github.com/transistorsoft/capacitor-background-fetch.git',
    title: 'capacitor-background-fetch',
    description: 'Periodic callbacks in the background for both IOS and Android',
    author: 'transistorsoft-admin',
  },
  {
    name: '@capacitor-community/native-audio',
    href: 'git+https://github.com/capacitor-community/native-audio.git',
    title: 'native-audio',
    description: 'A native plugin for native audio engine',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/apple-sign-in',
    href: 'git+https://github.com/capacitor-community/apple-sign-in.git',
    title: 'apple-sign-in',
    description: 'Capacitor Sign in with Apple',
    author: 'jcesarmobile',
  },
  {
    name: '@capgo/capacitor-native-biometric',
    href: 'git+https://github.com/Cap-go/capacitor-native-biometric.git',
    title: 'capacitor-native-biometric',
    description: 'This plugin gives access to the native biometric apis for android and iOS',
    author: 'riderx',
  },
  {
    name: '@capgo/inappbrowser',
    href: 'git+https://github.com/Cap-go/capacitor-inappbrowser.git',
    title: 'inappbrowser',
    description: 'Capacitor plugin in app browser',
    author: 'riderx',
  },
  {
    name: '@aparajita/capacitor-biometric-auth',
    href: 'git+https://github.com/aparajita/capacitor-biometric-auth.git',
    title: 'capacitor-biometric-auth',
    description: 'Provides access to the native biometric auth & device security APIs for Capacitor apps',
    author: 'ckgaparajita',
  },
  {
    name: '@aparajita/capacitor-secure-storage',
    href: 'git+https://github.com/aparajita/capacitor-secure-storage.git',
    title: 'capacitor-secure-storage',
    description: 'Capacitor 5+ plugin that provides secure storage for the iOS and Android',
    author: 'ckgaparajita',
  },
  {
    name: '@capacitor/browser',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'browser',
    description: 'The Browser API provides the ability to open an in-app browser and subscribe to browser events.',
    author: 'itschaced',
  },
  {
    name: '@transistorsoft/capacitor-background-geolocation',
    href: 'git+https://github.com/transistorsoft/capacitor-background-geolocation.git',
    title: 'capacitor-background-geolocation',
    description: 'The most sophisticated cross platform Capacitor background location tracking & geofencing module with battery-conscious motion-detection intelligence',
    author: 'transistorsoft-admin',
  },
  {
    name: '@capacitor/status-bar',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'status-bar',
    description: 'The StatusBar API Provides methods for configuring the style of the Status Bar, along with showing or hiding it.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-community/facebook-login',
    href: 'git+ssh://git@github.com/capacitor-community/facebook-login.git',
    title: 'facebook-login',
    description: 'A native plugin for Facebook Login',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-voice-recorder',
    href: 'git+https://github.com/tchvu3/capacitor-voice-recorder.git',
    title: 'capacitor-voice-recorder',
    description: 'Capacitor plugin for voice recording',
    author: 'tchvu3',
  },
  {
    name: '@capawesome/capacitor-badge',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-badge',
    description: 'Capacitor plugin to access and update the badge number of the app icon.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/native-market',
    href: 'git+https://github.com/capacitor-community/native-market.git',
    title: 'native-market',
    description: 'A native market plugin for linking to google play or app store.',
    author: 'jcesarmobile',
  },
  {
    name: '@capawesome/capacitor-screen-orientation',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-screen-orientation',
    description: 'Capacitor plugin to lock/unlock the screen orientation.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/safe-area',
    href: 'git+https://github.com/capacitor-community/safe-area.git',
    title: 'safe-area',
    description: 'Capacitor Plugin that exposes the safe area insets from the native iOS/Android device to your web project.',
    author: 'jcesarmobile',
  },
  {
    name: '@sentry/capacitor',
    href: 'git+https://github.com/getsentry/sentry-capacitor.git',
    title: 'capacitor',
    description: 'Official Sentry SDK for Capacitor',
    author: 'billyvg',
  },
  {
    name: '@capgo/capacitor-updater',
    href: 'git+https://github.com/Cap-go/capacitor-updater.git',
    title: 'capacitor-updater',
    description: 'Live update for capacitor apps',
    author: 'riderx',
  },
  {
    name: '@capacitor/geolocation',
    href: 'git+https://github.com/ionic-team/capacitor-geolocation.git',
    title: 'geolocation',
    description:
      'The Geolocation API provides simple methods for getting and tracking the current position of the device using GPS, along with altitude, heading, and speed information if available.',
    author: 'itschaced',
  },
  {
    name: 'capacitor-file-chunk',
    href: 'git+https://github.com/qrclip/capacitor-file-chunk.git',
    title: 'capacitor-file-chunk',
    description: 'Capacitor plugin to read and write files in chunks using a local server and without using capacitor bridge.',
    author: 'qrclip',
  },
  {
    name: '@jcesarmobile/ssl-skip',
    href: 'git+https://github.com/jcesarmobile/ssl-skip.git',
    title: 'ssl-skip',
    description: 'Capacitor plugin for skipping ssl checks',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-firebase/performance',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'performance',
    description: 'Capacitor plugin for Firebase Performance Monitoring.',
    author: 'robingenz',
  },
  {
    name: '@bcyesil/capacitor-plugin-printer',
    href: 'git+https://github.com/BarisCanYesil/capacitor-plugin-printer.git',
    title: 'capacitor-plugin-printer',
    description: 'Capacitor plugin for printing HTML format value iOS/Android apps.',
    author: 'bariscanyesil',
  },
  {
    name: '@capawesome/capacitor-background-task',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-background-task',
    description: 'Capacitor plugin for running background tasks.',
    author: 'robingenz',
  },
  {
    name: '@capawesome-team/capacitor-file-opener',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-file-opener',
    description: 'Capacitor plugin to open a file with the default application.',
    author: 'robingenz',
  },
  {
    name: 'pinia-plugin-capacitor-persist',
    href: 'git+https://github.com/craigrileyuk/pinia-plugin-capacitor-persist.git',
    title: 'pinia-plugin-capacitor-persist',
    description: 'A Vue 3 Pinia plugin which persists store content using the CapacitorJS Preferences store.',
    author: 'craigrileyuk',
  },
  {
    name: '@ebarooni/capacitor-calendar',
    href: 'git+https://github.com/ebarooni/capacitor-calendar.git',
    title: 'capacitor-calendar',
    description: 'A capacitor plugin for managing calendar events on iOS and Android, with reminders support on iOS.',
    author: 'ebarooni',
  },
  {
    name: '@capacitor/barcode-scanner',
    href: 'git+github.com/ionic-team/capacitor-barcode-scanner.git',
    title: 'barcode-scanner',
    description: 'Capacitor plugin using Outsystems Barcode libs',
    author: 'itschaced',
  },
  {
    name: '@capacitor/camera',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'camera',
    description: 'The Camera API provides the ability to take a photo with the camera or choose an existing one from the photo album.',
    author: 'itschaced',
  },
  {
    name: 'capacitor-rate-app',
    href: 'git+https://github.com/Nodonisko/capacitor-rate-app.git',
    title: 'capacitor-rate-app',
    description: 'Let users rate your app using native rate app dialog for both Android and iOS.',
    author: 'nodon',
  },
  {
    name: '@ua/capacitor-airship',
    href: 'git+https://github.com/urbanairship/capacitor-airship.git',
    title: 'capacitor-airship',
    description: 'Airship capacitor plugin',
    author: 'urbanairship',
  },
  {
    name: '@capacitor/splash-screen',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'splash-screen',
    description: 'The Splash Screen API provides methods for showing or hiding a Splash image.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-community/app-icon',
    href: 'git+https://github.com/capacitor-community/app-icon.git',
    title: 'app-icon',
    description: 'Capacitor community plugin for changing an iOS app icon.',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/text-to-speech',
    href: 'git+https://github.com/capacitor-community/text-to-speech.git',
    title: 'text-to-speech',
    description: 'Capacitor plugin for synthesizing speech from text.',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-jitsi-meet',
    href: 'git+https://github.com/calvinckho/capacitor-jitsi-meet.git',
    title: 'capacitor-jitsi-meet',
    description: 'This Ionic Capacitor plugin is created to make video calls through the free, open-sourced Jitsi video platform (https://meet.jit.si) on iOS and Android.',
    author: 'calvinckho',
  },
  {
    name: '@capacitor/screen-orientation',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'screen-orientation',
    description: 'The Screen Orientation API provides methods to lock and unlock the screen orientation.',
    author: 'itschaced',
  },
  {
    name: '@capgo/native-audio',
    href: 'git+https://github.com/Cap-go/capacitor-native-audio.git',
    title: 'native-audio',
    description: 'A native plugin for native audio engine',
    author: 'riderx',
  },
  {
    name: '@capacitor/keyboard',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'keyboard',
    description: 'The Keyboard API provides keyboard display and visibility control, along with event tracking when the keyboard shows and hides.',
    author: 'itschaced',
  },
  {
    name: 'capacitor-swipe-back-plugin',
    href: 'git+https://github.com/alesmraz/capacitor-plugin-swipe-back.git',
    title: 'capacitor-swipe-back-plugin',
    description:
      'Capacitor swipe back plugin. For Capacitor v3, v4 (0.0.3) and v5 (1.0.0+). For v2 use original plugin: https://github.com/diiiary/capacitor-plugin-ios-swipe-back',
    author: 'alesmraz',
  },
  {
    name: '@capawesome/capacitor-android-edge-to-edge-support',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-android-edge-to-edge-support',
    description: 'Capacitor plugin to support edge-to-edge display on Android.',
    author: 'robingenz',
  },
  {
    name: '@capacitor/text-zoom',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'text-zoom',
    description: 'The Text Zoom API provides the ability to change Web View text size for visual accessibility.',
    author: 'itschaced',
  },
  {
    name: 'capacitor-email-composer',
    href: 'git+https://github.com/EinfachHans/capacitor-email-composer.git',
    title: 'capacitor-email-composer',
    description: 'E-Mail Composer Plugin for Capacitor',
    author: 'hanskrywaa',
  },
  {
    name: 'capacitor-radar',
    href: 'git+https://github.com/radarlabs/capacitor-radar.git',
    title: 'capacitor-radar',
    description: 'Capacitor plugin for Radar, the leading geofencing and location tracking platform',
    author: 'nickpatrick-radar',
  },
  {
    name: '@hugotomazi/capacitor-navigation-bar',
    href: 'git+https://github.com/hugotomazi/navigation-bar.git',
    title: 'capacitor-navigation-bar',
    description: 'Capacitor Plugin for Navigation Bar',
    author: 'hugotomazi',
  },
  {
    name: '@capacitor/share',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'share',
    description: 'The Share API provides methods for sharing content in any sharing-enabled apps the user may have installed.',
    author: 'itschaced',
  },
  {
    name: '@recognizebv/capacitor-plugin-msauth',
    href: 'git+https://github.com/recognizegroup/capacitor-plugin-msauth.git',
    title: 'capacitor-plugin-msauth',
    description: 'This plugin enables MSAL support for Capacitor.',
    author: 'johankamp',
  },
  {
    name: 'capacitor-video-player',
    href: 'git+https://github.com/harmonwood/capacitor-video-player.git',
    title: 'capacitor-video-player',
    description: 'custom Native Capacitor plugin to play a video',
    author: 'jeepq',
  },
  {
    name: '@capacitor-community/firebase-crashlytics',
    href: 'git+https://github.com/capacitor-community/firebase-crashlytics.git',
    title: 'firebase-crashlytics',
    description: 'Capacitor plugin for Firebase Crashlytics.',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/haptics',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'haptics',
    description: 'The Haptics API provides physical feedback to the user through touch or vibration.',
    author: 'itschaced',
  },
  {
    name: '@capacitor/inappbrowser',
    href: 'git+https://github.com/ionic-team/capacitor-os-inappbrowser.git',
    title: 'inappbrowser',
    description:
      "The InAppBrowser Plugin provides a web browser view that allows you to load any web page externally. It behaves as a standard web browser and is useful to load untrusted content without risking your application's security. It offers three different ways t",
    author: 'itschaced',
  },
  {
    name: '@capacitor/action-sheet',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'action-sheet',
    description: 'The Action Sheet API provides access to native Action Sheets, which come up from the bottom of the screen and display actions a user can take.',
    author: 'itschaced',
  },
  {
    name: '@capacitor/live-updates',
    href: 'git+https://github.com/ionic-team/capacitor-live-updates-plugin.git',
    title: 'live-updates',
    description: 'Official Live Updates plugin for Capacitor',
    author: 'itschaced',
  },
  {
    name: '@capacitor-community/barcode-scanner',
    href: 'git+https://github.com/capacitor-community/barcode-scanner.git',
    title: 'barcode-scanner',
    description: 'A fast and efficient (QR) barcode scanner for Capacitor',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/network',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'network',
    description: 'The Network API provides network and connectivity information.',
    author: 'itschaced',
  },
  {
    name: '@capacitor-firebase/firestore',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'firestore',
    description: 'Capacitor plugin for Firebase Cloud Firestore.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-ios-autofill-save-password',
    href: 'git+https://github.com/cuongpl/capacitor-ios-autofill-save-password.git',
    title: 'capacitor-ios-autofill-save-password',
    description: 'Prompt to display dialog for saving password to keychain for iOS webview app.',
    author: 'cuongpl',
  },
  {
    name: '@capgo/capacitor-mute',
    href: 'git+https://github.com/Cap-go/capacitor-mute.git',
    title: 'capacitor-mute',
    description: 'Detect if the mute switch is enabled/disabled on a device',
    author: 'riderx',
  },
  {
    name: '@appcues/capacitor',
    href: 'git+https://github.com/appcues/appcues-capacitor-plugin.git',
    title: 'capacitor',
    description: 'Capcitor plugin to bridge the native Android and iOS Appcues mobile SDKs in an Ionic application.',
    author: 'stephano_appcues',
  },
  {
    name: '@aparajita/capacitor-dark-mode',
    href: 'git+https://github.com/aparajita/capacitor-dark-mode.git',
    title: 'capacitor-dark-mode',
    description: 'Universal dark mode support for Ionic web and native apps',
    author: 'ckgaparajita',
  },
  {
    name: '@cwoebker/capacitor-start-navigation',
    href: 'git+https://github.com/cwoebker/capacitor-start-navigation.git',
    title: 'capacitor-start-navigation',
    description: 'Starts navigation in the native maps application',
    author: 'cwoebker',
  },
  {
    name: '@capacitor-community/advertising-id',
    href: 'git+https://github.com/capacitor-community/advertising-id.git',
    title: 'advertising-id',
    description: 'Allows access to the IDFA (iOS) and GAID (Android)',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-blob-writer',
    href: 'git+https://github.com/diachedelic/capacitor-blob-writer.git',
    title: 'capacitor-blob-writer',
    description: 'Write javascript Blobs to the filesystem efficiently',
    author: 'diachedelic',
  },
  {
    name: '@capgo/nativegeocoder',
    href: 'git+https://github.com/Cap-go/capacitor-nativegeocoder.git',
    title: 'nativegeocoder',
    description: 'Capacitor plugin for native forward and reverse geocoding',
    author: 'riderx',
  },
  {
    name: '@capacitor-community/admob',
    href: 'git+ssh://git@github.com/capacitor-community/admob.git',
    title: 'admob',
    description: 'A native plugin for AdMob',
    author: 'jcesarmobile',
  },
  {
    name: 'hypertrack-sdk-ionic-capacitor',
    href: 'git+https://github.com/hypertrack/sdk-ionic-capacitor.git',
    title: 'hypertrack-sdk-ionic-capacitor',
    description: 'Capacitor plugin for HyperTrack generation SDKs',
    author: 'hypertrack',
  },
  {
    name: '@capacitor/toast',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'toast',
    description: 'The Toast API provides a notification pop up for displaying important information to a user. Just like real toast!',
    author: 'itschaced',
  },
  { name: '@capgo/camera-preview', href: 'git+https://github.com/Cap-go/camera-preview.git', title: 'camera-preview', description: 'Camera preview', author: 'riderx' },
  {
    name: 'capacitor-native-biometric',
    href: 'git+https://github.com/epicshaggy/capacitor-native-biometric.git',
    title: 'capacitor-native-biometric',
    description: 'This plugin gives access to the native biometric apis for android and iOS',
    author: 'epicshaggy',
  },
  {
    name: '@capacitor-firebase/app-check',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'app-check',
    description: 'Capacitor plugin for Firebase App Check.',
    author: 'robingenz',
  },
  {
    name: '@capawesome-team/capacitor-android-battery-optimization',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-android-battery-optimization',
    description: 'Capacitor plugin to access battery optimization settings on Android.',
    author: 'robingenz',
  },
  {
    name: '@capacitor/google-maps',
    href: 'git+https://github.com/ionic-team/capacitor-google-maps.git',
    title: 'google-maps',
    description: 'Google maps on Capacitor',
    author: 'itschaced',
  },
  {
    name: '@capawesome/capacitor-live-update',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-live-update',
    description: 'Capacitor plugin to update your app remotely in real-time.',
    author: 'robingenz',
  },
  { name: 'send-intent', href: 'git+https://github.com/carsten-klaffke/send-intent.git', title: 'send-intent', description: 'SendIntent', author: 'cklaffke' },
  {
    name: '@capacitor/push-notifications',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'push-notifications',
    description: 'The Push Notifications API provides access to native push notifications.',
    author: 'itschaced',
  },
  {
    name: '@capawesome/capacitor-managed-configurations',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-managed-configurations',
    description: 'Capacitor plugin to access managed configuration settings.',
    author: 'robingenz',
  },
  {
    name: '@capacitor/clipboard',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'clipboard',
    description: 'The Clipboard API enables copy and pasting to/from the system clipboard.',
    author: 'itschaced',
  },
  {
    name: 'capacitor-screenshot',
    href: 'git+https://github.com/ludufre/capacitor-screenshot.git',
    title: 'capacitor-screenshot',
    description: 'This plugin take screenshot of the app or webpage',
    author: 'ludufre',
  },
  {
    name: '@capacitor-community/date-picker',
    href: 'git+https://github.com/capacitor-community/date-picker.git',
    title: 'date-picker',
    description: 'Native DateTime Picker Plugin for Capacitor Apps',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/photoviewer',
    href: 'git+https://github.com/capacitor-community/photoviewer.git',
    title: 'photoviewer',
    description: 'PhotoViewer table images with fullscreen and sharing capabilities',
    author: 'jcesarmobile',
  },
  {
    name: '@whiteguru/capacitor-plugin-video-editor',
    href: 'git+https://github.com/dragermrb/capacitor-plugin-video-editor.git',
    title: 'capacitor-plugin-video-editor',
    description: 'Capacitor plugin to edit videos',
    author: 'dragermrb',
  },
  {
    name: 'capacitor-plugin-developer-options',
    href: 'git+https://github.com/asephermann/capacitor-plugin-developer-options.git',
    title: 'capacitor-plugin-developer-options',
    description: 'Capacitor Plugin to check and open developer options',
    author: 'asephermann',
  },
  {
    name: '@whiteguru/capacitor-plugin-file-opener',
    href: 'git+https://github.com/dragermrb/capacitor-plugin-file-opener.git',
    title: 'capacitor-plugin-file-opener',
    description: 'Capacitor plugin to open files',
    author: 'dragermrb',
  },
  {
    name: '@capacitor/dialog',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'dialog',
    description: 'The Dialog API provides methods for triggering native dialog windows for alerts, confirmations, and input prompts',
    author: 'itschaced',
  },
  {
    name: '@evva/capacitor-secure-storage-plugin',
    href: 'git+https://github.com/evva-sfw/capacitor-secure-storage-plugin.git',
    title: 'capacitor-secure-storage-plugin',
    description: 'Securely store secrets such as usernames, passwords, tokens, certificates or other sensitive information (strings) on iOS & Android',
    author: 'sfw-evva',
  },
  {
    name: '@capawesome/capacitor-torch',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-torch',
    description: 'Capacitor plugin for switching the flashlight on and off.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-document-scanner',
    href: 'git+https://github.com/WebsiteBeaver/capacitor-document-scanner.git',
    title: 'capacitor-document-scanner',
    description: 'A Capacitor plugin that lets you scan documents using Android and iOS',
    author: 'dmarcus',
  },
  {
    name: 'capacitor-branch-deep-links',
    href: 'git+https://github.com/BranchMetrics/capacitor-branch-deep-links.git',
    title: 'capacitor-branch-deep-links',
    description: 'Capacitor plugin for Branch.io deep links',
    author: 'echo_branch',
  },
  {
    name: '@capacitor/app-launcher',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'app-launcher',
    description: 'The AppLauncher API allows to open other apps',
    author: 'itschaced',
  },
  {
    name: '@capacitor-community/device-security-detect',
    href: 'git+https://github.com/capacitor-community/device-security-detect.git',
    title: 'device-security-detect',
    description:
      'The Device Security Detect plugin is designed to provide comprehensive device security detection capabilities for Capacitor-based applications. It aims to detect the device has been rooted (Android) or jailbroken (iOS). By using this plugin, developers ca',
    author: 'jcesarmobile',
  },
  {
    name: '@whiteguru/capacitor-plugin-facebook-login',
    href: 'git+https://github.com/dragermrb/capacitor-plugin-facebook-login.git',
    title: 'capacitor-plugin-facebook-login',
    description: 'Capacitor plugin to login with Facebook',
    author: 'dragermrb',
  },
  {
    name: '@revenuecat/purchases-capacitor',
    href: 'git+https://github.com/RevenueCat/purchases-capacitor.git',
    title: 'purchases-capacitor',
    description: 'Capacitor in-app purchases and subscriptions made easy. Support for iOS and Android.',
    author: 'vegaro',
  },
  {
    name: 'capacitor-plugin-ios-webview-configurator',
    href: 'git+https://github.com/cellular/capacitor-plugin-ios-webview-configurator.git',
    title: 'capacitor-plugin-ios-webview-configurator',
    description: '""',
    author: 'dlehmhus',
  },
  {
    name: '@capgo/native-market',
    href: 'git+https://github.com/riderx/native-market.git',
    title: 'native-market',
    description: 'A native market plugin for linking to google play or app store.',
    author: 'riderx',
  },
  {
    name: '@capacitor-community/image-to-text',
    href: 'git+ssh://git@github.com/capacitor-community/image-to-text.git',
    title: 'image-to-text',
    description: 'Image to Text (OCR) Plugin for Capacitor',
    author: 'jcesarmobile',
  },
  {
    name: '@mozartec/capacitor-microphone',
    href: 'git+https://github.com/mozartec/capacitor-microphone.git',
    title: 'capacitor-microphone',
    description: 'This Microphone API provides the ability to interact with the microphone and record Audio',
    author: 'mozart-alkhateeb',
  },
  {
    name: '@capacitor-community/stripe',
    href: 'git+https://github.com/capacitor-community/stripe.git',
    title: 'stripe',
    description: 'Stripe SDK bindings for Capacitor Applications',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-call-number',
    href: 'git+https://github.com/mantosh59/call-number.git',
    title: 'capacitor-call-number',
    description: 'Plugin to pick files/images/videos from android or ios.',
    author: 'devmantosh2019',
  },
  {
    name: 'capacitor-apprate-gfc',
    href: 'git+https://github.com/SASGeniusFlashConception/capacitor-apprate-gfc.git',
    title: 'capacitor-apprate-gfc',
    description: "Le plugin capacitor-apprate-gfc est une implementation native qui permet aux utilisateurs d'évaluer facilement votre application",
    author: 'geniusflashconception',
  },
  {
    name: '@foodello/intercom',
    href: 'git+https://github.com/fiksuruoka-fi/intercom.git',
    title: 'intercom',
    description: 'Enable Intercom features for Capacitor apps',
    author: 'eljass',
  },
  {
    name: 'capacitor-datawedge',
    href: 'git+https://github.com/jkbz64/capacitor-datawedge.git',
    title: 'capacitor-datawedge',
    description: 'DataWedge plugin for capacitor',
    author: 'jkbz',
  },
  {
    name: '@bondulich/native-audio',
    href: 'git+https://github.com/bondulich/native-audio.git',
    title: 'native-audio',
    description: 'A native plugin for native audio engine',
    author: 'bondulich',
  },
  {
    name: '@capacitor/local-notifications',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'local-notifications',
    description: 'The Local Notifications API provides a way to schedule device notifications locally (i.e. without a server sending push notifications).',
    author: 'itschaced',
  },
  {
    name: 'capacitor-music-controls-plugin-v3',
    href: 'git+https://github.com/ingageco/capacitor-music-controls-plugin-v3.git',
    title: 'capacitor-music-controls-plugin-v3',
    description: 'Implementation of MusicControls for Capacitor 3+ projects',
    author: 'ingage',
  },
  {
    name: 'capacitor-firebase-auth',
    href: 'git+https://github.com/baumblatt/capacitor-firebase-auth.git',
    title: 'capacitor-firebase-auth',
    description: 'Capacitor plugin for Firebase Authentication',
    author: 'baumblatt',
  },
  {
    name: 'capacitor-plugin-scanbot-sdk',
    href: '',
    title: 'capacitor-plugin-scanbot-sdk',
    description: 'Scanbot Document and Barcode Scanner SDK for Capacitor',
    author: 'scanbot',
  },
  {
    name: '@dghathway/firebase-remote-config',
    href: 'git+https://github.com/capacitor-community/firebase-remote-config.git',
    title: 'firebase-remote-config',
    description: 'A native plugin for firebase remote config',
    author: 'dghathway',
  },
  {
    name: '@davidwebwrk/barcode-scanner',
    href: 'git+https://github.com/capacitor-community/barcode-scanner.git',
    title: 'barcode-scanner',
    description: 'A fast and efficient (QR) barcode scanner for Capacitor',
    author: 'davidwebwrk',
  },
  {
    name: 'capacitor-pass-to-wallet',
    href: 'git+https://github.com/valentinAbundo/capacitor-pass-to-wallet.git.git',
    title: 'capacitor-pass-to-wallet',
    description: 'Allow to add .pkpass files to Apple Wallet',
    author: 'nitnelav97',
  },
  {
    name: '@johnjasonhudson/capacitor-healthkit',
    href: 'git+https://github.com/johnjasonhudson/capacitor-healthkit.git',
    title: 'capacitor-healthkit',
    description: 'Custom Capacitor HealthKit plugin with appleWalkingSteadiness support',
    author: 'johnjasonhudson',
  },
  {
    name: '@capacitor/motion',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'motion',
    description: 'The Motion API tracks accelerometer and device orientation (compass heading, etc.)',
    author: 'itschaced',
  },
  {
    name: '@pantrist/capacitor-firebase-dynamic-links',
    href: 'git+https://github.com/Pantrist-dev/capacitor-firebase-dynamic-links.git',
    title: 'capacitor-firebase-dynamic-links',
    description: 'Capacitor Plugin for Firebase Dynamic Links',
    author: 'nico.lueg',
  },
  {
    name: '@jonz94/capacitor-sim',
    href: 'git+https://github.com/jonz94/capacitor-sim.git',
    title: 'capacitor-sim',
    description: "Capacitor plugin to get information from device's sim cards",
    author: 'jonz94',
  },
  {
    name: '@capawesome/capacitor-photo-editor',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-photo-editor',
    description: 'Capacitor plugin that allows the user to edit a photo.',
    author: 'robingenz',
  },
  {
    name: '@capgo/capacitor-crisp',
    href: 'git+https://github.com/Cap-go/capacitor-crisp.git',
    title: 'capacitor-crisp',
    description: 'Crisp native SDK for capacitor',
    author: 'riderx',
  },
  {
    name: '@michaelwolz/camera-preview-lite',
    href: 'git+https://github.com/michaelwolz/camera-preview-lite.git',
    title: 'camera-preview-lite',
    description: 'Fork of the capacitor-community/camera-preview plugin focusing on high resolution photos without bloating up the code.',
    author: 'michaelwolz',
  },
  {
    name: 'capacitor-plugin-webview-cache',
    href: 'git+https://github.com/FrameworkSystemsGmbH/capacitor-plugin-webview-cache.git',
    title: 'capacitor-plugin-webview-cache',
    description: 'Clears Android WebView cache',
    author: 'fsare',
  },
  {
    name: '@e-is/capacitor-bluetooth-serial',
    href: 'git+https://github.com/e-is/capacitor-bluetooth-serial.git',
    title: 'capacitor-bluetooth-serial',
    description: 'Capacitor Bluetooth Serial Plugin',
    author: 'blavenie',
  },
  {
    name: 'capacitor-adjust-resize',
    href: 'git+https://github.com/NePheus/capacitor-adjust-resize.git',
    title: 'capacitor-adjust-resize',
    description: 'Auto adjust the native android layout when the keyboard opens. Needed when using translucent status and navigation bars.',
    author: 'nepheus',
  },
  {
    name: 'capacitor-plugin-security-check',
    href: 'git+https://github.com/indodevniaga/capacitor-plugin-security-check.git',
    title: 'capacitor-plugin-security-check',
    description: 'capacitor-plugin-security-check',
    author: 'greatdayhr',
  },
  {
    name: '@basecom-gmbh/capacitor-jailbreak-root-detection',
    href: 'git+https://github.com/Phil0xFF/capacitor-jailbreak-root-detection.git',
    title: 'capacitor-jailbreak-root-detection',
    description: 'Jailbreak Root detection Plugin for Capacitor',
    author: 'm.borgmann',
  },
  {
    name: 'capacitor-plugin-useragent',
    href: 'git+https://github.com/asephermann/capacitor-plugin-useragent.git',
    title: 'capacitor-plugin-useragent',
    description: 'Allows you to change your User-Agent for HTTP requests.',
    author: 'asephermann',
  },
  {
    name: '@capacitor-community/stripe-terminal',
    href: 'git+https://github.com/capacitor-community/stripe.git',
    title: 'stripe-terminal',
    description: 'Stripe SDK bindings for Capacitor Applications',
    author: 'jcesarmobile',
  },
  {
    name: '@capawesome-team/capacitor-datetime-picker',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-datetime-picker',
    description: 'Capacitor plugin that let the user easily enter both a date and a time.',
    author: 'robingenz',
  },
  {
    name: '@jofr/capacitor-media-session',
    href: 'git+https://github.com/jofr/capacitor-media-session.git',
    title: 'capacitor-media-session',
    description: 'Capacitor plugin for media notifications and platform media keys as well as background audio playback',
    author: 'jofr',
  },
  {
    name: '@perfood/capacitor-healthkit',
    href: 'git+https://github.com/perfood/capacitor-healthkit.git',
    title: 'capacitor-healthkit',
    description: 'Capacitor plugin to read data from and write data to Apple Health',
    author: 'mahnuh',
  },
  {
    name: 'tailwind-capacitor',
    href: 'git+https://github.com/Cap-go/tailwind-capacitor.git',
    title: 'tailwind-capacitor',
    description: 'Tailwind plugin for Capacitor apps',
    author: 'riderx',
  },
  {
    name: '@capgo/capacitor-data-storage-sqlite',
    href: 'git+https://github.com/Cap-go/capacitor-data-storage-sqlite.git',
    title: 'capacitor-data-storage-sqlite',
    description: 'SQLite Storage of key/value strings pair',
    author: 'riderx',
  },
  {
    name: 'capacitor-appmetrica-plugin',
    href: 'git+https://github.com/virusv/capacitor-appmetrica-plugin.git',
    title: 'capacitor-appmetrica-plugin',
    description: 'Yandex App metrica plugin for Capacitor',
    author: 'virusv',
  },
  {
    name: '@capacitor-firebase/storage',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'storage',
    description: 'Capacitor plugin for Firebase Cloud Storage.',
    author: 'robingenz',
  },
  {
    name: '@microblink/blinkid-capacitor',
    href: 'git+https://github.com/BlinkID/blinkid-capacitor.git',
    title: 'blinkid-capacitor',
    description: 'A small and powerful ID card Capacitor plugin for BlinkID SDK',
    author: 'microblinkadmin',
  },
  {
    name: '@capgo/capacitor-flash',
    href: 'git+https://github.com/Cap-go/capacitor-flash.git',
    title: 'capacitor-flash',
    description: 'Switch the Flashlight / Torch of your device.',
    author: 'riderx',
  },
  {
    name: 'capacitor-antitampering',
    href: 'git+https://github.com/asephermann/capacitor-antitampering.git',
    title: 'capacitor-antitampering',
    description: 'Capacitor plugin to verifies the integrity of the static assets of your application, cheking if the files have changed since the original build.',
    author: 'asephermann',
  },
  {
    name: '@aparajita/capacitor-ios-silent-notifications',
    href: 'git+https://github.com/aparajita/capacitor-ios-silent-notifications.git',
    title: 'capacitor-ios-silent-notifications',
    description: 'Capacitor 5+ plugin that provides silent notification support for iOS',
    author: 'ckgaparajita',
  },
  {
    name: '@capgo/capacitor-navigation-bar',
    href: 'git+https://github.com/Cap-go/capacitor-navigation-bar.git',
    title: 'capacitor-navigation-bar',
    description: 'Set navigation bar color for android lolipop and higher',
    author: 'riderx',
  },
  {
    name: '@skektec/capacitor-contacts',
    href: 'git+https://github.com/Skektec/Capacitor-V7-Contacts-Port.git',
    title: 'capacitor-contacts',
    description: 'Contacts Plugin for Capacitor, ported for Capacitor V7',
    author: 'skektec',
  },
  {
    name: '@capgo/capacitor-screen-recorder',
    href: 'git+https://github.com/Cap-go/capacitor-screen-recorder.git',
    title: 'capacitor-screen-recorder',
    description: "Record device's screen",
    author: 'riderx',
  },
  {
    name: '@falconeta/capacitor-wifi-connect',
    href: 'git+https://github.com/falconeta/capacitor-wifi-connect.git',
    title: 'capacitor-wifi-connect',
    description: 'plugin used for connect the device through Wifi also with prefix',
    author: 'falconeta-dev',
  },
  {
    name: '@aashu-dubey/capacitor-statusbar-safe-area',
    href: 'git+https://github.com/Aashu-Dubey/capacitor-statusbar-safe-area.git',
    title: 'capacitor-statusbar-safe-area',
    description: 'Get Status bar height and Safe area insets on Android & iOS.',
    author: 'aashu-dubey',
  },
  {
    name: 'capacitor-plugin-playlist',
    href: 'git+https://github.com/phiamo/capacitor-plugin-playlist.git',
    title: 'capacitor-plugin-playlist',
    description: 'Playlist ',
    author: 'phiamo',
  },
  {
    name: '@capacitor-community/volume-buttons',
    href: 'git+https://github.com/capacitor-community/volume-buttons.git',
    title: 'volume-buttons',
    description: 'Capacitor Volume Buttons. The plugin enables to listen to hardware volume button presses',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor/screen-reader',
    href: 'git+https://github.com/ionic-team/capacitor-plugins.git',
    title: 'screen-reader',
    description: 'The Screen Reader API provides access to TalkBack/VoiceOver/etc. and provides simple text-to-speech capabilities for visual accessibility.',
    author: 'itschaced',
  },
  {
    name: 'capacitor-subscriptions',
    href: 'git+https://github.com/CraigRonald555/capacitor-subscriptions.git.git',
    title: 'capacitor-subscriptions',
    description: 'A capacitor plugin which simplifies subscription handling - implementing StoreKit 2 and Google Billing',
    author: 'craigronald',
  },
  {
    name: '@capacitor/background-runner',
    href: 'git+https://github.com/ionic-team/capacitor-background-runner.git',
    title: 'background-runner',
    description: 'Capacitor Background Runner',
    author: 'itschaced',
  },
  {
    name: 'capacitor-read-native-setting',
    href: 'git+https://github.com/ingageco/capacitor-read-native-setting.git',
    title: 'capacitor-read-native-setting',
    description: 'A simple plugin to read from Info.plist on iOS and strings.xml on Android',
    author: 'ingage',
  },
  {
    name: '@ranit-mondal/emarsys-sdk-wrapper-plugin',
    href: 'git+https://github.com/ranit-mondal/emarsys-sdk-wrapper-plugin.git',
    title: 'emarsys-sdk-wrapper-plugin',
    description: 'Custom Capacitor Plugin To have communication with Emarsys SDK',
    author: 'ranit1998',
  },
  {
    name: '@okode/capacitor-marketingcloud',
    href: 'git+https://github.com/okode/capacitor-marketingcloud.git',
    title: 'capacitor-marketingcloud',
    description: 'MarketingCloud Capacitor Plugin',
    author: 'okode',
  },
  {
    name: 'capacitor-plugin-rfid',
    href: 'git+https://github.com/YamilEzequiel/plugins-rfid-ionic.git',
    title: 'capacitor-plugin-rfid',
    description: 'Read RFID',
    author: 'yamillazzari',
  },
  {
    name: '@adeprez/capacitor-user-agent',
    href: 'git+https://github.com/adeprez/capacitor-user-agent.git',
    title: 'capacitor-user-agent',
    description: 'User Agent get/set/reset plugin for Capacitor',
    author: 'adeprez',
  },
  {
    name: 'capacitor-native-google-one-tap-signin',
    href: 'git+https://github.com/inouiw/capacitor-native-google-one-tap-signin.git',
    title: 'capacitor-native-google-one-tap-signin',
    description: 'Google One Tap sign-in plugin for capacitor.',
    author: 'inouiw',
  },
  {
    name: '@capgo/capacitor-shake',
    href: 'git+https://github.com/Cap-go/capacitor-shake.git',
    title: 'capacitor-shake',
    description: 'Detect shake gesture in device',
    author: 'riderx',
  },
  {
    name: '@capawesome/capacitor-app-review',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-app-review',
    description: 'Capacitor plugin that allows users to submit app store reviews and ratings.',
    author: 'robingenz',
  },
  {
    name: '@capawesome/capacitor-posthog',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-posthog',
    description: 'Unofficial Capacitor plugin for PostHog SDK.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-google-play-services-checker',
    href: 'git+https://github.com/asephermann/capacitor-google-play-services-checker.git',
    title: 'capacitor-google-play-services-checker',
    description: 'Capacitor Plugin Google Play Services Checker',
    author: 'asephermann',
  },
  {
    name: '@capacitor-community/video-recorder',
    href: 'git+https://github.com/capacitor-community/video-recorder.git',
    title: 'video-recorder',
    description: 'capacitor plugin to record video',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-suppress-longpress-gesture',
    href: 'git+https://github.com/Nikita-schetko/capacitor-suppress-longpress-gesture.git',
    title: 'capacitor-suppress-longpress-gesture',
    description: 'This plugin allows to suppress longpress gesture in iOS system. Designed for capacitor v6, and support previous versions also. Check readme.md',
    author: 'nikita_shchetko',
  },
  {
    name: '@unsou/capacitor-intercom',
    href: 'git+https://github.com/unsou/capacitor-intercom.git',
    title: 'capacitor-intercom',
    description: 'Enable Intercom features for Capacitor apps',
    author: 'maxnowack',
  },
  {
    name: '@rollershop/capacitor-emarsys-sdk',
    href: 'git+https://github.com/roller-ecom/capacitor-emarsys-sdk.git',
    title: 'capacitor-emarsys-sdk',
    description: 'Capacitor Plugin that wraps the Emarsys SDK',
    author: 'roller-shop',
  },
  {
    name: 'capacitor-hce-plugin',
    href: 'git+https://github.com/thangman22/capacitor-hce-plugin.git',
    title: 'capacitor-hce-plugin',
    description: 'Plugin to make your capacitor app to support NFC HCE',
    author: 'thangman22',
  },
  {
    name: '@anuradev/capacitor-background-mode',
    href: 'git+https://github.com/angeloraso/capacitor-background-mode.git.git',
    title: 'capacitor-background-mode',
    description: 'Capacitor plugin to enable background mode',
    author: 'araso',
  },
  { name: 'capacitor-zeroconf', href: 'git+https://github.com/trik/capacitor-zeroconf.git', title: 'capacitor-zeroconf', description: 'Capacitor ZeroConf plugin', author: 'trik' },
  {
    name: '@freeedcom/capacitor-facebook-login',
    href: 'git+ssh://git@github.com/freeedcom/capacitor-facebook-login.git',
    title: 'capacitor-facebook-login',
    description: 'A native plugin for Facebook Login',
    author: 'aidar-freeed',
  },
  {
    name: 'capacitor-biometric-auth',
    href: 'git+https://github.com/arielhernandezmusa/capacitor-biometric-auth.git',
    title: 'capacitor-biometric-auth',
    description: 'Complete',
    author: 'arielhernandezmusa',
  },
  {
    name: '@capawesome/capacitor-cloudinary',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-cloudinary',
    description: 'Unofficial Capacitor plugin for integrating with Cloudinary.',
    author: 'robingenz',
  },
  {
    name: '@capacitor-community/tap-jacking',
    href: 'git+https://github.com/capacitor-community/tap-jacking.git',
    title: 'tap-jacking',
    description: 'Capacitor Plugin to prevent tap jacking in Android',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-firebase/functions',
    href: 'git+https://github.com/capawesome-team/capacitor-firebase.git',
    title: 'functions',
    description: 'Capacitor plugin for Firebase Cloud Functions.',
    author: 'robingenz',
  },
  {
    name: '@independo/capacitor-voice-recorder',
    href: 'git+https://github.com/independo-gmbh/capacitor-voice-recorder.git',
    title: 'capacitor-voice-recorder',
    description: 'Capacitor plugin for voice recording',
    author: 'kstruempf',
  },
  {
    name: '@houseninja/capacitor-mixpanel',
    href: 'git+https://github.com/houseninjadojo/capacitor-mixpanel.git',
    title: 'capacitor-mixpanel',
    description: 'Capacitor plugin for Mixpanel',
    author: 'mileszim',
  },
  {
    name: 'capacitor-request-location',
    href: 'git+https://github.com/asephermann/capacitor-request-location.git',
    title: 'capacitor-request-location',
    description: 'A Capacitor plugin to check and request permission for using location service (Android)',
    author: 'asephermann',
  },
  {
    name: '@remnote/capacitor-updater',
    href: 'git+https://github.com/Cap-go/capacitor-updater.git',
    title: 'capacitor-updater',
    description: 'OTA update for capacitor apps',
    author: 'mfranzs',
  },
  {
    name: '@atroo/capacitor-secure-storage-plugin',
    href: 'git+https://github.com/atroo/capacitor-secure-storage-plugin.git.git',
    title: 'capacitor-secure-storage-plugin',
    description: 'Securely store secrets such as usernames, passwords, tokens, certificates or other sensitive information (strings) on iOS & Android',
    author: 'atroo',
  },
  {
    name: 'metamap-capacitor-plugin',
    href: 'git+https://github.com/GetMetaMap/mati-capacitor-plugin.git',
    title: 'metamap-capacitor-plugin',
    description: 'Capacitor plugin for MetaMapSDK',
    author: 'getmetamap',
  },
  {
    name: 'capacitor-android-shortcuts',
    href: 'git+https://github.com/NePheus/capacitor-android-shortcuts.git',
    title: 'capacitor-android-shortcuts',
    description: 'Add shortcuts in Android',
    author: 'nepheus',
  },
  {
    name: 'capacitor-ios-app-tracking',
    href: 'git+https://github.com/migtam628/capacitor-ios-app-tracking.git',
    title: 'capacitor-ios-app-tracking',
    description: 'App AD Tracking for iOS 14 and above',
    author: 'migtamrod1',
  },
  {
    name: '@fresha/capacitor-plugin-applepay',
    href: 'git+https://github.com/fresha/capacitor-plugin-applepay.git',
    title: 'capacitor-plugin-applepay',
    description: 'Apple Pay plugin for Capacitor',
    author: 'dziala',
  },
  {
    name: '@capacitor-community/stripe-identity',
    href: 'git+https://github.com/capacitor-community/stripe.git',
    title: 'stripe-identity',
    description: 'Stripe Identity SDK bindings for Capacitor Applications',
    author: 'jcesarmobile',
  },
  {
    name: '@leadscout/http',
    href: 'git+https://github.com/Homscout/http.git',
    title: 'http',
    description: 'A native HTTP plugin for CORS-free requests and file transfers',
    author: 'mrozema',
  },
  {
    name: 'capacitor-sim-pro',
    href: 'git+https://github.com/Pakshal-Jain25/capacitor-phonenumber-info.git',
    title: 'capacitor-sim-pro',
    description: "Capacitor plugin to get user phonenumber information from device's sim cards",
    author: 'pakshal-mobicloud',
  },
  {
    name: 'capacitor-plugin-dynamsoft-barcode-reader',
    href: 'git+https://github.com/tony-xlh/capacitor-plugin-dynamsoft-barcode-reader.git',
    title: 'capacitor-plugin-dynamsoft-barcode-reader',
    description: 'A capacitor plugin for Dynamsoft Barcode Reader',
    author: 'xulihang',
  },
  {
    name: '@capacitor-community/mdm-appconfig',
    href: 'git+https://github.com/capacitor-community/mdm-appconfig.git',
    title: 'mdm-appconfig',
    description: 'Capacitor community plugin for reading app configurations written by a MDM (see appconfig.org) such as VMWare Workspace One.',
    author: 'jcesarmobile',
  },
  {
    name: '@joinflux/capacitor-segment',
    href: 'git+https://github.com/joinflux/capacitor-segment.git',
    title: 'capacitor-segment',
    description: 'A Capacitor plugin for Segment analytics',
    author: 'gugahoi',
  },
  {
    name: 'sq-capacitor-plugin-ios-swipe-back',
    href: '',
    title: 'sq-capacitor-plugin-ios-swipe-back',
    description: 'Enable the back/forward swipe guestures support for iOS',
    author: 'a.poplavsky',
  },
  {
    name: 'capacitor-greatday-camera',
    href: 'git+https://github.com/asephermann/capacitor-greatday-camera.git',
    title: 'capacitor-greatday-camera',
    description: 'The capacitor plugin for camera function',
    author: 'asephermann',
  },
  {
    name: 'capacitor-plugin-ecies',
    href: 'git+https://github.com/stefanskiasan/capacitor-plugin-ecies.git.git',
    title: 'capacitor-plugin-ecies',
    description: 'Ecies Encryption',
    author: 'stefanskiasan',
  },
  {
    name: 'capacitor-mock-location-checker',
    href: 'git+https://github.com/asephermann/capacitor-mock-location-checker.git',
    title: 'capacitor-mock-location-checker',
    description: 'Capacitor plugin to avoid location mocking',
    author: 'asephermann',
  },
  {
    name: 'capacitor-plugin-camera',
    href: 'git+https://github.com/xulihang/capacitor-plugin-camera.git',
    title: 'capacitor-plugin-camera',
    description: 'A capacitor camera plugin',
    author: 'xulihang',
  },
  {
    name: '@pantrist/capacitor-plugin-ml-kit-text-recognition',
    href: 'git+https://github.com/Pantrist-dev/capacitor-plugin-ml-kit-text-recognition.git',
    title: 'capacitor-plugin-ml-kit-text-recognition',
    description: 'Capacitor Wrapper for TextRecognition of Gogoles ML-Kit',
    author: 'nico.lueg',
  },
  {
    name: '@anuradev/capacitor-phone-call-notification',
    href: 'git+https://github.com/angeloraso/capacitor-phone-call-notification.git.git',
    title: 'capacitor-phone-call-notification',
    description: 'Capacitor plugin to create phone call notifications',
    author: 'araso',
  },
  {
    name: '@capawesome-team/capacitor-android-foreground-service',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-android-foreground-service',
    description: 'Capacitor plugin to run a foreground service on Android.',
    author: 'robingenz',
  },
  {
    name: '@whiteguru/capacitor-plugin-file-picker',
    href: 'git+https://github.com/dragermrb/capacitor-plugin-file-picker.git',
    title: 'capacitor-plugin-file-picker',
    description: 'Capacitor plugin to pick files',
    author: 'dragermrb',
  },
  {
    name: 'capacitor-tiktok-event-sdk-plugin',
    href: 'git+https://github.com/hh12122/capacitor-tiktok-plugin.git.git',
    title: 'capacitor-tiktok-event-sdk-plugin',
    description: 'capacitor plugin for tiktok event sdk',
    author: 'hocineprint',
  },
  {
    name: 'callkit-voip-capacitor-plugin',
    href: 'git+https://github.com/Abhiranjanchaurasia/callkit-voip-capacitor-plugin.git',
    title: 'callkit-voip-capacitor-plugin',
    description: 'Provide CallKit and PushKit functionality to capacitor on iOS & android',
    author: 'abhiranjanchaurasia',
  },
  {
    name: '@evva/abrevva-capacitor',
    href: 'git+https://github.com/evva-sfw/abrevva-capacitor.git',
    title: 'abrevva-capacitor',
    description: 'Collection of tools to work with electronic EVVA access components.',
    author: 'sfw-evva',
  },
  {
    name: '@microblink/blinkcard-capacitor',
    href: 'git+https://github.com/blinkcard/blinkcard-capacitor.git',
    title: 'blinkcard-capacitor',
    description: 'AI-driven credit card scanning for cross-platform apps built with Capacitor.',
    author: 'mb-mpisacic',
  },
  {
    name: '@langx/capacitor-voice-recorder',
    href: 'git+https://github.com/langx/capacitor-voice-recorder.git',
    title: 'capacitor-voice-recorder',
    description: 'Capacitor plugin for voice recording',
    author: 'xuelink',
  },
  {
    name: '@olo/pay-capacitor',
    href: 'git+https://github.com/ololabs/olo-pay-capacitor-plugin-releases.git',
    title: 'pay-capacitor',
    description: 'Olo Pay SDK Capacitor Plugin',
    author: 'carol.cuatt',
  },
  {
    name: '@teamhive/capacitor-single-signon',
    href: 'git+https://github.com/TeamHive/capacitor-single-sign-on.git',
    title: 'capacitor-single-signon',
    description: 'This plugin is designed to streamline the single signon process between android and ios',
    author: 'emrado',
  },
  {
    name: '@capacitor-community/exif',
    href: 'git+https://github.com/capacitor-community/exif.git',
    title: 'exif',
    description: 'This plugin offers utility functions for interacting with image exif metadata',
    author: 'jcesarmobile',
  },
  {
    name: 'capacitor-gleap-plugin',
    href: 'git+https://github.com/GleapSDK/Capacitor-SDK.git',
    title: 'capacitor-gleap-plugin',
    description:
      'Gleap SDK for Capacitor is the easiest way to integrate Gleap into your Ionic apps! Achieve better app quality with comprehensive in-app bug reporting & customer feedback for your web-apps and websites. Many thanks to Stephan Nagel (congrapp) for his work',
    author: 'boehlerlukas',
  },
  {
    name: '@okode/capacitor-dynatrace',
    href: 'git+https://github.com/okode/capacitor-dynatrace.git',
    title: 'capacitor-dynatrace',
    description: 'Dynatrace plugin for Capacitor',
    author: 'okode',
  },
  {
    name: 'capacitor-plugin-backgroundservice',
    href: 'git+https://github.com/manpreet-mobicloud/capacitor-plugin-registerBackgroundService.git.git',
    title: 'capacitor-plugin-backgroundservice',
    description: 'Plugin to start application as foreground service to run in background continously even if the app is killed or device is rebooted',
    author: 'pakshal-mobicloud',
  },
  {
    name: 'capacitor-custom-google-maps',
    href: 'git+https://github.com/nasasutisna/capacitor-custom-google-maps.git',
    title: 'capacitor-custom-google-maps',
    description: 'capacitor custom plugin google maps',
    author: 'nasa.sutisna',
  },
  {
    name: 'capacitor-plugin-siri-shorts',
    href: 'git+https://github.com/TimoZacherl/capacitor-plugin-siri-shortcuts.git',
    title: 'capacitor-plugin-siri-shorts',
    description: 'Capacitor Plugin for Siri Shortcuts',
    author: 'timozacherl',
  },
  {
    name: '@belongnet/capacitor-google-auth',
    href: 'git+https://github.com/belongnet/CapacitorGoogleAuth.git',
    title: 'capacitor-google-auth',
    description: 'Google Auth plugin for capacitor.',
    author: 'reslear',
  },
  {
    name: 'capacitor-freerasp',
    href: 'git+https://github.com/talsec/Free-RASP-Capacitor.git',
    title: 'capacitor-freerasp',
    description: 'Capacitor plugin for improving app security and threat monitoring on Android and iOS mobile devices',
    author: 'talsec-app',
  },
  {
    name: 'enode-capacitor',
    href: 'git+https://github.com/eneco-online/enode-capacitor.git',
    title: 'enode-capacitor',
    description: 'Enode SDK for Capacitor',
    author: 'eneco-valentijn',
  },
  {
    name: '@okode/capacitor-plugin-secure-share',
    href: 'git+https://github.com/okode/capacitor-plugin-secure-share.git',
    title: 'capacitor-plugin-secure-share',
    description: 'Capacitor Secure Share Plugin',
    author: 'okode',
  },
  {
    name: '@capacitor-community/google-maps',
    href: 'git+https://github.com/capacitor-community/google-maps.git',
    title: 'google-maps',
    description: 'Plugin using native Maps API for Android and iOS.',
    author: 'jcesarmobile',
  },
  {
    name: '@capacitor-community/security-provider',
    href: 'git+https://github.com/capacitor-community/security-provider.git',
    title: 'security-provider',
    description: 'Capacitor plugin with methods to check and update the Android Security Provider',
    author: 'jcesarmobile',
  },
  {
    name: '@proteansoftware/capacitor-start-navigation',
    href: 'git+https://github.com/ProteanSoftware/capacitor-start-navigation.git',
    title: 'capacitor-start-navigation',
    description: 'Starts navigation in the native maps application',
    author: 'dave_proteansoftware',
  },
  {
    name: 'capacitor-areas',
    href: 'git+https://github.com/NePheus/capacitor-areas.git',
    title: 'capacitor-areas',
    description: 'This plugin provides functions to detect the devices safe area and the status bar and navigation bar height.',
    author: 'nepheus',
  },
  {
    name: 'capacitor-music-controls-plugin',
    href: 'git+https://github.com/ingageco/capacitor-music-controls-plugin.git',
    title: 'capacitor-music-controls-plugin',
    description: 'Implementation of MusicControls for Capacitor 3+ projects',
    author: 'ingage',
  },
  {
    name: '@capacitor-community/appcenter',
    href: 'git+https://github.com/capacitor-community/appcenter-sdk-capacitor.git',
    title: 'appcenter',
    description: "Capacitor Plugin for Microsoft's App Center SDK.",
    author: 'jcesarmobile',
  },
  {
    name: '@easy-connect/inappbrowser',
    href: 'git+https://github.com/Ticket-Gretchen/capacitor-inappbrowser.git',
    title: 'inappbrowser',
    description: 'Capacitor plugin in app browser',
    author: 'easyconnect',
  },
  {
    name: '@nativescript/capacitor',
    href: 'git+https://github.com/NativeScript/capacitor.git',
    title: 'capacitor',
    description: 'NativeScript for Capacitor',
    author: 'mukaschultze',
  },
  {
    name: '@whiteguru/capacitor-plugin-media-capture',
    href: 'git+https://github.com/dragermrb/capacitor-plugin-media-capture.git',
    title: 'capacitor-plugin-media-capture',
    description: 'Capacitor plugin to capture video',
    author: 'dragermrb',
  },
  {
    name: '@capacitor-community/flipper',
    href: 'git+https://github.com/capacitor-community/flipper.git',
    title: 'flipper',
    description: 'A native plugin for flipper debugger',
    author: 'jcesarmobile',
  },
  {
    name: '@velocitycubed/capacitor-plugin-msauth-v2',
    href: 'git+https://github.com/VelocityCubed/capacitor-plugin-msauth-v2.git',
    title: 'capacitor-plugin-msauth-v2',
    description: 'This plugin enables MSAL support for Capacitor.',
    author: 'allenjvn',
  },
  {
    name: 'opale-fire-analytics',
    href: 'git+https://github.com/ajpprod/opale-fire-analytics.git',
    title: 'opale-fire-analytics',
    description: 'A native plugin for firebase analytics.',
    author: 'opale-app',
  },
  {
    name: 'capacitor-webview-print',
    href: 'git+https://github.com/5uper/capacitor-webview-print.git',
    title: 'capacitor-webview-print',
    description: 'This is a Capacitor plugin for printing the webview. It supports the Web, iOS and Android Platform.',
    author: '5uper',
  },
  {
    name: 'serialconnectioncapacitor',
    href: 'git+https://github.com/laoapps/Serial_Connection_Capacitor.git',
    title: 'serialconnectioncapacitor',
    description: 'for serial connection',
    author: 'touyara',
  },
  {
    name: 'capacitor-incoming-call-kit',
    href: 'git+https://github.com/olarewajuakeemope/capacitor-incoming-call-kit.git',
    title: 'capacitor-incoming-call-kit',
    description: 'A Capacitor plugin to show incoming call in your Capacitor app(Custom for Android/Callkit for iOS)',
    author: 'olarewaopeyemi',
  },
  {
    name: 'capacitor-luna-id-sdk',
    href: 'git+https://github.com/qliqdev/capacitor-luna-id-sdk.git',
    title: 'capacitor-luna-id-sdk',
    description: 'LUNA SDK is a face recognition and analysis system that provides efficient and accurate processing of faces in images and video streams',
    author: 'abbas.fatullaev',
  },
  {
    name: '@agorapulse/capacitor-mediastore',
    href: 'git+https://github.com/agorapulse/capacitor-mediastore.git',
    title: 'capacitor-mediastore',
    description: 'Manage Android media files',
    author: 'benorama',
  },
  {
    name: '@capacitor-mlkit/selfie-segmentation',
    href: 'git+https://github.com/capawesome-team/capacitor-mlkit.git',
    title: 'selfie-segmentation',
    description: 'Capacitor plugin for ML Kit Selfie Segmentation.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-open-app-settings',
    href: 'git+https://github.com/swernimo/capacitor-open-app-settings.git',
    title: 'capacitor-open-app-settings',
    description: "A simple plugin that opens the app's settings page (if it exists)",
    author: 'swernimont',
  },
  {
    name: 'capacitor-biometric-lock',
    href: 'git+https://github.com/aeharding/capacitor-biometric-lock.git',
    title: 'capacitor-biometric-lock',
    description: 'Lock and unlock an app with biometrics',
    author: 'aeharding',
  },
  {
    name: '@nitra/capacitor-plugin-smartmerch-camera',
    href: 'git+https://github.com/abinbevefes/capacitor-plugin-smartmerch-camera.git',
    title: 'capacitor-plugin-smartmerch-camera',
    description: '-',
    author: 'vitaliytv',
  },
  {
    name: '@capacitor-mlkit/face-detection',
    href: 'git+https://github.com/capawesome-team/capacitor-mlkit.git',
    title: 'face-detection',
    description: 'Capacitor plugin for ML Kit Face Detection.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-nfc-launch',
    href: 'git+https://github.com/NePheus/capacitor-nfc-launch.git',
    title: 'capacitor-nfc-launch',
    description: 'Launch the app by a NFC tag and read the data',
    author: 'nepheus',
  },
  {
    name: '@rcastriotta/capacitor-social-login',
    href: 'git+https://github.com/rcastriotta/capacitor-social-login.git',
    title: 'capacitor-social-login',
    description: 'All social logins in one plugin',
    author: 'rcastriotta',
  },
  {
    name: '@teamhive/capacitor-video-recorder',
    href: 'git+https://github.com/TeamHive/capacitor-video-recorder.git',
    title: 'capacitor-video-recorder',
    description: 'Records video',
    author: 'emrado',
  },
  {
    name: 'capacitor-plugin-camera-forked',
    href: 'git+https://github.com/capexpert-io/capacitor-plugin-camera.git',
    title: 'capacitor-plugin-camera-forked',
    description: 'A capacitor camera plugin - A custom Capacitor camera plugin with additional features.',
    author: 'varunnayyar',
  },
  {
    name: '@capacitor-mlkit/translation',
    href: 'git+https://github.com/capawesome-team/capacitor-mlkit.git',
    title: 'translation',
    description: 'Capacitor plugin for ML Kit Translation.',
    author: 'robingenz',
  },
  {
    name: 'nostr-signer-capacitor-plugin',
    href: 'git+https://github.com/chebizarro/nostr-signer-capacitor-plugin.git',
    title: 'nostr-signer-capacitor-plugin',
    description: 'This capacitor plugin uses the intents package to interact with nostr signer apps on the Android platform',
    author: 'chebizarro',
  },
  {
    name: 'capacitor-plugin-audiosession-bluetooth',
    href: 'git+https://github.com/Jun-Murakami/capacitor-plugin-audiosession-bluetooth.git',
    title: 'capacitor-plugin-audiosession-bluetooth',
    description:
      'This capacitor plugin allows iOS applications to get notified audio about interrupts & route changes (for example when a headset is connected), and also query and override the audio device in use.',
    author: 'jun-murakami',
  },
  {
    name: 'capacitor-aad',
    href: 'https://github.com/leopq/capacitor-azure-active-directory.git',
    title: 'capacitor-aad',
    description: 'Capacitor plugin used to authenticate with Azure Active Directory on apps and PWAs!',
    author: 'leopq',
  },
  {
    name: 'capacitor-razorpay',
    href: 'git+https://github.com/razorpay/razorpay-cordova.git',
    title: 'capacitor-razorpay',
    description: 'This plugin is used for integration related to ionic Capacitor and its latest versions.',
    author: 'vivek_shindhe9604',
  },
  {
    name: 'capacitor-stripe-terminal',
    href: 'git+https://github.com/eventOneHQ/capacitor-stripe-terminal.git',
    title: 'capacitor-stripe-terminal',
    description: 'Capacitor plugin for Stripe Terminal (credit card readers).',
    author: 'nprail',
  },
  {
    name: 'capacitor-widgetsbridge-plugin',
    href: 'git+https://github.com/0xn33t/capacitor-widgetsbridge-plugin.git.git',
    title: 'capacitor-widgetsbridge-plugin',
    description: 'Capacitor plugin to interact with ios widgetkit',
    author: '0xn33t',
  },
  {
    name: '@aalzehla/capacitor-jailbreak-root-detection',
    href: 'git+https://github.com/aalzehla/capacitor-jailbreak-root-detection.git.git',
    title: 'capacitor-jailbreak-root-detection',
    description: 'Jailbreak Root detection plugin for capacitor.',
    author: 'aalzehla',
  },
  {
    name: '@dineengine/capacitor-olo-pay',
    href: 'git+https://gitlab.chepri.com/capacitor-plugins/olo-pay.git',
    title: 'capacitor-olo-pay',
    description: 'Gives access to native Olo Pay SDKs for use in Capacitor projects',
    author: 'dedeveloper',
  },
  {
    name: '@danyalwe/capacitor-sensors',
    href: 'git+https://github.com/zAlweNy26/capacitor-sensors.git',
    title: 'capacitor-sensors',
    description: 'Get access to every sensor present in the device!',
    author: 'danyalwe',
  },
  {
    name: 'capacitor-share-extension',
    href: 'git+https://github.com/calvinckho/capacitor-share-extension.git',
    title: 'capacitor-share-extension',
    description: 'A Capacitor Plugin that provides native capabilities to retrieve media files sent via iOS Share Extension and Android Send Intent events',
    author: 'calvinckho',
  },
  {
    name: '@sencrop/capacitor-intercom',
    href: 'git+https://github.com/sencrop/capacitor-intercom.git',
    title: 'capacitor-intercom',
    description: 'Intercom Plugin for Capacitor',
    author: 'jeromesencrop',
  },
  {
    name: 'capacitor-cache-clear',
    href: 'git+https://github.com/yourusername/capacitor-cache-clear.git',
    title: 'capacitor-cache-clear',
    description: 'A Capacitor plugin that provides methods to clear both WebView cache and app cache directory on Android and iOS platforms',
    author: 'varunnayyar',
  },
  {
    name: 'capacitor-plugin-filedownload',
    href: 'git+https://github.com/AlwaysLoveme/capacitor-plugin-filedownload.git.git',
    title: 'capacitor-plugin-filedownload',
    description: 'a file download plugin for capacitor3.0+',
    author: 'zhuxian',
  },
  {
    name: '@micahlt/capacitor-dark-mode',
    href: 'git+https://github.com/hinddeep/ionicCapacitorDarkMode.git',
    title: 'capacitor-dark-mode',
    description: 'Handle dark mode changes on android and iOS',
    author: 'micahlt',
  },
  { name: 'capacitor-print', href: 'git+https://github.com/leoruhland/capacitor-print.git', title: 'capacitor-print', description: 'Print the webview', author: 'leoruhland' },
  {
    name: '@hotend/capacitor-file-picker',
    href: 'git+https://github.com/rbreckner/capawesome-capacitor-plugins.git',
    title: 'capacitor-file-picker',
    description: 'Capacitor plugin that allows the user to select a file.',
    author: 'pommes',
  },
  {
    name: '@leadscout/intercom',
    href: 'git+https://github.com/Homscout/intercom.git',
    title: 'intercom',
    description: 'Enable Intercom features for Capacitor apps',
    author: 'mrozema',
  },
  {
    name: '@squareetlabs/capacitor-openwith',
    href: 'git+https://github.com/squareetlabs/capacitor-openwith.git',
    title: 'capacitor-openwith',
    description: 'Capacitor plugin to handle files shared from other apps',
    author: 'squareetlabs',
  },
  {
    name: '@capacitor-mlkit/face-mesh-detection',
    href: 'git+https://github.com/capawesome-team/capacitor-mlkit.git',
    title: 'face-mesh-detection',
    description: 'Capacitor plugin for ML Kit Face Mesh Detection.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-root-jailbreak-detector',
    href: 'git+https://github.com/asephermann/capacitor-root-jailbreak-detector.git',
    title: 'capacitor-root-jailbreak-detector',
    description: 'Capacitor Plugin Root/Jailbreak Detection',
    author: 'asephermann',
  },
  {
    name: '@mamillastre/capacitor-environment',
    href: 'git+https://github.com/mamillastre/capacitor-environment.git',
    title: 'capacitor-environment',
    description: 'Capacitor plugin to get JSON based environment specific data',
    author: 'mamillastre',
  },
  { name: '@zeply-ou/google-pay-capacitor', href: '', title: 'google-pay-capacitor', description: 'Google Pay plugin for Capacitor', author: 'nikos.mastragelis' },
  {
    name: '@bobbyg603/capacitor-social-login',
    href: 'git+https://github.com/Cap-go/capacitor-social-login.git',
    title: 'capacitor-social-login',
    description: 'All social logins in one plugin',
    author: 'bobbyg603',
  },
  {
    name: 'capacitor-plugin-android-insets',
    href: 'git+https://github.com/owlsdepartment/capacitor-plugin-android-insets.git',
    title: 'capacitor-plugin-android-insets',
    description: 'Capacitro plugin for retrieving proper top offset of Android status bar',
    author: 'przyb',
  },
  {
    name: '@aparajita/capacitor-logger',
    href: 'git+https://github.com/aparajita/capacitor-logger.git',
    title: 'capacitor-logger',
    description: 'Enhanced, universal logging for Capacitor apps and plugins',
    author: 'ckgaparajita',
  },
  {
    name: 'capacitor-facebook-events',
    href: 'git+https://github.com/Linknpay/capacitor-facebook-events.git',
    title: 'capacitor-facebook-events',
    description: 'Facebook events tracking in Capacitor applications',
    author: 'gketata',
  },
  {
    name: '@selaliadobor/apple-sign-in',
    href: 'git+https://github.com/capacitor-community/apple-sign-in.git',
    title: 'apple-sign-in',
    description: 'Capacitor Sign in with Apple',
    author: 'selaliadobor',
  },
  {
    name: 'capacitor-exit-app-ios',
    href: 'git+https://github.com/tienmanh94hbk/capacitor-exit-app-ios.git',
    title: 'capacitor-exit-app-ios',
    description: 'exit app on ios',
    author: 'dotienmanh',
  },
  {
    name: '@capgo/native-purchases',
    href: 'git+https://github.com/Cap-go/native-purchases.git',
    title: 'native-purchases',
    description: 'In-app Subscriptions Made Easy',
    author: 'riderx',
  },
  {
    name: '@felix-health/capacitor-segment',
    href: 'git+https://github.com/FelixHealth/capacitor-segment.git',
    title: 'capacitor-segment',
    description: 'Capacitor plugin for Segment analytics',
    author: 'felix-eddiemachete',
  },
  {
    name: '@heap/heap-capacitor-bridge',
    href: 'git+https://github.com/heap.git',
    title: 'heap-capacitor-bridge',
    description: 'Heap manual track SDK for Capacitor on native platforms',
    author: 'jamesnghiem.heap',
  },
  {
    name: '@givenergy/barcode-scanning',
    href: 'git+https://github.com/capawesome-team/capacitor-mlkit.git',
    title: 'barcode-scanning',
    description: 'Capacitor plugin for ML Kit Barcode Scanning.',
    author: 'givenergy-jamiem',
  },
  {
    name: '@codext/capacitor-wifi',
    href: 'git+https://github.com/codextde/capacitor-wifi.git',
    title: 'capacitor-wifi',
    description: 'Connect to Wifi through your capacitor plugin. Good for IoT device connections.',
    author: 'danielehrhardt',
  },
  {
    name: '@capawesome/capacitor-app-shortcuts',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-app-shortcuts',
    description: 'Capacitor plugin to manage app shortcuts and quick actions.',
    author: 'robingenz',
  },
  {
    name: '@cycraft/capacitor-repro',
    href: 'git+https://github.com/CyCraft/ReproSDKPlugin.git',
    title: 'capacitor-repro',
    description: 'Unofficial Capacitor plugin for Repro SDK.',
    author: 'mesqueeb',
  },
  {
    name: 'capacitor-plugin-phone-call',
    href: 'git+https://github.com/AlwaysLoveme/capacitor-plugin-phonecall.git.git',
    title: 'capacitor-plugin-phone-call',
    description: 'a native phone call plugin for Capacitor',
    author: 'zhuxian',
  },
  {
    name: 'posthog-cap',
    href: 'git+https://github.com/Pama-Lee/capacitor-plugins.git',
    title: 'posthog-cap',
    description: 'Custom Capacitor plugin for PostHog SDK.',
    author: 'pamalee',
  },
  {
    name: 'capacitor-autostartmanager',
    href: 'git+https://github.com/asephermann/capacitor-autostartmanager.git',
    title: 'capacitor-autostartmanager',
    description: 'Auto Start Manager, Check Automatic Date Time Zone, Check Camera',
    author: 'asephermann',
  },
  {
    name: '@capacitor-community/appcenter-crashes',
    href: 'git+https://github.com/capacitor-community/appcenter-sdk-capacitor.git#master',
    title: 'appcenter-crashes',
    description: "Capacitor plugin for Microsoft's App Center Crashes",
    author: 'jcesarmobile',
  },
  {
    name: '@slothfi/capacitor-social-login',
    href: 'git+https://github.com/Slothfi/capacitor-social-login.git',
    title: 'capacitor-social-login',
    description: 'All social logins in one plugin',
    author: '0xghosty',
  },
  {
    name: '@hiloenergie/capacitor-plugin-safe-area',
    href: 'https://dev.azure.com/HQCdevops/HQC/_git/capacitor-community-safe-area',
    title: 'capacitor-plugin-safe-area',
    description: 'A plugin to expose the safe area insets from the native iOS/Android device to your web project.',
    author: 'jbouchard_hiloenergie',
  },
  {
    name: 'capacitor-plugin-silent-notifications',
    href: 'git+https://github.com/greenygh0st/capacitor-plugin-silent-notifications.git',
    title: 'capacitor-plugin-silent-notifications',
    description: 'Allows an a Capacitor application to handle iOS remote/silent push notifications',
    author: 'greenygh0st',
  },
  {
    name: '@hiloenergie/capacitor-plugin-native-gestures-area',
    href: 'https://dev.azure.com/HQCdevops/HQC/_git/capacitor-plugin-native-gestures-area',
    title: 'capacitor-plugin-native-gestures-area',
    description: 'A plugin to expose the native gestures area insets from the native iOS/Android device to your web project.',
    author: 'jfcere_hiloenergie',
  },
  {
    name: 'capacitor-geofence-box-tracker',
    href: 'git+https://github.com/jaimbox/capacitor-geofence-box-tracker.git',
    title: 'capacitor-geofence-box-tracker',
    description: 'Capacitor Geofence Tracker',
    author: 'jaimbox',
  },
  {
    name: 'adjust-capacitor-plugin',
    href: 'git+https://github.com/fieprmxxwx83/adjust-capacitor-plugin.git',
    title: 'adjust-capacitor-plugin',
    description: 'Adjust SDK plugin for Capacitor',
    author: 'fieprmxxwx83',
  },
  {
    name: '@capawesome/capacitor-screenshot',
    href: 'git+https://github.com/capawesome-team/capacitor-plugins.git',
    title: 'capacitor-screenshot',
    description: 'Capacitor plugin for taking screenshots.',
    author: 'robingenz',
  },
  {
    name: 'capacitor-reader',
    href: 'git+https://github.com/aeharding/capacitor-reader.git',
    title: 'capacitor-reader',
    description: 'Opens a simplified in app browser, prioritizing readability',
    author: 'aeharding',
  },
  {
    name: '@salurusrinivasarao/emarsys-sdk-wrapper-plugin',
    href: 'git+https://github.com/srinivassaluru/emarsys-sdk-wrapper-plugin.git',
    title: 'emarsys-sdk-wrapper-plugin',
    description: 'Custom Capacitor Plugin To have communication with Emarsys SDK',
    author: 'salurusrinivasarao',
  },
  {
    name: 'capacitor-health-connect',
    href: 'git+https://github.com/ubie-oss/capacitor-health-connect.git',
    title: 'capacitor-health-connect',
    description: 'Android Health Connect integration for Capacitor',
    author: 'monchi',
  },
  {
    name: '@bazuka5801/photoviewer',
    href: 'git+https://github.com/capacitor-community/photoviewer.git',
    title: 'photoviewer',
    description: 'PhotoViewer table images with fullscreen and sharing capabilities',
    author: 'bazuka5801',
  },
  {
    name: '@polyfillhq/capacitor-ios-swipe-gesture',
    href: 'git+https://github.com/polyfill-hq/capacitor-ios-swipe-gesture.git',
    title: 'capacitor-ios-swipe-gesture',
    description: 'Handles enabling / disabling the iOS back swipe gesture',
    author: 'kayone',
  },
  {
    name: '@movilitascloud/barcode-scanning-fork',
    href: 'git+https://github.com/capawesome-team/capacitor-mlkit.git',
    title: 'barcode-scanning-fork',
    description: 'Capacitor plugin for ML Kit Barcode Scanning.',
    author: 'mvcloud',
  },
  {
    name: 'bhd-capacitor-nfc-tag',
    href: 'git+https://dev.azure.com/bhdleon/BHDL-Capitulo-FrontEnd-System-Best-Practice.git',
    title: 'bhd-capacitor-nfc-tag',
    description: 'Read/Write Nfc tags BHD plugin.',
    author: 'dwane_jimenez',
  },
  {
    name: '@bugfender/capacitor',
    href: 'git+https://github.com/bugfender/bugfender-capacitor.git',
    title: 'capacitor',
    description: 'Remote logging with Bugfender',
    author: 'gimix3',
  },
  {
    name: 'capacitor-community-contacts',
    href: 'git+https://github.com/capacitor-community/contacts.git',
    title: 'capacitor-community-contacts',
    description: 'Contacts Plugin for Capacitor',
    author: 'denis_galkin',
  },
  {
    name: 'capacitor-kakao-login-plugin',
    href: 'git+https://github.com/nerdFrenzs/capacitor-kakao-login-plugin.git',
    title: 'capacitor-kakao-login-plugin',
    description: 'This plugin is only used in Native capacitor(not web implemented)',
    author: 'nerdfrenzs',
  },
  {
    name: '@felix-health/inappbrowser',
    href: 'git+https://github.com/Felix-Health/capacitor-inappbrowser.git',
    title: 'inappbrowser',
    description: 'Capacitor plugin in app browser | Felix Health fork',
    author: 'felix-eddiemachete',
  },
  {
    name: 'capacitor-plugin-notifyvisitors',
    href: '',
    title: 'capacitor-plugin-notifyvisitors',
    description: 'A Capacitor Plugin of NotifyVisitors SDK for push notifications and surveys',
    author: 'notifyvisitors_sdk',
  },
  {
    name: '@albgen/capacitor-zpl-plugin',
    href: 'git+https://github.com/albgen/capacitor-zpl-plugin.git.git',
    title: 'capacitor-zpl-plugin',
    description: 'A plugin which facilitate the communication with ZPL Printers.',
    author: 'albgen',
  },
  {
    name: 'capacitor-clear-cache',
    href: 'git+https://github.com/aeharding/capacitor-clear-cache.git',
    title: 'capacitor-clear-cache',
    description: 'Clear various app caches',
    author: 'aeharding',
  },
  {
    name: 'media-captura',
    href: 'git+https://github.com/thefrikz18/MediaCapture.git',
    title: 'media-captura',
    description: 'Plugin Capacitor Media capture',
    author: 'thefrikz18',
  },
]
