name: Create READMEs

permissions:
  checks: write
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build code and release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile

      - name: Generate packages list
        run: node scripts/generate_actions.mjs
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Create READMEs
        run: node scripts/write_readme.mjs
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Train model from READMEs
        run: node scripts/train_model.mjs
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Generate tutorials
        run: node scripts/generate_tutorials.mjs
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
      - name: Commit generated files
        run: |
          git config --global user.name "Rishi Raj Jain"
          git config --global user.email "rishi18304@iiitd.ac.in"
          git add -A
          git commit -m "Commit generated files"
          git push origin main -f
        working-directory: ./
